// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: best_bid_offer.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// below enum is just for reference only, not used in this message
type BestBidOffer_PresenceBits int32

const (
	BestBidOffer_BID        BestBidOffer_PresenceBits = 1
	BestBidOffer_ASK        BestBidOffer_PresenceBits = 2
	BestBidOffer_LEAN_PRICE BestBidOffer_PresenceBits = 4
)

// Enum value maps for BestBidOffer_PresenceBits.
var (
	BestBidOffer_PresenceBits_name = map[int32]string{
		1: "BID",
		2: "ASK",
		4: "LEAN_PRICE",
	}
	BestBidOffer_PresenceBits_value = map[string]int32{
		"BID":        1,
		"ASK":        2,
		"LEAN_PRICE": 4,
	}
)

func (x BestBidOffer_PresenceBits) Enum() *BestBidOffer_PresenceBits {
	p := new(BestBidOffer_PresenceBits)
	*p = x
	return p
}

func (x BestBidOffer_PresenceBits) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BestBidOffer_PresenceBits) Descriptor() protoreflect.EnumDescriptor {
	return file_best_bid_offer_proto_enumTypes[0].Descriptor()
}

func (BestBidOffer_PresenceBits) Type() protoreflect.EnumType {
	return &file_best_bid_offer_proto_enumTypes[0]
}

func (x BestBidOffer_PresenceBits) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *BestBidOffer_PresenceBits) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = BestBidOffer_PresenceBits(num)
	return nil
}

// Deprecated: Use BestBidOffer_PresenceBits.Descriptor instead.
func (BestBidOffer_PresenceBits) EnumDescriptor() ([]byte, []int) {
	return file_best_bid_offer_proto_rawDescGZIP(), []int{0, 0}
}

type BestBidOffer struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TemplateId      *int32                 `protobuf:"varint,154467,req,name=template_id,json=templateId" json:"template_id,omitempty"`                  // PB_OFFSET + MNM_TEMPLATE_ID
	Symbol          *string                `protobuf:"bytes,110100,opt,name=symbol" json:"symbol,omitempty"`                                             // PB_OFFSET + MNM_SYMBOL
	Exchange        *string                `protobuf:"bytes,110101,opt,name=exchange" json:"exchange,omitempty"`                                         // PB_OFFSET + MNM_EXCHANGE
	PresenceBits    *uint32                `protobuf:"varint,149138,opt,name=presence_bits,json=presenceBits" json:"presence_bits,omitempty"`            // PB_OFFSET + MNM_PRICING_INDICATOR
	ClearBits       *uint32                `protobuf:"varint,154571,opt,name=clear_bits,json=clearBits" json:"clear_bits,omitempty"`                     // PB_OFFSET + MNM_DISPLAY_INDICATOR
	IsSnapshot      *bool                  `protobuf:"varint,110121,opt,name=is_snapshot,json=isSnapshot" json:"is_snapshot,omitempty"`                  // PB_OFFSET + MNM_UPDATE_TYPE
	BidPrice        *float64               `protobuf:"fixed64,100022,opt,name=bid_price,json=bidPrice" json:"bid_price,omitempty"`                       // PB_OFFSET + MNM_BID_PRICE
	BidSize         *int32                 `protobuf:"varint,100030,opt,name=bid_size,json=bidSize" json:"bid_size,omitempty"`                           // PB_OFFSET + MNM_BID_SIZE
	BidOrders       *int32                 `protobuf:"varint,154403,opt,name=bid_orders,json=bidOrders" json:"bid_orders,omitempty"`                     // PB_OFFSET + MNM_BID_NO_OF_ORDERS
	BidImplicitSize *int32                 `protobuf:"varint,154867,opt,name=bid_implicit_size,json=bidImplicitSize" json:"bid_implicit_size,omitempty"` // PB_OFFSET + MNM_BID_IMPLICIT_SIZE
	BidTime         *string                `protobuf:"bytes,100266,opt,name=bid_time,json=bidTime" json:"bid_time,omitempty"`
	AskPrice        *float64               `protobuf:"fixed64,100025,opt,name=ask_price,json=askPrice" json:"ask_price,omitempty"`                       // PB_OFFSET + MNM_ASK_PRICE
	AskSize         *int32                 `protobuf:"varint,100031,opt,name=ask_size,json=askSize" json:"ask_size,omitempty"`                           // PB_OFFSET + MNM_ASK_SIZE
	AskOrders       *int32                 `protobuf:"varint,154404,opt,name=ask_orders,json=askOrders" json:"ask_orders,omitempty"`                     // PB_OFFSET + MNM_ASK_NO_OF_ORDERS
	AskImplicitSize *int32                 `protobuf:"varint,154868,opt,name=ask_implicit_size,json=askImplicitSize" json:"ask_implicit_size,omitempty"` // PB_OFFSET + MNM_ASK_IMPLICIT_SIZE
	AskTime         *string                `protobuf:"bytes,100267,opt,name=ask_time,json=askTime" json:"ask_time,omitempty"`
	LeanPrice       *float64               `protobuf:"fixed64,154909,opt,name=lean_price,json=leanPrice" json:"lean_price,omitempty"` // PB_OFFSET + MNM_LEAN_PRICE
	Ssboe           *int32                 `protobuf:"varint,150100,opt,name=ssboe" json:"ssboe,omitempty"`                           // PB_OFFSET + MNM_SECONDS_SINCE_BOE
	Usecs           *int32                 `protobuf:"varint,150101,opt,name=usecs" json:"usecs,omitempty"`                           // PB_OFFSET + MNM_USECS
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BestBidOffer) Reset() {
	*x = BestBidOffer{}
	mi := &file_best_bid_offer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BestBidOffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BestBidOffer) ProtoMessage() {}

func (x *BestBidOffer) ProtoReflect() protoreflect.Message {
	mi := &file_best_bid_offer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BestBidOffer.ProtoReflect.Descriptor instead.
func (*BestBidOffer) Descriptor() ([]byte, []int) {
	return file_best_bid_offer_proto_rawDescGZIP(), []int{0}
}

func (x *BestBidOffer) GetTemplateId() int32 {
	if x != nil && x.TemplateId != nil {
		return *x.TemplateId
	}
	return 0
}

func (x *BestBidOffer) GetSymbol() string {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return ""
}

func (x *BestBidOffer) GetExchange() string {
	if x != nil && x.Exchange != nil {
		return *x.Exchange
	}
	return ""
}

func (x *BestBidOffer) GetPresenceBits() uint32 {
	if x != nil && x.PresenceBits != nil {
		return *x.PresenceBits
	}
	return 0
}

func (x *BestBidOffer) GetClearBits() uint32 {
	if x != nil && x.ClearBits != nil {
		return *x.ClearBits
	}
	return 0
}

func (x *BestBidOffer) GetIsSnapshot() bool {
	if x != nil && x.IsSnapshot != nil {
		return *x.IsSnapshot
	}
	return false
}

func (x *BestBidOffer) GetBidPrice() float64 {
	if x != nil && x.BidPrice != nil {
		return *x.BidPrice
	}
	return 0
}

func (x *BestBidOffer) GetBidSize() int32 {
	if x != nil && x.BidSize != nil {
		return *x.BidSize
	}
	return 0
}

func (x *BestBidOffer) GetBidOrders() int32 {
	if x != nil && x.BidOrders != nil {
		return *x.BidOrders
	}
	return 0
}

func (x *BestBidOffer) GetBidImplicitSize() int32 {
	if x != nil && x.BidImplicitSize != nil {
		return *x.BidImplicitSize
	}
	return 0
}

func (x *BestBidOffer) GetBidTime() string {
	if x != nil && x.BidTime != nil {
		return *x.BidTime
	}
	return ""
}

func (x *BestBidOffer) GetAskPrice() float64 {
	if x != nil && x.AskPrice != nil {
		return *x.AskPrice
	}
	return 0
}

func (x *BestBidOffer) GetAskSize() int32 {
	if x != nil && x.AskSize != nil {
		return *x.AskSize
	}
	return 0
}

func (x *BestBidOffer) GetAskOrders() int32 {
	if x != nil && x.AskOrders != nil {
		return *x.AskOrders
	}
	return 0
}

func (x *BestBidOffer) GetAskImplicitSize() int32 {
	if x != nil && x.AskImplicitSize != nil {
		return *x.AskImplicitSize
	}
	return 0
}

func (x *BestBidOffer) GetAskTime() string {
	if x != nil && x.AskTime != nil {
		return *x.AskTime
	}
	return ""
}

func (x *BestBidOffer) GetLeanPrice() float64 {
	if x != nil && x.LeanPrice != nil {
		return *x.LeanPrice
	}
	return 0
}

func (x *BestBidOffer) GetSsboe() int32 {
	if x != nil && x.Ssboe != nil {
		return *x.Ssboe
	}
	return 0
}

func (x *BestBidOffer) GetUsecs() int32 {
	if x != nil && x.Usecs != nil {
		return *x.Usecs
	}
	return 0
}

var File_best_bid_offer_proto protoreflect.FileDescriptor

const file_best_bid_offer_proto_rawDesc = "" +
	"\n" +
	"\x14best_bid_offer.proto\x12\x03rti\"\xa7\x05\n" +
	"\fBestBidOffer\x12!\n" +
	"\vtemplate_id\x18\xe3\xb6\t \x02(\x05R\n" +
	"templateId\x12\x18\n" +
	"\x06symbol\x18\x94\xdc\x06 \x01(\tR\x06symbol\x12\x1c\n" +
	"\bexchange\x18\x95\xdc\x06 \x01(\tR\bexchange\x12%\n" +
	"\rpresence_bits\x18\x92\x8d\t \x01(\rR\fpresenceBits\x12\x1f\n" +
	"\n" +
	"clear_bits\x18˷\t \x01(\rR\tclearBits\x12!\n" +
	"\vis_snapshot\x18\xa9\xdc\x06 \x01(\bR\n" +
	"isSnapshot\x12\x1d\n" +
	"\tbid_price\x18\xb6\x8d\x06 \x01(\x01R\bbidPrice\x12\x1b\n" +
	"\bbid_size\x18\xbe\x8d\x06 \x01(\x05R\abidSize\x12\x1f\n" +
	"\n" +
	"bid_orders\x18\xa3\xb6\t \x01(\x05R\tbidOrders\x12,\n" +
	"\x11bid_implicit_size\x18\xf3\xb9\t \x01(\x05R\x0fbidImplicitSize\x12\x1b\n" +
	"\bbid_time\x18\xaa\x8f\x06 \x01(\tR\abidTime\x12\x1d\n" +
	"\task_price\x18\xb9\x8d\x06 \x01(\x01R\baskPrice\x12\x1b\n" +
	"\bask_size\x18\xbf\x8d\x06 \x01(\x05R\aaskSize\x12\x1f\n" +
	"\n" +
	"ask_orders\x18\xa4\xb6\t \x01(\x05R\taskOrders\x12,\n" +
	"\x11ask_implicit_size\x18\xf4\xb9\t \x01(\x05R\x0faskImplicitSize\x12\x1b\n" +
	"\bask_time\x18\xab\x8f\x06 \x01(\tR\aaskTime\x12\x1f\n" +
	"\n" +
	"lean_price\x18\x9d\xba\t \x01(\x01R\tleanPrice\x12\x16\n" +
	"\x05ssboe\x18Ԕ\t \x01(\x05R\x05ssboe\x12\x16\n" +
	"\x05usecs\x18Ք\t \x01(\x05R\x05usecs\"0\n" +
	"\fPresenceBits\x12\a\n" +
	"\x03BID\x10\x01\x12\a\n" +
	"\x03ASK\x10\x02\x12\x0e\n" +
	"\n" +
	"LEAN_PRICE\x10\x04B\x1eZ\x1cquant/extensions/rithmic/api"

var (
	file_best_bid_offer_proto_rawDescOnce sync.Once
	file_best_bid_offer_proto_rawDescData []byte
)

func file_best_bid_offer_proto_rawDescGZIP() []byte {
	file_best_bid_offer_proto_rawDescOnce.Do(func() {
		file_best_bid_offer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_best_bid_offer_proto_rawDesc), len(file_best_bid_offer_proto_rawDesc)))
	})
	return file_best_bid_offer_proto_rawDescData
}

var file_best_bid_offer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_best_bid_offer_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_best_bid_offer_proto_goTypes = []any{
	(BestBidOffer_PresenceBits)(0), // 0: rti.BestBidOffer.PresenceBits
	(*BestBidOffer)(nil),           // 1: rti.BestBidOffer
}
var file_best_bid_offer_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_best_bid_offer_proto_init() }
func file_best_bid_offer_proto_init() {
	if File_best_bid_offer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_best_bid_offer_proto_rawDesc), len(file_best_bid_offer_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_best_bid_offer_proto_goTypes,
		DependencyIndexes: file_best_bid_offer_proto_depIdxs,
		EnumInfos:         file_best_bid_offer_proto_enumTypes,
		MessageInfos:      file_best_bid_offer_proto_msgTypes,
	}.Build()
	File_best_bid_offer_proto = out.File
	file_best_bid_offer_proto_goTypes = nil
	file_best_bid_offer_proto_depIdxs = nil
}
