// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: depth_by_order.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DepthByOrder_TransactionType int32

const (
	DepthByOrder_BUY  DepthByOrder_TransactionType = 1
	DepthByOrder_SELL DepthByOrder_TransactionType = 2
)

// Enum value maps for DepthByOrder_TransactionType.
var (
	DepthByOrder_TransactionType_name = map[int32]string{
		1: "BUY",
		2: "SELL",
	}
	DepthByOrder_TransactionType_value = map[string]int32{
		"BUY":  1,
		"SELL": 2,
	}
)

func (x DepthByOrder_TransactionType) Enum() *DepthByOrder_TransactionType {
	p := new(DepthByOrder_TransactionType)
	*p = x
	return p
}

func (x DepthByOrder_TransactionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DepthByOrder_TransactionType) Descriptor() protoreflect.EnumDescriptor {
	return file_depth_by_order_proto_enumTypes[0].Descriptor()
}

func (DepthByOrder_TransactionType) Type() protoreflect.EnumType {
	return &file_depth_by_order_proto_enumTypes[0]
}

func (x DepthByOrder_TransactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *DepthByOrder_TransactionType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = DepthByOrder_TransactionType(num)
	return nil
}

// Deprecated: Use DepthByOrder_TransactionType.Descriptor instead.
func (DepthByOrder_TransactionType) EnumDescriptor() ([]byte, []int) {
	return file_depth_by_order_proto_rawDescGZIP(), []int{0, 0}
}

type DepthByOrder_UpdateType int32

const (
	DepthByOrder_NEW    DepthByOrder_UpdateType = 1
	DepthByOrder_CHANGE DepthByOrder_UpdateType = 2
	DepthByOrder_DELETE DepthByOrder_UpdateType = 3
)

// Enum value maps for DepthByOrder_UpdateType.
var (
	DepthByOrder_UpdateType_name = map[int32]string{
		1: "NEW",
		2: "CHANGE",
		3: "DELETE",
	}
	DepthByOrder_UpdateType_value = map[string]int32{
		"NEW":    1,
		"CHANGE": 2,
		"DELETE": 3,
	}
)

func (x DepthByOrder_UpdateType) Enum() *DepthByOrder_UpdateType {
	p := new(DepthByOrder_UpdateType)
	*p = x
	return p
}

func (x DepthByOrder_UpdateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DepthByOrder_UpdateType) Descriptor() protoreflect.EnumDescriptor {
	return file_depth_by_order_proto_enumTypes[1].Descriptor()
}

func (DepthByOrder_UpdateType) Type() protoreflect.EnumType {
	return &file_depth_by_order_proto_enumTypes[1]
}

func (x DepthByOrder_UpdateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *DepthByOrder_UpdateType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = DepthByOrder_UpdateType(num)
	return nil
}

// Deprecated: Use DepthByOrder_UpdateType.Descriptor instead.
func (DepthByOrder_UpdateType) EnumDescriptor() ([]byte, []int) {
	return file_depth_by_order_proto_rawDescGZIP(), []int{0, 1}
}

type DepthByOrder struct {
	state              protoimpl.MessageState         `protogen:"open.v1"`
	TemplateId         *int32                         `protobuf:"varint,154467,req,name=template_id,json=templateId" json:"template_id,omitempty"`                                                      // PB_OFFSET + MNM_TEMPLATE_ID
	Symbol             *string                        `protobuf:"bytes,110100,opt,name=symbol" json:"symbol,omitempty"`                                                                                 // PB_OFFSET + MNM_SYMBOL
	Exchange           *string                        `protobuf:"bytes,110101,opt,name=exchange" json:"exchange,omitempty"`                                                                             // PB_OFFSET + MNM_EXCHANGE
	SequenceNumber     *uint64                        `protobuf:"varint,112002,opt,name=sequence_number,json=sequenceNumber" json:"sequence_number,omitempty"`                                          // PB_OFFSET + MNM_SEQUENCE_NUMBER
	UpdateType         []DepthByOrder_UpdateType      `protobuf:"varint,110121,rep,name=update_type,json=updateType,enum=rti.DepthByOrder_UpdateType" json:"update_type,omitempty"`                     // PB_OFFSET + MNM_UPDATE_TYPE
	TransactionType    []DepthByOrder_TransactionType `protobuf:"varint,153612,rep,name=transaction_type,json=transactionType,enum=rti.DepthByOrder_TransactionType" json:"transaction_type,omitempty"` // PB_OFFSET + MNM_MARKET_DEPTH_SIDE
	DepthPrice         []float64                      `protobuf:"fixed64,154405,rep,name=depth_price,json=depthPrice" json:"depth_price,omitempty"`                                                     // PB_OFFSET + MNM_MARKET_DEPTH_PRICE
	PrevDepthPrice     []float64                      `protobuf:"fixed64,154906,rep,name=prev_depth_price,json=prevDepthPrice" json:"prev_depth_price,omitempty"`                                       // PB_OFFSET + MNM_PREVIOUS_MARKET_DEPTH_PRICE
	PrevDepthPriceFlag []bool                         `protobuf:"varint,154930,rep,name=prev_depth_price_flag,json=prevDepthPriceFlag" json:"prev_depth_price_flag,omitempty"`                          // PB_OFFSET + MNM_PREVIOUS_MARKET_DEPTH_PRICE_FLAG
	DepthSize          []int32                        `protobuf:"varint,154406,rep,name=depth_size,json=depthSize" json:"depth_size,omitempty"`                                                         // PB_OFFSET + MNM_MARKET_DEPTH_SIZE
	DepthOrderPriority []uint64                       `protobuf:"varint,153613,rep,name=depth_order_priority,json=depthOrderPriority" json:"depth_order_priority,omitempty"`                            // PB_OFFSET + MNM_MARKET_DEPTH_ORDER_PRIORITY
	ExchangeOrderId    []string                       `protobuf:"bytes,149238,rep,name=exchange_order_id,json=exchangeOrderId" json:"exchange_order_id,omitempty"`                                      // PB_OFFSET + MNM_EXCH_ORD_ID
	Ssboe              *int32                         `protobuf:"varint,150100,opt,name=ssboe" json:"ssboe,omitempty"`                                                                                  // PB_OFFSET + MNM_SECONDS_SINCE_BOE
	Usecs              *int32                         `protobuf:"varint,150101,opt,name=usecs" json:"usecs,omitempty"`                                                                                  // PB_OFFSET + MNM_USECS
	SourceSsboe        *int32                         `protobuf:"varint,150400,opt,name=source_ssboe,json=sourceSsboe" json:"source_ssboe,omitempty"`                                                   // PB_OFFSET + MNM_SOURCE_SSBOE
	SourceUsecs        *int32                         `protobuf:"varint,150401,opt,name=source_usecs,json=sourceUsecs" json:"source_usecs,omitempty"`                                                   // PB_OFFSET + MNM_SOURCE_USECS
	SourceNsecs        *int32                         `protobuf:"varint,150404,opt,name=source_nsecs,json=sourceNsecs" json:"source_nsecs,omitempty"`                                                   // PB_OFFSET + MNM_SOURCE_NSECS
	JopSsboe           *int32                         `protobuf:"varint,150600,opt,name=jop_ssboe,json=jopSsboe" json:"jop_ssboe,omitempty"`                                                            // PB_OFFSET + MNM_JOP_SSBOE
	JopNsecs           *int32                         `protobuf:"varint,150604,opt,name=jop_nsecs,json=jopNsecs" json:"jop_nsecs,omitempty"`                                                            // PB_OFFSET + MNM_JOP_NSECS
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DepthByOrder) Reset() {
	*x = DepthByOrder{}
	mi := &file_depth_by_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DepthByOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DepthByOrder) ProtoMessage() {}

func (x *DepthByOrder) ProtoReflect() protoreflect.Message {
	mi := &file_depth_by_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DepthByOrder.ProtoReflect.Descriptor instead.
func (*DepthByOrder) Descriptor() ([]byte, []int) {
	return file_depth_by_order_proto_rawDescGZIP(), []int{0}
}

func (x *DepthByOrder) GetTemplateId() int32 {
	if x != nil && x.TemplateId != nil {
		return *x.TemplateId
	}
	return 0
}

func (x *DepthByOrder) GetSymbol() string {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return ""
}

func (x *DepthByOrder) GetExchange() string {
	if x != nil && x.Exchange != nil {
		return *x.Exchange
	}
	return ""
}

func (x *DepthByOrder) GetSequenceNumber() uint64 {
	if x != nil && x.SequenceNumber != nil {
		return *x.SequenceNumber
	}
	return 0
}

func (x *DepthByOrder) GetUpdateType() []DepthByOrder_UpdateType {
	if x != nil {
		return x.UpdateType
	}
	return nil
}

func (x *DepthByOrder) GetTransactionType() []DepthByOrder_TransactionType {
	if x != nil {
		return x.TransactionType
	}
	return nil
}

func (x *DepthByOrder) GetDepthPrice() []float64 {
	if x != nil {
		return x.DepthPrice
	}
	return nil
}

func (x *DepthByOrder) GetPrevDepthPrice() []float64 {
	if x != nil {
		return x.PrevDepthPrice
	}
	return nil
}

func (x *DepthByOrder) GetPrevDepthPriceFlag() []bool {
	if x != nil {
		return x.PrevDepthPriceFlag
	}
	return nil
}

func (x *DepthByOrder) GetDepthSize() []int32 {
	if x != nil {
		return x.DepthSize
	}
	return nil
}

func (x *DepthByOrder) GetDepthOrderPriority() []uint64 {
	if x != nil {
		return x.DepthOrderPriority
	}
	return nil
}

func (x *DepthByOrder) GetExchangeOrderId() []string {
	if x != nil {
		return x.ExchangeOrderId
	}
	return nil
}

func (x *DepthByOrder) GetSsboe() int32 {
	if x != nil && x.Ssboe != nil {
		return *x.Ssboe
	}
	return 0
}

func (x *DepthByOrder) GetUsecs() int32 {
	if x != nil && x.Usecs != nil {
		return *x.Usecs
	}
	return 0
}

func (x *DepthByOrder) GetSourceSsboe() int32 {
	if x != nil && x.SourceSsboe != nil {
		return *x.SourceSsboe
	}
	return 0
}

func (x *DepthByOrder) GetSourceUsecs() int32 {
	if x != nil && x.SourceUsecs != nil {
		return *x.SourceUsecs
	}
	return 0
}

func (x *DepthByOrder) GetSourceNsecs() int32 {
	if x != nil && x.SourceNsecs != nil {
		return *x.SourceNsecs
	}
	return 0
}

func (x *DepthByOrder) GetJopSsboe() int32 {
	if x != nil && x.JopSsboe != nil {
		return *x.JopSsboe
	}
	return 0
}

func (x *DepthByOrder) GetJopNsecs() int32 {
	if x != nil && x.JopNsecs != nil {
		return *x.JopNsecs
	}
	return 0
}

var File_depth_by_order_proto protoreflect.FileDescriptor

const file_depth_by_order_proto_rawDesc = "" +
	"\n" +
	"\x14depth_by_order.proto\x12\x03rti\"\xde\x06\n" +
	"\fDepthByOrder\x12!\n" +
	"\vtemplate_id\x18\xe3\xb6\t \x02(\x05R\n" +
	"templateId\x12\x18\n" +
	"\x06symbol\x18\x94\xdc\x06 \x01(\tR\x06symbol\x12\x1c\n" +
	"\bexchange\x18\x95\xdc\x06 \x01(\tR\bexchange\x12)\n" +
	"\x0fsequence_number\x18\x82\xeb\x06 \x01(\x04R\x0esequenceNumber\x12?\n" +
	"\vupdate_type\x18\xa9\xdc\x06 \x03(\x0e2\x1c.rti.DepthByOrder.UpdateTypeR\n" +
	"updateType\x12N\n" +
	"\x10transaction_type\x18\x8c\xb0\t \x03(\x0e2!.rti.DepthByOrder.TransactionTypeR\x0ftransactionType\x12!\n" +
	"\vdepth_price\x18\xa5\xb6\t \x03(\x01R\n" +
	"depthPrice\x12*\n" +
	"\x10prev_depth_price\x18\x9a\xba\t \x03(\x01R\x0eprevDepthPrice\x123\n" +
	"\x15prev_depth_price_flag\x18\xb2\xba\t \x03(\bR\x12prevDepthPriceFlag\x12\x1f\n" +
	"\n" +
	"depth_size\x18\xa6\xb6\t \x03(\x05R\tdepthSize\x122\n" +
	"\x14depth_order_priority\x18\x8d\xb0\t \x03(\x04R\x12depthOrderPriority\x12,\n" +
	"\x11exchange_order_id\x18\xf6\x8d\t \x03(\tR\x0fexchangeOrderId\x12\x16\n" +
	"\x05ssboe\x18Ԕ\t \x01(\x05R\x05ssboe\x12\x16\n" +
	"\x05usecs\x18Ք\t \x01(\x05R\x05usecs\x12#\n" +
	"\fsource_ssboe\x18\x80\x97\t \x01(\x05R\vsourceSsboe\x12#\n" +
	"\fsource_usecs\x18\x81\x97\t \x01(\x05R\vsourceUsecs\x12#\n" +
	"\fsource_nsecs\x18\x84\x97\t \x01(\x05R\vsourceNsecs\x12\x1d\n" +
	"\tjop_ssboe\x18Ș\t \x01(\x05R\bjopSsboe\x12\x1d\n" +
	"\tjop_nsecs\x18̘\t \x01(\x05R\bjopNsecs\"$\n" +
	"\x0fTransactionType\x12\a\n" +
	"\x03BUY\x10\x01\x12\b\n" +
	"\x04SELL\x10\x02\"-\n" +
	"\n" +
	"UpdateType\x12\a\n" +
	"\x03NEW\x10\x01\x12\n" +
	"\n" +
	"\x06CHANGE\x10\x02\x12\n" +
	"\n" +
	"\x06DELETE\x10\x03B\x1eZ\x1cquant/extensions/rithmic/api"

var (
	file_depth_by_order_proto_rawDescOnce sync.Once
	file_depth_by_order_proto_rawDescData []byte
)

func file_depth_by_order_proto_rawDescGZIP() []byte {
	file_depth_by_order_proto_rawDescOnce.Do(func() {
		file_depth_by_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_depth_by_order_proto_rawDesc), len(file_depth_by_order_proto_rawDesc)))
	})
	return file_depth_by_order_proto_rawDescData
}

var file_depth_by_order_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_depth_by_order_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_depth_by_order_proto_goTypes = []any{
	(DepthByOrder_TransactionType)(0), // 0: rti.DepthByOrder.TransactionType
	(DepthByOrder_UpdateType)(0),      // 1: rti.DepthByOrder.UpdateType
	(*DepthByOrder)(nil),              // 2: rti.DepthByOrder
}
var file_depth_by_order_proto_depIdxs = []int32{
	1, // 0: rti.DepthByOrder.update_type:type_name -> rti.DepthByOrder.UpdateType
	0, // 1: rti.DepthByOrder.transaction_type:type_name -> rti.DepthByOrder.TransactionType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_depth_by_order_proto_init() }
func file_depth_by_order_proto_init() {
	if File_depth_by_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_depth_by_order_proto_rawDesc), len(file_depth_by_order_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_depth_by_order_proto_goTypes,
		DependencyIndexes: file_depth_by_order_proto_depIdxs,
		EnumInfos:         file_depth_by_order_proto_enumTypes,
		MessageInfos:      file_depth_by_order_proto_msgTypes,
	}.Build()
	File_depth_by_order_proto = out.File
	file_depth_by_order_proto_goTypes = nil
	file_depth_by_order_proto_depIdxs = nil
}
