// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: order_book.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// below enum is just for reference only, not used in this message
type OrderBook_PresenceBits int32

const (
	OrderBook_BID OrderBook_PresenceBits = 1
	OrderBook_ASK OrderBook_PresenceBits = 2
)

// Enum value maps for OrderBook_PresenceBits.
var (
	OrderBook_PresenceBits_name = map[int32]string{
		1: "BID",
		2: "ASK",
	}
	OrderBook_PresenceBits_value = map[string]int32{
		"BID": 1,
		"ASK": 2,
	}
)

func (x OrderBook_PresenceBits) Enum() *OrderBook_PresenceBits {
	p := new(OrderBook_PresenceBits)
	*p = x
	return p
}

func (x OrderBook_PresenceBits) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderBook_PresenceBits) Descriptor() protoreflect.EnumDescriptor {
	return file_order_book_proto_enumTypes[0].Descriptor()
}

func (OrderBook_PresenceBits) Type() protoreflect.EnumType {
	return &file_order_book_proto_enumTypes[0]
}

func (x OrderBook_PresenceBits) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *OrderBook_PresenceBits) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = OrderBook_PresenceBits(num)
	return nil
}

// Deprecated: Use OrderBook_PresenceBits.Descriptor instead.
func (OrderBook_PresenceBits) EnumDescriptor() ([]byte, []int) {
	return file_order_book_proto_rawDescGZIP(), []int{0, 0}
}

type OrderBook_UpdateType int32

const (
	OrderBook_CLEAR_ORDER_BOOK OrderBook_UpdateType = 1
	OrderBook_NO_BOOK          OrderBook_UpdateType = 2
	OrderBook_SNAPSHOT_IMAGE   OrderBook_UpdateType = 3
	OrderBook_BEGIN            OrderBook_UpdateType = 4
	OrderBook_MIDDLE           OrderBook_UpdateType = 5
	OrderBook_END              OrderBook_UpdateType = 6
	OrderBook_SOLO             OrderBook_UpdateType = 7
)

// Enum value maps for OrderBook_UpdateType.
var (
	OrderBook_UpdateType_name = map[int32]string{
		1: "CLEAR_ORDER_BOOK",
		2: "NO_BOOK",
		3: "SNAPSHOT_IMAGE",
		4: "BEGIN",
		5: "MIDDLE",
		6: "END",
		7: "SOLO",
	}
	OrderBook_UpdateType_value = map[string]int32{
		"CLEAR_ORDER_BOOK": 1,
		"NO_BOOK":          2,
		"SNAPSHOT_IMAGE":   3,
		"BEGIN":            4,
		"MIDDLE":           5,
		"END":              6,
		"SOLO":             7,
	}
)

func (x OrderBook_UpdateType) Enum() *OrderBook_UpdateType {
	p := new(OrderBook_UpdateType)
	*p = x
	return p
}

func (x OrderBook_UpdateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderBook_UpdateType) Descriptor() protoreflect.EnumDescriptor {
	return file_order_book_proto_enumTypes[1].Descriptor()
}

func (OrderBook_UpdateType) Type() protoreflect.EnumType {
	return &file_order_book_proto_enumTypes[1]
}

func (x OrderBook_UpdateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *OrderBook_UpdateType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = OrderBook_UpdateType(num)
	return nil
}

// Deprecated: Use OrderBook_UpdateType.Descriptor instead.
func (OrderBook_UpdateType) EnumDescriptor() ([]byte, []int) {
	return file_order_book_proto_rawDescGZIP(), []int{0, 1}
}

type OrderBook struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    *int32                 `protobuf:"varint,154467,req,name=template_id,json=templateId" json:"template_id,omitempty"`                               // PB_OFFSET + MNM_TEMPLATE_ID
	Symbol        *string                `protobuf:"bytes,110100,opt,name=symbol" json:"symbol,omitempty"`                                                          // PB_OFFSET + MNM_SYMBOL
	Exchange      *string                `protobuf:"bytes,110101,opt,name=exchange" json:"exchange,omitempty"`                                                      // PB_OFFSET + MNM_EXCHANGE
	PresenceBits  *uint32                `protobuf:"varint,149138,opt,name=presence_bits,json=presenceBits" json:"presence_bits,omitempty"`                         // PB_OFFSET + MNM_PRICING_INDICATOR
	UpdateType    *OrderBook_UpdateType  `protobuf:"varint,157608,opt,name=update_type,json=updateType,enum=rti.OrderBook_UpdateType" json:"update_type,omitempty"` // PB_OFFSET + MNM_MARKET_DEPTH_UPDATE_TYPE
	BidPrice      []float64              `protobuf:"fixed64,154282,rep,name=bid_price,json=bidPrice" json:"bid_price,omitempty"`                                    // PB_OFFSET + MNM_MARKET_DEPTH_BID_PRICE
	BidSize       []int32                `protobuf:"varint,154283,rep,name=bid_size,json=bidSize" json:"bid_size,omitempty"`                                        // PB_OFFSET + MNM_MARKET_DEPTH_BID_SIZE
	BidOrders     []int32                `protobuf:"varint,154401,rep,name=bid_orders,json=bidOrders" json:"bid_orders,omitempty"`                                  // PB_OFFSET + MNM_MARKET_DEPTH_BID_NO_OF_ORDERS
	ImplBidSize   []int32                `protobuf:"varint,154412,rep,name=impl_bid_size,json=implBidSize" json:"impl_bid_size,omitempty"`                          // PB_OFFSET + MNM_MARKET_DEPTH_IMPLICIT_BID_SIZE
	AskPrice      []float64              `protobuf:"fixed64,154284,rep,name=ask_price,json=askPrice" json:"ask_price,omitempty"`                                    // PB_OFFSET + MNM_MARKET_DEPTH_ASK_PRICE
	AskSize       []int32                `protobuf:"varint,154285,rep,name=ask_size,json=askSize" json:"ask_size,omitempty"`                                        // PB_OFFSET + MNM_MARKET_DEPTH_ASK_SIZE
	AskOrders     []int32                `protobuf:"varint,154402,rep,name=ask_orders,json=askOrders" json:"ask_orders,omitempty"`                                  // PB_OFFSET + MNM_MARKET_DEPTH_ASK_NO_OF_ORDERS
	ImplAskSize   []int32                `protobuf:"varint,154415,rep,name=impl_ask_size,json=implAskSize" json:"impl_ask_size,omitempty"`                          // PB_OFFSET + MNM_MARKET_DEPTH_IMPLICIT_ASK_SIZE
	Ssboe         *int32                 `protobuf:"varint,150100,opt,name=ssboe" json:"ssboe,omitempty"`                                                           // PB_OFFSET + MNM_SECONDS_SINCE_BOE
	Usecs         *int32                 `protobuf:"varint,150101,opt,name=usecs" json:"usecs,omitempty"`                                                           // PB_OFFSET + MNM_USECS
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderBook) Reset() {
	*x = OrderBook{}
	mi := &file_order_book_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderBook) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderBook) ProtoMessage() {}

func (x *OrderBook) ProtoReflect() protoreflect.Message {
	mi := &file_order_book_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBook.ProtoReflect.Descriptor instead.
func (*OrderBook) Descriptor() ([]byte, []int) {
	return file_order_book_proto_rawDescGZIP(), []int{0}
}

func (x *OrderBook) GetTemplateId() int32 {
	if x != nil && x.TemplateId != nil {
		return *x.TemplateId
	}
	return 0
}

func (x *OrderBook) GetSymbol() string {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return ""
}

func (x *OrderBook) GetExchange() string {
	if x != nil && x.Exchange != nil {
		return *x.Exchange
	}
	return ""
}

func (x *OrderBook) GetPresenceBits() uint32 {
	if x != nil && x.PresenceBits != nil {
		return *x.PresenceBits
	}
	return 0
}

func (x *OrderBook) GetUpdateType() OrderBook_UpdateType {
	if x != nil && x.UpdateType != nil {
		return *x.UpdateType
	}
	return OrderBook_CLEAR_ORDER_BOOK
}

func (x *OrderBook) GetBidPrice() []float64 {
	if x != nil {
		return x.BidPrice
	}
	return nil
}

func (x *OrderBook) GetBidSize() []int32 {
	if x != nil {
		return x.BidSize
	}
	return nil
}

func (x *OrderBook) GetBidOrders() []int32 {
	if x != nil {
		return x.BidOrders
	}
	return nil
}

func (x *OrderBook) GetImplBidSize() []int32 {
	if x != nil {
		return x.ImplBidSize
	}
	return nil
}

func (x *OrderBook) GetAskPrice() []float64 {
	if x != nil {
		return x.AskPrice
	}
	return nil
}

func (x *OrderBook) GetAskSize() []int32 {
	if x != nil {
		return x.AskSize
	}
	return nil
}

func (x *OrderBook) GetAskOrders() []int32 {
	if x != nil {
		return x.AskOrders
	}
	return nil
}

func (x *OrderBook) GetImplAskSize() []int32 {
	if x != nil {
		return x.ImplAskSize
	}
	return nil
}

func (x *OrderBook) GetSsboe() int32 {
	if x != nil && x.Ssboe != nil {
		return *x.Ssboe
	}
	return 0
}

func (x *OrderBook) GetUsecs() int32 {
	if x != nil && x.Usecs != nil {
		return *x.Usecs
	}
	return 0
}

var File_order_book_proto protoreflect.FileDescriptor

const file_order_book_proto_rawDesc = "" +
	"\n" +
	"\x10order_book.proto\x12\x03rti\"\x92\x05\n" +
	"\tOrderBook\x12!\n" +
	"\vtemplate_id\x18\xe3\xb6\t \x02(\x05R\n" +
	"templateId\x12\x18\n" +
	"\x06symbol\x18\x94\xdc\x06 \x01(\tR\x06symbol\x12\x1c\n" +
	"\bexchange\x18\x95\xdc\x06 \x01(\tR\bexchange\x12%\n" +
	"\rpresence_bits\x18\x92\x8d\t \x01(\rR\fpresenceBits\x12<\n" +
	"\vupdate_type\x18\xa8\xcf\t \x01(\x0e2\x19.rti.OrderBook.UpdateTypeR\n" +
	"updateType\x12\x1d\n" +
	"\tbid_price\x18\xaa\xb5\t \x03(\x01R\bbidPrice\x12\x1b\n" +
	"\bbid_size\x18\xab\xb5\t \x03(\x05R\abidSize\x12\x1f\n" +
	"\n" +
	"bid_orders\x18\xa1\xb6\t \x03(\x05R\tbidOrders\x12$\n" +
	"\rimpl_bid_size\x18\xac\xb6\t \x03(\x05R\vimplBidSize\x12\x1d\n" +
	"\task_price\x18\xac\xb5\t \x03(\x01R\baskPrice\x12\x1b\n" +
	"\bask_size\x18\xad\xb5\t \x03(\x05R\aaskSize\x12\x1f\n" +
	"\n" +
	"ask_orders\x18\xa2\xb6\t \x03(\x05R\taskOrders\x12$\n" +
	"\rimpl_ask_size\x18\xaf\xb6\t \x03(\x05R\vimplAskSize\x12\x16\n" +
	"\x05ssboe\x18Ԕ\t \x01(\x05R\x05ssboe\x12\x16\n" +
	"\x05usecs\x18Ք\t \x01(\x05R\x05usecs\" \n" +
	"\fPresenceBits\x12\a\n" +
	"\x03BID\x10\x01\x12\a\n" +
	"\x03ASK\x10\x02\"m\n" +
	"\n" +
	"UpdateType\x12\x14\n" +
	"\x10CLEAR_ORDER_BOOK\x10\x01\x12\v\n" +
	"\aNO_BOOK\x10\x02\x12\x12\n" +
	"\x0eSNAPSHOT_IMAGE\x10\x03\x12\t\n" +
	"\x05BEGIN\x10\x04\x12\n" +
	"\n" +
	"\x06MIDDLE\x10\x05\x12\a\n" +
	"\x03END\x10\x06\x12\b\n" +
	"\x04SOLO\x10\aB\x1eZ\x1cquant/extensions/rithmic/api"

var (
	file_order_book_proto_rawDescOnce sync.Once
	file_order_book_proto_rawDescData []byte
)

func file_order_book_proto_rawDescGZIP() []byte {
	file_order_book_proto_rawDescOnce.Do(func() {
		file_order_book_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_book_proto_rawDesc), len(file_order_book_proto_rawDesc)))
	})
	return file_order_book_proto_rawDescData
}

var file_order_book_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_order_book_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_order_book_proto_goTypes = []any{
	(OrderBook_PresenceBits)(0), // 0: rti.OrderBook.PresenceBits
	(OrderBook_UpdateType)(0),   // 1: rti.OrderBook.UpdateType
	(*OrderBook)(nil),           // 2: rti.OrderBook
}
var file_order_book_proto_depIdxs = []int32{
	1, // 0: rti.OrderBook.update_type:type_name -> rti.OrderBook.UpdateType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_order_book_proto_init() }
func file_order_book_proto_init() {
	if File_order_book_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_book_proto_rawDesc), len(file_order_book_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_order_book_proto_goTypes,
		DependencyIndexes: file_order_book_proto_depIdxs,
		EnumInfos:         file_order_book_proto_enumTypes,
		MessageInfos:      file_order_book_proto_msgTypes,
	}.Build()
	File_order_book_proto = out.File
	file_order_book_proto_goTypes = nil
	file_order_book_proto_depIdxs = nil
}
