// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: request_market_data_update_by_underlying.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestMarketDataUpdateByUnderlying_UpdateBits int32

const (
	RequestMarketDataUpdateByUnderlying_LAST_TRADE           RequestMarketDataUpdateByUnderlying_UpdateBits = 1
	RequestMarketDataUpdateByUnderlying_BBO                  RequestMarketDataUpdateByUnderlying_UpdateBits = 2
	RequestMarketDataUpdateByUnderlying_ORDER_BOOK           RequestMarketDataUpdateByUnderlying_UpdateBits = 4
	RequestMarketDataUpdateByUnderlying_OPEN                 RequestMarketDataUpdateByUnderlying_UpdateBits = 8
	RequestMarketDataUpdateByUnderlying_OPENING_INDICATOR    RequestMarketDataUpdateByUnderlying_UpdateBits = 16
	RequestMarketDataUpdateByUnderlying_HIGH_LOW             RequestMarketDataUpdateByUnderlying_UpdateBits = 32
	RequestMarketDataUpdateByUnderlying_HIGH_BID_LOW_ASK     RequestMarketDataUpdateByUnderlying_UpdateBits = 64
	RequestMarketDataUpdateByUnderlying_CLOSE                RequestMarketDataUpdateByUnderlying_UpdateBits = 128
	RequestMarketDataUpdateByUnderlying_CLOSING_INDICATOR    RequestMarketDataUpdateByUnderlying_UpdateBits = 256
	RequestMarketDataUpdateByUnderlying_SETTLEMENT           RequestMarketDataUpdateByUnderlying_UpdateBits = 512
	RequestMarketDataUpdateByUnderlying_MARKET_MODE          RequestMarketDataUpdateByUnderlying_UpdateBits = 1024
	RequestMarketDataUpdateByUnderlying_OPEN_INTEREST        RequestMarketDataUpdateByUnderlying_UpdateBits = 2048
	RequestMarketDataUpdateByUnderlying_MARGIN_RATE          RequestMarketDataUpdateByUnderlying_UpdateBits = 4096
	RequestMarketDataUpdateByUnderlying_HIGH_PRICE_LIMIT     RequestMarketDataUpdateByUnderlying_UpdateBits = 8192
	RequestMarketDataUpdateByUnderlying_LOW_PRICE_LIMIT      RequestMarketDataUpdateByUnderlying_UpdateBits = 16384
	RequestMarketDataUpdateByUnderlying_PROJECTED_SETTLEMENT RequestMarketDataUpdateByUnderlying_UpdateBits = 32768
)

// Enum value maps for RequestMarketDataUpdateByUnderlying_UpdateBits.
var (
	RequestMarketDataUpdateByUnderlying_UpdateBits_name = map[int32]string{
		1:     "LAST_TRADE",
		2:     "BBO",
		4:     "ORDER_BOOK",
		8:     "OPEN",
		16:    "OPENING_INDICATOR",
		32:    "HIGH_LOW",
		64:    "HIGH_BID_LOW_ASK",
		128:   "CLOSE",
		256:   "CLOSING_INDICATOR",
		512:   "SETTLEMENT",
		1024:  "MARKET_MODE",
		2048:  "OPEN_INTEREST",
		4096:  "MARGIN_RATE",
		8192:  "HIGH_PRICE_LIMIT",
		16384: "LOW_PRICE_LIMIT",
		32768: "PROJECTED_SETTLEMENT",
	}
	RequestMarketDataUpdateByUnderlying_UpdateBits_value = map[string]int32{
		"LAST_TRADE":           1,
		"BBO":                  2,
		"ORDER_BOOK":           4,
		"OPEN":                 8,
		"OPENING_INDICATOR":    16,
		"HIGH_LOW":             32,
		"HIGH_BID_LOW_ASK":     64,
		"CLOSE":                128,
		"CLOSING_INDICATOR":    256,
		"SETTLEMENT":           512,
		"MARKET_MODE":          1024,
		"OPEN_INTEREST":        2048,
		"MARGIN_RATE":          4096,
		"HIGH_PRICE_LIMIT":     8192,
		"LOW_PRICE_LIMIT":      16384,
		"PROJECTED_SETTLEMENT": 32768,
	}
)

func (x RequestMarketDataUpdateByUnderlying_UpdateBits) Enum() *RequestMarketDataUpdateByUnderlying_UpdateBits {
	p := new(RequestMarketDataUpdateByUnderlying_UpdateBits)
	*p = x
	return p
}

func (x RequestMarketDataUpdateByUnderlying_UpdateBits) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestMarketDataUpdateByUnderlying_UpdateBits) Descriptor() protoreflect.EnumDescriptor {
	return file_request_market_data_update_by_underlying_proto_enumTypes[0].Descriptor()
}

func (RequestMarketDataUpdateByUnderlying_UpdateBits) Type() protoreflect.EnumType {
	return &file_request_market_data_update_by_underlying_proto_enumTypes[0]
}

func (x RequestMarketDataUpdateByUnderlying_UpdateBits) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RequestMarketDataUpdateByUnderlying_UpdateBits) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RequestMarketDataUpdateByUnderlying_UpdateBits(num)
	return nil
}

// Deprecated: Use RequestMarketDataUpdateByUnderlying_UpdateBits.Descriptor instead.
func (RequestMarketDataUpdateByUnderlying_UpdateBits) EnumDescriptor() ([]byte, []int) {
	return file_request_market_data_update_by_underlying_proto_rawDescGZIP(), []int{0, 0}
}

type RequestMarketDataUpdateByUnderlying_Request int32

const (
	RequestMarketDataUpdateByUnderlying_SUBSCRIBE   RequestMarketDataUpdateByUnderlying_Request = 1
	RequestMarketDataUpdateByUnderlying_UNSUBSCRIBE RequestMarketDataUpdateByUnderlying_Request = 2
)

// Enum value maps for RequestMarketDataUpdateByUnderlying_Request.
var (
	RequestMarketDataUpdateByUnderlying_Request_name = map[int32]string{
		1: "SUBSCRIBE",
		2: "UNSUBSCRIBE",
	}
	RequestMarketDataUpdateByUnderlying_Request_value = map[string]int32{
		"SUBSCRIBE":   1,
		"UNSUBSCRIBE": 2,
	}
)

func (x RequestMarketDataUpdateByUnderlying_Request) Enum() *RequestMarketDataUpdateByUnderlying_Request {
	p := new(RequestMarketDataUpdateByUnderlying_Request)
	*p = x
	return p
}

func (x RequestMarketDataUpdateByUnderlying_Request) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestMarketDataUpdateByUnderlying_Request) Descriptor() protoreflect.EnumDescriptor {
	return file_request_market_data_update_by_underlying_proto_enumTypes[1].Descriptor()
}

func (RequestMarketDataUpdateByUnderlying_Request) Type() protoreflect.EnumType {
	return &file_request_market_data_update_by_underlying_proto_enumTypes[1]
}

func (x RequestMarketDataUpdateByUnderlying_Request) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RequestMarketDataUpdateByUnderlying_Request) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RequestMarketDataUpdateByUnderlying_Request(num)
	return nil
}

// Deprecated: Use RequestMarketDataUpdateByUnderlying_Request.Descriptor instead.
func (RequestMarketDataUpdateByUnderlying_Request) EnumDescriptor() ([]byte, []int) {
	return file_request_market_data_update_by_underlying_proto_rawDescGZIP(), []int{0, 1}
}

type RequestMarketDataUpdateByUnderlying struct {
	state            protoimpl.MessageState                       `protogen:"open.v1"`
	TemplateId       *int32                                       `protobuf:"varint,154467,req,name=template_id,json=templateId" json:"template_id,omitempty"`                              // PB_OFFSET + MNM_TEMPLATE_ID
	UserMsg          []string                                     `protobuf:"bytes,132760,rep,name=user_msg,json=userMsg" json:"user_msg,omitempty"`                                        // PB_OFFSET + MNM_USER_MSG
	UnderlyingSymbol *string                                      `protobuf:"bytes,101026,opt,name=underlying_symbol,json=underlyingSymbol" json:"underlying_symbol,omitempty"`             // PB_OFFSET + MNM_UNDERLYING_SYMBOL
	Exchange         *string                                      `protobuf:"bytes,110101,opt,name=exchange" json:"exchange,omitempty"`                                                     // PB_OFFSET + MNM_EXCHANGE
	ExpirationDate   *string                                      `protobuf:"bytes,100067,opt,name=expiration_date,json=expirationDate" json:"expiration_date,omitempty"`                   // PB_OFFSET + MNM_EXPIRATION_DATE
	Request          *RequestMarketDataUpdateByUnderlying_Request `protobuf:"varint,100000,opt,name=request,enum=rti.RequestMarketDataUpdateByUnderlying_Request" json:"request,omitempty"` // PB_OFFSET + MNM_REQUEST
	UpdateBits       *uint32                                      `protobuf:"varint,154211,opt,name=update_bits,json=updateBits" json:"update_bits,omitempty"`                              // PB_OFFSET + MNM_MESSAGE_ID
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RequestMarketDataUpdateByUnderlying) Reset() {
	*x = RequestMarketDataUpdateByUnderlying{}
	mi := &file_request_market_data_update_by_underlying_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMarketDataUpdateByUnderlying) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMarketDataUpdateByUnderlying) ProtoMessage() {}

func (x *RequestMarketDataUpdateByUnderlying) ProtoReflect() protoreflect.Message {
	mi := &file_request_market_data_update_by_underlying_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMarketDataUpdateByUnderlying.ProtoReflect.Descriptor instead.
func (*RequestMarketDataUpdateByUnderlying) Descriptor() ([]byte, []int) {
	return file_request_market_data_update_by_underlying_proto_rawDescGZIP(), []int{0}
}

func (x *RequestMarketDataUpdateByUnderlying) GetTemplateId() int32 {
	if x != nil && x.TemplateId != nil {
		return *x.TemplateId
	}
	return 0
}

func (x *RequestMarketDataUpdateByUnderlying) GetUserMsg() []string {
	if x != nil {
		return x.UserMsg
	}
	return nil
}

func (x *RequestMarketDataUpdateByUnderlying) GetUnderlyingSymbol() string {
	if x != nil && x.UnderlyingSymbol != nil {
		return *x.UnderlyingSymbol
	}
	return ""
}

func (x *RequestMarketDataUpdateByUnderlying) GetExchange() string {
	if x != nil && x.Exchange != nil {
		return *x.Exchange
	}
	return ""
}

func (x *RequestMarketDataUpdateByUnderlying) GetExpirationDate() string {
	if x != nil && x.ExpirationDate != nil {
		return *x.ExpirationDate
	}
	return ""
}

func (x *RequestMarketDataUpdateByUnderlying) GetRequest() RequestMarketDataUpdateByUnderlying_Request {
	if x != nil && x.Request != nil {
		return *x.Request
	}
	return RequestMarketDataUpdateByUnderlying_SUBSCRIBE
}

func (x *RequestMarketDataUpdateByUnderlying) GetUpdateBits() uint32 {
	if x != nil && x.UpdateBits != nil {
		return *x.UpdateBits
	}
	return 0
}

var File_request_market_data_update_by_underlying_proto protoreflect.FileDescriptor

const file_request_market_data_update_by_underlying_proto_rawDesc = "" +
	"\n" +
	".request_market_data_update_by_underlying.proto\x12\x03rti\"\xad\x05\n" +
	"#RequestMarketDataUpdateByUnderlying\x12!\n" +
	"\vtemplate_id\x18\xe3\xb6\t \x02(\x05R\n" +
	"templateId\x12\x1b\n" +
	"\buser_msg\x18\x98\x8d\b \x03(\tR\auserMsg\x12-\n" +
	"\x11underlying_symbol\x18\xa2\x95\x06 \x01(\tR\x10underlyingSymbol\x12\x1c\n" +
	"\bexchange\x18\x95\xdc\x06 \x01(\tR\bexchange\x12)\n" +
	"\x0fexpiration_date\x18\xe3\x8d\x06 \x01(\tR\x0eexpirationDate\x12L\n" +
	"\arequest\x18\xa0\x8d\x06 \x01(\x0e20.rti.RequestMarketDataUpdateByUnderlying.RequestR\arequest\x12!\n" +
	"\vupdate_bits\x18\xe3\xb4\t \x01(\rR\n" +
	"updateBits\"\xb1\x02\n" +
	"\n" +
	"UpdateBits\x12\x0e\n" +
	"\n" +
	"LAST_TRADE\x10\x01\x12\a\n" +
	"\x03BBO\x10\x02\x12\x0e\n" +
	"\n" +
	"ORDER_BOOK\x10\x04\x12\b\n" +
	"\x04OPEN\x10\b\x12\x15\n" +
	"\x11OPENING_INDICATOR\x10\x10\x12\f\n" +
	"\bHIGH_LOW\x10 \x12\x14\n" +
	"\x10HIGH_BID_LOW_ASK\x10@\x12\n" +
	"\n" +
	"\x05CLOSE\x10\x80\x01\x12\x16\n" +
	"\x11CLOSING_INDICATOR\x10\x80\x02\x12\x0f\n" +
	"\n" +
	"SETTLEMENT\x10\x80\x04\x12\x10\n" +
	"\vMARKET_MODE\x10\x80\b\x12\x12\n" +
	"\rOPEN_INTEREST\x10\x80\x10\x12\x10\n" +
	"\vMARGIN_RATE\x10\x80 \x12\x15\n" +
	"\x10HIGH_PRICE_LIMIT\x10\x80@\x12\x15\n" +
	"\x0fLOW_PRICE_LIMIT\x10\x80\x80\x01\x12\x1a\n" +
	"\x14PROJECTED_SETTLEMENT\x10\x80\x80\x02\")\n" +
	"\aRequest\x12\r\n" +
	"\tSUBSCRIBE\x10\x01\x12\x0f\n" +
	"\vUNSUBSCRIBE\x10\x02B\x1eZ\x1cquant/extensions/rithmic/api"

var (
	file_request_market_data_update_by_underlying_proto_rawDescOnce sync.Once
	file_request_market_data_update_by_underlying_proto_rawDescData []byte
)

func file_request_market_data_update_by_underlying_proto_rawDescGZIP() []byte {
	file_request_market_data_update_by_underlying_proto_rawDescOnce.Do(func() {
		file_request_market_data_update_by_underlying_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_request_market_data_update_by_underlying_proto_rawDesc), len(file_request_market_data_update_by_underlying_proto_rawDesc)))
	})
	return file_request_market_data_update_by_underlying_proto_rawDescData
}

var file_request_market_data_update_by_underlying_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_request_market_data_update_by_underlying_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_request_market_data_update_by_underlying_proto_goTypes = []any{
	(RequestMarketDataUpdateByUnderlying_UpdateBits)(0), // 0: rti.RequestMarketDataUpdateByUnderlying.UpdateBits
	(RequestMarketDataUpdateByUnderlying_Request)(0),    // 1: rti.RequestMarketDataUpdateByUnderlying.Request
	(*RequestMarketDataUpdateByUnderlying)(nil),         // 2: rti.RequestMarketDataUpdateByUnderlying
}
var file_request_market_data_update_by_underlying_proto_depIdxs = []int32{
	1, // 0: rti.RequestMarketDataUpdateByUnderlying.request:type_name -> rti.RequestMarketDataUpdateByUnderlying.Request
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_request_market_data_update_by_underlying_proto_init() }
func file_request_market_data_update_by_underlying_proto_init() {
	if File_request_market_data_update_by_underlying_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_request_market_data_update_by_underlying_proto_rawDesc), len(file_request_market_data_update_by_underlying_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_request_market_data_update_by_underlying_proto_goTypes,
		DependencyIndexes: file_request_market_data_update_by_underlying_proto_depIdxs,
		EnumInfos:         file_request_market_data_update_by_underlying_proto_enumTypes,
		MessageInfos:      file_request_market_data_update_by_underlying_proto_msgTypes,
	}.Build()
	File_request_market_data_update_by_underlying_proto = out.File
	file_request_market_data_update_by_underlying_proto_goTypes = nil
	file_request_market_data_update_by_underlying_proto_depIdxs = nil
}
