// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: request_time_bar_update.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestTimeBarUpdate_BarType int32

const (
	RequestTimeBarUpdate_SECOND_BAR RequestTimeBarUpdate_BarType = 1
	RequestTimeBarUpdate_MINUTE_BAR RequestTimeBarUpdate_BarType = 2
	RequestTimeBarUpdate_DAILY_BAR  RequestTimeBarUpdate_BarType = 3
	RequestTimeBarUpdate_WEEKLY_BAR RequestTimeBarUpdate_BarType = 4
)

// Enum value maps for RequestTimeBarUpdate_BarType.
var (
	RequestTimeBarUpdate_BarType_name = map[int32]string{
		1: "SECOND_BAR",
		2: "MINUTE_BAR",
		3: "DAILY_BAR",
		4: "WEEKLY_BAR",
	}
	RequestTimeBarUpdate_BarType_value = map[string]int32{
		"SECOND_BAR": 1,
		"MINUTE_BAR": 2,
		"DAILY_BAR":  3,
		"WEEKLY_BAR": 4,
	}
)

func (x RequestTimeBarUpdate_BarType) Enum() *RequestTimeBarUpdate_BarType {
	p := new(RequestTimeBarUpdate_BarType)
	*p = x
	return p
}

func (x RequestTimeBarUpdate_BarType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestTimeBarUpdate_BarType) Descriptor() protoreflect.EnumDescriptor {
	return file_request_time_bar_update_proto_enumTypes[0].Descriptor()
}

func (RequestTimeBarUpdate_BarType) Type() protoreflect.EnumType {
	return &file_request_time_bar_update_proto_enumTypes[0]
}

func (x RequestTimeBarUpdate_BarType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RequestTimeBarUpdate_BarType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RequestTimeBarUpdate_BarType(num)
	return nil
}

// Deprecated: Use RequestTimeBarUpdate_BarType.Descriptor instead.
func (RequestTimeBarUpdate_BarType) EnumDescriptor() ([]byte, []int) {
	return file_request_time_bar_update_proto_rawDescGZIP(), []int{0, 0}
}

type RequestTimeBarUpdate_Request int32

const (
	RequestTimeBarUpdate_SUBSCRIBE   RequestTimeBarUpdate_Request = 1
	RequestTimeBarUpdate_UNSUBSCRIBE RequestTimeBarUpdate_Request = 2
)

// Enum value maps for RequestTimeBarUpdate_Request.
var (
	RequestTimeBarUpdate_Request_name = map[int32]string{
		1: "SUBSCRIBE",
		2: "UNSUBSCRIBE",
	}
	RequestTimeBarUpdate_Request_value = map[string]int32{
		"SUBSCRIBE":   1,
		"UNSUBSCRIBE": 2,
	}
)

func (x RequestTimeBarUpdate_Request) Enum() *RequestTimeBarUpdate_Request {
	p := new(RequestTimeBarUpdate_Request)
	*p = x
	return p
}

func (x RequestTimeBarUpdate_Request) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestTimeBarUpdate_Request) Descriptor() protoreflect.EnumDescriptor {
	return file_request_time_bar_update_proto_enumTypes[1].Descriptor()
}

func (RequestTimeBarUpdate_Request) Type() protoreflect.EnumType {
	return &file_request_time_bar_update_proto_enumTypes[1]
}

func (x RequestTimeBarUpdate_Request) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RequestTimeBarUpdate_Request) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RequestTimeBarUpdate_Request(num)
	return nil
}

// Deprecated: Use RequestTimeBarUpdate_Request.Descriptor instead.
func (RequestTimeBarUpdate_Request) EnumDescriptor() ([]byte, []int) {
	return file_request_time_bar_update_proto_rawDescGZIP(), []int{0, 1}
}

type RequestTimeBarUpdate struct {
	state         protoimpl.MessageState        `protogen:"open.v1"`
	TemplateId    *int32                        `protobuf:"varint,154467,req,name=template_id,json=templateId" json:"template_id,omitempty"`                              // PB_OFFSET + MNM_TEMPLATE_ID
	UserMsg       []string                      `protobuf:"bytes,132760,rep,name=user_msg,json=userMsg" json:"user_msg,omitempty"`                                        // PB_OFFSET + MNM_USER_MSG
	Symbol        *string                       `protobuf:"bytes,110100,opt,name=symbol" json:"symbol,omitempty"`                                                         // PB_OFFSET + MNM_SYMBOL
	Exchange      *string                       `protobuf:"bytes,110101,opt,name=exchange" json:"exchange,omitempty"`                                                     // PB_OFFSET + MNM_EXCHANGE
	Request       *RequestTimeBarUpdate_Request `protobuf:"varint,100000,opt,name=request,enum=rti.RequestTimeBarUpdate_Request" json:"request,omitempty"`                // PB_OFFSET + MNM_REQUEST
	BarType       *RequestTimeBarUpdate_BarType `protobuf:"varint,119200,opt,name=bar_type,json=barType,enum=rti.RequestTimeBarUpdate_BarType" json:"bar_type,omitempty"` // PB_OFFSET + MNM_DATA_BAR_TYPE
	BarTypePeriod *int32                        `protobuf:"varint,119112,opt,name=bar_type_period,json=barTypePeriod" json:"bar_type_period,omitempty"`                   // PB_OFFSET + MNM_TIME_BAR_PERIOD
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestTimeBarUpdate) Reset() {
	*x = RequestTimeBarUpdate{}
	mi := &file_request_time_bar_update_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestTimeBarUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestTimeBarUpdate) ProtoMessage() {}

func (x *RequestTimeBarUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_request_time_bar_update_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestTimeBarUpdate.ProtoReflect.Descriptor instead.
func (*RequestTimeBarUpdate) Descriptor() ([]byte, []int) {
	return file_request_time_bar_update_proto_rawDescGZIP(), []int{0}
}

func (x *RequestTimeBarUpdate) GetTemplateId() int32 {
	if x != nil && x.TemplateId != nil {
		return *x.TemplateId
	}
	return 0
}

func (x *RequestTimeBarUpdate) GetUserMsg() []string {
	if x != nil {
		return x.UserMsg
	}
	return nil
}

func (x *RequestTimeBarUpdate) GetSymbol() string {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return ""
}

func (x *RequestTimeBarUpdate) GetExchange() string {
	if x != nil && x.Exchange != nil {
		return *x.Exchange
	}
	return ""
}

func (x *RequestTimeBarUpdate) GetRequest() RequestTimeBarUpdate_Request {
	if x != nil && x.Request != nil {
		return *x.Request
	}
	return RequestTimeBarUpdate_SUBSCRIBE
}

func (x *RequestTimeBarUpdate) GetBarType() RequestTimeBarUpdate_BarType {
	if x != nil && x.BarType != nil {
		return *x.BarType
	}
	return RequestTimeBarUpdate_SECOND_BAR
}

func (x *RequestTimeBarUpdate) GetBarTypePeriod() int32 {
	if x != nil && x.BarTypePeriod != nil {
		return *x.BarTypePeriod
	}
	return 0
}

var File_request_time_bar_update_proto protoreflect.FileDescriptor

const file_request_time_bar_update_proto_rawDesc = "" +
	"\n" +
	"\x1drequest_time_bar_update.proto\x12\x03rti\"\xac\x03\n" +
	"\x14RequestTimeBarUpdate\x12!\n" +
	"\vtemplate_id\x18\xe3\xb6\t \x02(\x05R\n" +
	"templateId\x12\x1b\n" +
	"\buser_msg\x18\x98\x8d\b \x03(\tR\auserMsg\x12\x18\n" +
	"\x06symbol\x18\x94\xdc\x06 \x01(\tR\x06symbol\x12\x1c\n" +
	"\bexchange\x18\x95\xdc\x06 \x01(\tR\bexchange\x12=\n" +
	"\arequest\x18\xa0\x8d\x06 \x01(\x0e2!.rti.RequestTimeBarUpdate.RequestR\arequest\x12>\n" +
	"\bbar_type\x18\xa0\xa3\a \x01(\x0e2!.rti.RequestTimeBarUpdate.BarTypeR\abarType\x12(\n" +
	"\x0fbar_type_period\x18Ȣ\a \x01(\x05R\rbarTypePeriod\"H\n" +
	"\aBarType\x12\x0e\n" +
	"\n" +
	"SECOND_BAR\x10\x01\x12\x0e\n" +
	"\n" +
	"MINUTE_BAR\x10\x02\x12\r\n" +
	"\tDAILY_BAR\x10\x03\x12\x0e\n" +
	"\n" +
	"WEEKLY_BAR\x10\x04\")\n" +
	"\aRequest\x12\r\n" +
	"\tSUBSCRIBE\x10\x01\x12\x0f\n" +
	"\vUNSUBSCRIBE\x10\x02B\x1eZ\x1cquant/extensions/rithmic/api"

var (
	file_request_time_bar_update_proto_rawDescOnce sync.Once
	file_request_time_bar_update_proto_rawDescData []byte
)

func file_request_time_bar_update_proto_rawDescGZIP() []byte {
	file_request_time_bar_update_proto_rawDescOnce.Do(func() {
		file_request_time_bar_update_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_request_time_bar_update_proto_rawDesc), len(file_request_time_bar_update_proto_rawDesc)))
	})
	return file_request_time_bar_update_proto_rawDescData
}

var file_request_time_bar_update_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_request_time_bar_update_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_request_time_bar_update_proto_goTypes = []any{
	(RequestTimeBarUpdate_BarType)(0), // 0: rti.RequestTimeBarUpdate.BarType
	(RequestTimeBarUpdate_Request)(0), // 1: rti.RequestTimeBarUpdate.Request
	(*RequestTimeBarUpdate)(nil),      // 2: rti.RequestTimeBarUpdate
}
var file_request_time_bar_update_proto_depIdxs = []int32{
	1, // 0: rti.RequestTimeBarUpdate.request:type_name -> rti.RequestTimeBarUpdate.Request
	0, // 1: rti.RequestTimeBarUpdate.bar_type:type_name -> rti.RequestTimeBarUpdate.BarType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_request_time_bar_update_proto_init() }
func file_request_time_bar_update_proto_init() {
	if File_request_time_bar_update_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_request_time_bar_update_proto_rawDesc), len(file_request_time_bar_update_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_request_time_bar_update_proto_goTypes,
		DependencyIndexes: file_request_time_bar_update_proto_depIdxs,
		EnumInfos:         file_request_time_bar_update_proto_enumTypes,
		MessageInfos:      file_request_time_bar_update_proto_msgTypes,
	}.Build()
	File_request_time_bar_update_proto = out.File
	file_request_time_bar_update_proto_goTypes = nil
	file_request_time_bar_update_proto_depIdxs = nil
}
