// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: request_pnl_position_updates.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestPnLPositionUpdates_Request int32

const (
	RequestPnLPositionUpdates_SUBSCRIBE   RequestPnLPositionUpdates_Request = 1
	RequestPnLPositionUpdates_UNSUBSCRIBE RequestPnLPositionUpdates_Request = 2
)

// Enum value maps for RequestPnLPositionUpdates_Request.
var (
	RequestPnLPositionUpdates_Request_name = map[int32]string{
		1: "SUBSCRIBE",
		2: "UNSUBSCRIBE",
	}
	RequestPnLPositionUpdates_Request_value = map[string]int32{
		"SUBSCRIBE":   1,
		"UNSUBSCRIBE": 2,
	}
)

func (x RequestPnLPositionUpdates_Request) Enum() *RequestPnLPositionUpdates_Request {
	p := new(RequestPnLPositionUpdates_Request)
	*p = x
	return p
}

func (x RequestPnLPositionUpdates_Request) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestPnLPositionUpdates_Request) Descriptor() protoreflect.EnumDescriptor {
	return file_request_pnl_position_updates_proto_enumTypes[0].Descriptor()
}

func (RequestPnLPositionUpdates_Request) Type() protoreflect.EnumType {
	return &file_request_pnl_position_updates_proto_enumTypes[0]
}

func (x RequestPnLPositionUpdates_Request) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RequestPnLPositionUpdates_Request) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RequestPnLPositionUpdates_Request(num)
	return nil
}

// Deprecated: Use RequestPnLPositionUpdates_Request.Descriptor instead.
func (RequestPnLPositionUpdates_Request) EnumDescriptor() ([]byte, []int) {
	return file_request_pnl_position_updates_proto_rawDescGZIP(), []int{0, 0}
}

type RequestPnLPositionUpdates struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	TemplateId    *int32                             `protobuf:"varint,154467,req,name=template_id,json=templateId" json:"template_id,omitempty"`                    // PB_OFFSET + MNM_TEMPLATE_ID
	UserMsg       []string                           `protobuf:"bytes,132760,rep,name=user_msg,json=userMsg" json:"user_msg,omitempty"`                              // PB_OFFSET + MNM_USER_MSG
	Request       *RequestPnLPositionUpdates_Request `protobuf:"varint,100000,opt,name=request,enum=rti.RequestPnLPositionUpdates_Request" json:"request,omitempty"` // PB_OFFSET + MNM_REQUEST
	FcmId         *string                            `protobuf:"bytes,154013,opt,name=fcm_id,json=fcmId" json:"fcm_id,omitempty"`                                    // PB_OFFSET + MNM_FCM_ID
	IbId          *string                            `protobuf:"bytes,154014,opt,name=ib_id,json=ibId" json:"ib_id,omitempty"`                                       // PB_OFFSET + MNM_IB_ID
	AccountId     *string                            `protobuf:"bytes,154008,opt,name=account_id,json=accountId" json:"account_id,omitempty"`                        // PB_OFFSET + MNM_ACCOUNT_ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestPnLPositionUpdates) Reset() {
	*x = RequestPnLPositionUpdates{}
	mi := &file_request_pnl_position_updates_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestPnLPositionUpdates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPnLPositionUpdates) ProtoMessage() {}

func (x *RequestPnLPositionUpdates) ProtoReflect() protoreflect.Message {
	mi := &file_request_pnl_position_updates_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPnLPositionUpdates.ProtoReflect.Descriptor instead.
func (*RequestPnLPositionUpdates) Descriptor() ([]byte, []int) {
	return file_request_pnl_position_updates_proto_rawDescGZIP(), []int{0}
}

func (x *RequestPnLPositionUpdates) GetTemplateId() int32 {
	if x != nil && x.TemplateId != nil {
		return *x.TemplateId
	}
	return 0
}

func (x *RequestPnLPositionUpdates) GetUserMsg() []string {
	if x != nil {
		return x.UserMsg
	}
	return nil
}

func (x *RequestPnLPositionUpdates) GetRequest() RequestPnLPositionUpdates_Request {
	if x != nil && x.Request != nil {
		return *x.Request
	}
	return RequestPnLPositionUpdates_SUBSCRIBE
}

func (x *RequestPnLPositionUpdates) GetFcmId() string {
	if x != nil && x.FcmId != nil {
		return *x.FcmId
	}
	return ""
}

func (x *RequestPnLPositionUpdates) GetIbId() string {
	if x != nil && x.IbId != nil {
		return *x.IbId
	}
	return ""
}

func (x *RequestPnLPositionUpdates) GetAccountId() string {
	if x != nil && x.AccountId != nil {
		return *x.AccountId
	}
	return ""
}

var File_request_pnl_position_updates_proto protoreflect.FileDescriptor

const file_request_pnl_position_updates_proto_rawDesc = "" +
	"\n" +
	"\"request_pnl_position_updates.proto\x12\x03rti\"\x9b\x02\n" +
	"\x19RequestPnLPositionUpdates\x12!\n" +
	"\vtemplate_id\x18\xe3\xb6\t \x02(\x05R\n" +
	"templateId\x12\x1b\n" +
	"\buser_msg\x18\x98\x8d\b \x03(\tR\auserMsg\x12B\n" +
	"\arequest\x18\xa0\x8d\x06 \x01(\x0e2&.rti.RequestPnLPositionUpdates.RequestR\arequest\x12\x17\n" +
	"\x06fcm_id\x18\x9d\xb3\t \x01(\tR\x05fcmId\x12\x15\n" +
	"\x05ib_id\x18\x9e\xb3\t \x01(\tR\x04ibId\x12\x1f\n" +
	"\n" +
	"account_id\x18\x98\xb3\t \x01(\tR\taccountId\")\n" +
	"\aRequest\x12\r\n" +
	"\tSUBSCRIBE\x10\x01\x12\x0f\n" +
	"\vUNSUBSCRIBE\x10\x02B\x1eZ\x1cquant/extensions/rithmic/api"

var (
	file_request_pnl_position_updates_proto_rawDescOnce sync.Once
	file_request_pnl_position_updates_proto_rawDescData []byte
)

func file_request_pnl_position_updates_proto_rawDescGZIP() []byte {
	file_request_pnl_position_updates_proto_rawDescOnce.Do(func() {
		file_request_pnl_position_updates_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_request_pnl_position_updates_proto_rawDesc), len(file_request_pnl_position_updates_proto_rawDesc)))
	})
	return file_request_pnl_position_updates_proto_rawDescData
}

var file_request_pnl_position_updates_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_request_pnl_position_updates_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_request_pnl_position_updates_proto_goTypes = []any{
	(RequestPnLPositionUpdates_Request)(0), // 0: rti.RequestPnLPositionUpdates.Request
	(*RequestPnLPositionUpdates)(nil),      // 1: rti.RequestPnLPositionUpdates
}
var file_request_pnl_position_updates_proto_depIdxs = []int32{
	0, // 0: rti.RequestPnLPositionUpdates.request:type_name -> rti.RequestPnLPositionUpdates.Request
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_request_pnl_position_updates_proto_init() }
func file_request_pnl_position_updates_proto_init() {
	if File_request_pnl_position_updates_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_request_pnl_position_updates_proto_rawDesc), len(file_request_pnl_position_updates_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_request_pnl_position_updates_proto_goTypes,
		DependencyIndexes: file_request_pnl_position_updates_proto_depIdxs,
		EnumInfos:         file_request_pnl_position_updates_proto_enumTypes,
		MessageInfos:      file_request_pnl_position_updates_proto_msgTypes,
	}.Build()
	File_request_pnl_position_updates_proto = out.File
	file_request_pnl_position_updates_proto_goTypes = nil
	file_request_pnl_position_updates_proto_depIdxs = nil
}
