// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: request_modify_order.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestModifyOrder_PriceType int32

const (
	RequestModifyOrder_LIMIT             RequestModifyOrder_PriceType = 1
	RequestModifyOrder_MARKET            RequestModifyOrder_PriceType = 2
	RequestModifyOrder_STOP_LIMIT        RequestModifyOrder_PriceType = 3
	RequestModifyOrder_STOP_MARKET       RequestModifyOrder_PriceType = 4
	RequestModifyOrder_MARKET_IF_TOUCHED RequestModifyOrder_PriceType = 5
	RequestModifyOrder_LIMIT_IF_TOUCHED  RequestModifyOrder_PriceType = 6
)

// Enum value maps for RequestModifyOrder_PriceType.
var (
	RequestModifyOrder_PriceType_name = map[int32]string{
		1: "LIMIT",
		2: "MARKET",
		3: "STOP_LIMIT",
		4: "STOP_MARKET",
		5: "MARKET_IF_TOUCHED",
		6: "LIMIT_IF_TOUCHED",
	}
	RequestModifyOrder_PriceType_value = map[string]int32{
		"LIMIT":             1,
		"MARKET":            2,
		"STOP_LIMIT":        3,
		"STOP_MARKET":       4,
		"MARKET_IF_TOUCHED": 5,
		"LIMIT_IF_TOUCHED":  6,
	}
)

func (x RequestModifyOrder_PriceType) Enum() *RequestModifyOrder_PriceType {
	p := new(RequestModifyOrder_PriceType)
	*p = x
	return p
}

func (x RequestModifyOrder_PriceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestModifyOrder_PriceType) Descriptor() protoreflect.EnumDescriptor {
	return file_request_modify_order_proto_enumTypes[0].Descriptor()
}

func (RequestModifyOrder_PriceType) Type() protoreflect.EnumType {
	return &file_request_modify_order_proto_enumTypes[0]
}

func (x RequestModifyOrder_PriceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RequestModifyOrder_PriceType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RequestModifyOrder_PriceType(num)
	return nil
}

// Deprecated: Use RequestModifyOrder_PriceType.Descriptor instead.
func (RequestModifyOrder_PriceType) EnumDescriptor() ([]byte, []int) {
	return file_request_modify_order_proto_rawDescGZIP(), []int{0, 0}
}

type RequestModifyOrder_PriceField int32

const (
	RequestModifyOrder_BID_PRICE   RequestModifyOrder_PriceField = 1
	RequestModifyOrder_OFFER_PRICE RequestModifyOrder_PriceField = 2
	RequestModifyOrder_TRADE_PRICE RequestModifyOrder_PriceField = 3
	RequestModifyOrder_LEAN_PRICE  RequestModifyOrder_PriceField = 4
)

// Enum value maps for RequestModifyOrder_PriceField.
var (
	RequestModifyOrder_PriceField_name = map[int32]string{
		1: "BID_PRICE",
		2: "OFFER_PRICE",
		3: "TRADE_PRICE",
		4: "LEAN_PRICE",
	}
	RequestModifyOrder_PriceField_value = map[string]int32{
		"BID_PRICE":   1,
		"OFFER_PRICE": 2,
		"TRADE_PRICE": 3,
		"LEAN_PRICE":  4,
	}
)

func (x RequestModifyOrder_PriceField) Enum() *RequestModifyOrder_PriceField {
	p := new(RequestModifyOrder_PriceField)
	*p = x
	return p
}

func (x RequestModifyOrder_PriceField) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestModifyOrder_PriceField) Descriptor() protoreflect.EnumDescriptor {
	return file_request_modify_order_proto_enumTypes[1].Descriptor()
}

func (RequestModifyOrder_PriceField) Type() protoreflect.EnumType {
	return &file_request_modify_order_proto_enumTypes[1]
}

func (x RequestModifyOrder_PriceField) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RequestModifyOrder_PriceField) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RequestModifyOrder_PriceField(num)
	return nil
}

// Deprecated: Use RequestModifyOrder_PriceField.Descriptor instead.
func (RequestModifyOrder_PriceField) EnumDescriptor() ([]byte, []int) {
	return file_request_modify_order_proto_rawDescGZIP(), []int{0, 1}
}

type RequestModifyOrder_Condition int32

const (
	RequestModifyOrder_EQUAL_TO              RequestModifyOrder_Condition = 1
	RequestModifyOrder_NOT_EQUAL_TO          RequestModifyOrder_Condition = 2
	RequestModifyOrder_GREATER_THAN          RequestModifyOrder_Condition = 3
	RequestModifyOrder_GREATER_THAN_EQUAL_TO RequestModifyOrder_Condition = 4
	RequestModifyOrder_LESSER_THAN           RequestModifyOrder_Condition = 5
	RequestModifyOrder_LESSER_THAN_EQUAL_TO  RequestModifyOrder_Condition = 6
)

// Enum value maps for RequestModifyOrder_Condition.
var (
	RequestModifyOrder_Condition_name = map[int32]string{
		1: "EQUAL_TO",
		2: "NOT_EQUAL_TO",
		3: "GREATER_THAN",
		4: "GREATER_THAN_EQUAL_TO",
		5: "LESSER_THAN",
		6: "LESSER_THAN_EQUAL_TO",
	}
	RequestModifyOrder_Condition_value = map[string]int32{
		"EQUAL_TO":              1,
		"NOT_EQUAL_TO":          2,
		"GREATER_THAN":          3,
		"GREATER_THAN_EQUAL_TO": 4,
		"LESSER_THAN":           5,
		"LESSER_THAN_EQUAL_TO":  6,
	}
)

func (x RequestModifyOrder_Condition) Enum() *RequestModifyOrder_Condition {
	p := new(RequestModifyOrder_Condition)
	*p = x
	return p
}

func (x RequestModifyOrder_Condition) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestModifyOrder_Condition) Descriptor() protoreflect.EnumDescriptor {
	return file_request_modify_order_proto_enumTypes[2].Descriptor()
}

func (RequestModifyOrder_Condition) Type() protoreflect.EnumType {
	return &file_request_modify_order_proto_enumTypes[2]
}

func (x RequestModifyOrder_Condition) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RequestModifyOrder_Condition) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RequestModifyOrder_Condition(num)
	return nil
}

// Deprecated: Use RequestModifyOrder_Condition.Descriptor instead.
func (RequestModifyOrder_Condition) EnumDescriptor() ([]byte, []int) {
	return file_request_modify_order_proto_rawDescGZIP(), []int{0, 2}
}

type RequestModifyOrder_OrderPlacement int32

const (
	RequestModifyOrder_MANUAL RequestModifyOrder_OrderPlacement = 1
	RequestModifyOrder_AUTO   RequestModifyOrder_OrderPlacement = 2
)

// Enum value maps for RequestModifyOrder_OrderPlacement.
var (
	RequestModifyOrder_OrderPlacement_name = map[int32]string{
		1: "MANUAL",
		2: "AUTO",
	}
	RequestModifyOrder_OrderPlacement_value = map[string]int32{
		"MANUAL": 1,
		"AUTO":   2,
	}
)

func (x RequestModifyOrder_OrderPlacement) Enum() *RequestModifyOrder_OrderPlacement {
	p := new(RequestModifyOrder_OrderPlacement)
	*p = x
	return p
}

func (x RequestModifyOrder_OrderPlacement) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestModifyOrder_OrderPlacement) Descriptor() protoreflect.EnumDescriptor {
	return file_request_modify_order_proto_enumTypes[3].Descriptor()
}

func (RequestModifyOrder_OrderPlacement) Type() protoreflect.EnumType {
	return &file_request_modify_order_proto_enumTypes[3]
}

func (x RequestModifyOrder_OrderPlacement) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RequestModifyOrder_OrderPlacement) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RequestModifyOrder_OrderPlacement(num)
	return nil
}

// Deprecated: Use RequestModifyOrder_OrderPlacement.Descriptor instead.
func (RequestModifyOrder_OrderPlacement) EnumDescriptor() ([]byte, []int) {
	return file_request_modify_order_proto_rawDescGZIP(), []int{0, 3}
}

type RequestModifyOrder struct {
	state               protoimpl.MessageState             `protogen:"open.v1"`
	TemplateId          *int32                             `protobuf:"varint,154467,req,name=template_id,json=templateId" json:"template_id,omitempty"`
	UserMsg             []string                           `protobuf:"bytes,132760,rep,name=user_msg,json=userMsg" json:"user_msg,omitempty"`
	WindowName          *string                            `protobuf:"bytes,154629,opt,name=window_name,json=windowName" json:"window_name,omitempty"`
	FcmId               *string                            `protobuf:"bytes,154013,opt,name=fcm_id,json=fcmId" json:"fcm_id,omitempty"`
	IbId                *string                            `protobuf:"bytes,154014,opt,name=ib_id,json=ibId" json:"ib_id,omitempty"`
	AccountId           *string                            `protobuf:"bytes,154008,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
	BasketId            *string                            `protobuf:"bytes,110300,opt,name=basket_id,json=basketId" json:"basket_id,omitempty"`
	Symbol              *string                            `protobuf:"bytes,110100,opt,name=symbol" json:"symbol,omitempty"`
	Exchange            *string                            `protobuf:"bytes,110101,opt,name=exchange" json:"exchange,omitempty"`
	Quantity            *int32                             `protobuf:"varint,112004,opt,name=quantity" json:"quantity,omitempty"`
	Price               *float64                           `protobuf:"fixed64,110306,opt,name=price" json:"price,omitempty"`
	TriggerPrice        *float64                           `protobuf:"fixed64,149247,opt,name=trigger_price,json=triggerPrice" json:"trigger_price,omitempty"`
	PriceType           *RequestModifyOrder_PriceType      `protobuf:"varint,112008,opt,name=price_type,json=priceType,enum=rti.RequestModifyOrder_PriceType" json:"price_type,omitempty"`
	ManualOrAuto        *RequestModifyOrder_OrderPlacement `protobuf:"varint,154710,opt,name=manual_or_auto,json=manualOrAuto,enum=rti.RequestModifyOrder_OrderPlacement" json:"manual_or_auto,omitempty"`
	TrailingStop        *bool                              `protobuf:"varint,157063,opt,name=trailing_stop,json=trailingStop" json:"trailing_stop,omitempty"`
	TrailByTicks        *int32                             `protobuf:"varint,157064,opt,name=trail_by_ticks,json=trailByTicks" json:"trail_by_ticks,omitempty"`
	IfTouchedSymbol     *string                            `protobuf:"bytes,154451,opt,name=if_touched_symbol,json=ifTouchedSymbol" json:"if_touched_symbol,omitempty"`
	IfTouchedExchange   *string                            `protobuf:"bytes,154452,opt,name=if_touched_exchange,json=ifTouchedExchange" json:"if_touched_exchange,omitempty"`
	IfTouchedCondition  *RequestModifyOrder_Condition      `protobuf:"varint,154453,opt,name=if_touched_condition,json=ifTouchedCondition,enum=rti.RequestModifyOrder_Condition" json:"if_touched_condition,omitempty"`
	IfTouchedPriceField *RequestModifyOrder_PriceField     `protobuf:"varint,154454,opt,name=if_touched_price_field,json=ifTouchedPriceField,enum=rti.RequestModifyOrder_PriceField" json:"if_touched_price_field,omitempty"`
	IfTouchedPrice      *float64                           `protobuf:"fixed64,153632,opt,name=if_touched_price,json=ifTouchedPrice" json:"if_touched_price,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RequestModifyOrder) Reset() {
	*x = RequestModifyOrder{}
	mi := &file_request_modify_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestModifyOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestModifyOrder) ProtoMessage() {}

func (x *RequestModifyOrder) ProtoReflect() protoreflect.Message {
	mi := &file_request_modify_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestModifyOrder.ProtoReflect.Descriptor instead.
func (*RequestModifyOrder) Descriptor() ([]byte, []int) {
	return file_request_modify_order_proto_rawDescGZIP(), []int{0}
}

func (x *RequestModifyOrder) GetTemplateId() int32 {
	if x != nil && x.TemplateId != nil {
		return *x.TemplateId
	}
	return 0
}

func (x *RequestModifyOrder) GetUserMsg() []string {
	if x != nil {
		return x.UserMsg
	}
	return nil
}

func (x *RequestModifyOrder) GetWindowName() string {
	if x != nil && x.WindowName != nil {
		return *x.WindowName
	}
	return ""
}

func (x *RequestModifyOrder) GetFcmId() string {
	if x != nil && x.FcmId != nil {
		return *x.FcmId
	}
	return ""
}

func (x *RequestModifyOrder) GetIbId() string {
	if x != nil && x.IbId != nil {
		return *x.IbId
	}
	return ""
}

func (x *RequestModifyOrder) GetAccountId() string {
	if x != nil && x.AccountId != nil {
		return *x.AccountId
	}
	return ""
}

func (x *RequestModifyOrder) GetBasketId() string {
	if x != nil && x.BasketId != nil {
		return *x.BasketId
	}
	return ""
}

func (x *RequestModifyOrder) GetSymbol() string {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return ""
}

func (x *RequestModifyOrder) GetExchange() string {
	if x != nil && x.Exchange != nil {
		return *x.Exchange
	}
	return ""
}

func (x *RequestModifyOrder) GetQuantity() int32 {
	if x != nil && x.Quantity != nil {
		return *x.Quantity
	}
	return 0
}

func (x *RequestModifyOrder) GetPrice() float64 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

func (x *RequestModifyOrder) GetTriggerPrice() float64 {
	if x != nil && x.TriggerPrice != nil {
		return *x.TriggerPrice
	}
	return 0
}

func (x *RequestModifyOrder) GetPriceType() RequestModifyOrder_PriceType {
	if x != nil && x.PriceType != nil {
		return *x.PriceType
	}
	return RequestModifyOrder_LIMIT
}

func (x *RequestModifyOrder) GetManualOrAuto() RequestModifyOrder_OrderPlacement {
	if x != nil && x.ManualOrAuto != nil {
		return *x.ManualOrAuto
	}
	return RequestModifyOrder_MANUAL
}

func (x *RequestModifyOrder) GetTrailingStop() bool {
	if x != nil && x.TrailingStop != nil {
		return *x.TrailingStop
	}
	return false
}

func (x *RequestModifyOrder) GetTrailByTicks() int32 {
	if x != nil && x.TrailByTicks != nil {
		return *x.TrailByTicks
	}
	return 0
}

func (x *RequestModifyOrder) GetIfTouchedSymbol() string {
	if x != nil && x.IfTouchedSymbol != nil {
		return *x.IfTouchedSymbol
	}
	return ""
}

func (x *RequestModifyOrder) GetIfTouchedExchange() string {
	if x != nil && x.IfTouchedExchange != nil {
		return *x.IfTouchedExchange
	}
	return ""
}

func (x *RequestModifyOrder) GetIfTouchedCondition() RequestModifyOrder_Condition {
	if x != nil && x.IfTouchedCondition != nil {
		return *x.IfTouchedCondition
	}
	return RequestModifyOrder_EQUAL_TO
}

func (x *RequestModifyOrder) GetIfTouchedPriceField() RequestModifyOrder_PriceField {
	if x != nil && x.IfTouchedPriceField != nil {
		return *x.IfTouchedPriceField
	}
	return RequestModifyOrder_BID_PRICE
}

func (x *RequestModifyOrder) GetIfTouchedPrice() float64 {
	if x != nil && x.IfTouchedPrice != nil {
		return *x.IfTouchedPrice
	}
	return 0
}

var File_request_modify_order_proto protoreflect.FileDescriptor

const file_request_modify_order_proto_rawDesc = "" +
	"\n" +
	"\x1arequest_modify_order.proto\x12\x03rti\"\x8c\n" +
	"\n" +
	"\x12RequestModifyOrder\x12!\n" +
	"\vtemplate_id\x18\xe3\xb6\t \x02(\x05R\n" +
	"templateId\x12\x1b\n" +
	"\buser_msg\x18\x98\x8d\b \x03(\tR\auserMsg\x12!\n" +
	"\vwindow_name\x18\x85\xb8\t \x01(\tR\n" +
	"windowName\x12\x17\n" +
	"\x06fcm_id\x18\x9d\xb3\t \x01(\tR\x05fcmId\x12\x15\n" +
	"\x05ib_id\x18\x9e\xb3\t \x01(\tR\x04ibId\x12\x1f\n" +
	"\n" +
	"account_id\x18\x98\xb3\t \x01(\tR\taccountId\x12\x1d\n" +
	"\tbasket_id\x18\xdc\xdd\x06 \x01(\tR\bbasketId\x12\x18\n" +
	"\x06symbol\x18\x94\xdc\x06 \x01(\tR\x06symbol\x12\x1c\n" +
	"\bexchange\x18\x95\xdc\x06 \x01(\tR\bexchange\x12\x1c\n" +
	"\bquantity\x18\x84\xeb\x06 \x01(\x05R\bquantity\x12\x16\n" +
	"\x05price\x18\xe2\xdd\x06 \x01(\x01R\x05price\x12%\n" +
	"\rtrigger_price\x18\xff\x8d\t \x01(\x01R\ftriggerPrice\x12B\n" +
	"\n" +
	"price_type\x18\x88\xeb\x06 \x01(\x0e2!.rti.RequestModifyOrder.PriceTypeR\tpriceType\x12N\n" +
	"\x0emanual_or_auto\x18ָ\t \x01(\x0e2&.rti.RequestModifyOrder.OrderPlacementR\fmanualOrAuto\x12%\n" +
	"\rtrailing_stop\x18\x87\xcb\t \x01(\bR\ftrailingStop\x12&\n" +
	"\x0etrail_by_ticks\x18\x88\xcb\t \x01(\x05R\ftrailByTicks\x12,\n" +
	"\x11if_touched_symbol\x18Ӷ\t \x01(\tR\x0fifTouchedSymbol\x120\n" +
	"\x13if_touched_exchange\x18Զ\t \x01(\tR\x11ifTouchedExchange\x12U\n" +
	"\x14if_touched_condition\x18ն\t \x01(\x0e2!.rti.RequestModifyOrder.ConditionR\x12ifTouchedCondition\x12Y\n" +
	"\x16if_touched_price_field\x18ֶ\t \x01(\x0e2\".rti.RequestModifyOrder.PriceFieldR\x13ifTouchedPriceField\x12*\n" +
	"\x10if_touched_price\x18\xa0\xb0\t \x01(\x01R\x0eifTouchedPrice\"p\n" +
	"\tPriceType\x12\t\n" +
	"\x05LIMIT\x10\x01\x12\n" +
	"\n" +
	"\x06MARKET\x10\x02\x12\x0e\n" +
	"\n" +
	"STOP_LIMIT\x10\x03\x12\x0f\n" +
	"\vSTOP_MARKET\x10\x04\x12\x15\n" +
	"\x11MARKET_IF_TOUCHED\x10\x05\x12\x14\n" +
	"\x10LIMIT_IF_TOUCHED\x10\x06\"M\n" +
	"\n" +
	"PriceField\x12\r\n" +
	"\tBID_PRICE\x10\x01\x12\x0f\n" +
	"\vOFFER_PRICE\x10\x02\x12\x0f\n" +
	"\vTRADE_PRICE\x10\x03\x12\x0e\n" +
	"\n" +
	"LEAN_PRICE\x10\x04\"\x83\x01\n" +
	"\tCondition\x12\f\n" +
	"\bEQUAL_TO\x10\x01\x12\x10\n" +
	"\fNOT_EQUAL_TO\x10\x02\x12\x10\n" +
	"\fGREATER_THAN\x10\x03\x12\x19\n" +
	"\x15GREATER_THAN_EQUAL_TO\x10\x04\x12\x0f\n" +
	"\vLESSER_THAN\x10\x05\x12\x18\n" +
	"\x14LESSER_THAN_EQUAL_TO\x10\x06\"&\n" +
	"\x0eOrderPlacement\x12\n" +
	"\n" +
	"\x06MANUAL\x10\x01\x12\b\n" +
	"\x04AUTO\x10\x02B\x1eZ\x1cquant/extensions/rithmic/api"

var (
	file_request_modify_order_proto_rawDescOnce sync.Once
	file_request_modify_order_proto_rawDescData []byte
)

func file_request_modify_order_proto_rawDescGZIP() []byte {
	file_request_modify_order_proto_rawDescOnce.Do(func() {
		file_request_modify_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_request_modify_order_proto_rawDesc), len(file_request_modify_order_proto_rawDesc)))
	})
	return file_request_modify_order_proto_rawDescData
}

var file_request_modify_order_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_request_modify_order_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_request_modify_order_proto_goTypes = []any{
	(RequestModifyOrder_PriceType)(0),      // 0: rti.RequestModifyOrder.PriceType
	(RequestModifyOrder_PriceField)(0),     // 1: rti.RequestModifyOrder.PriceField
	(RequestModifyOrder_Condition)(0),      // 2: rti.RequestModifyOrder.Condition
	(RequestModifyOrder_OrderPlacement)(0), // 3: rti.RequestModifyOrder.OrderPlacement
	(*RequestModifyOrder)(nil),             // 4: rti.RequestModifyOrder
}
var file_request_modify_order_proto_depIdxs = []int32{
	0, // 0: rti.RequestModifyOrder.price_type:type_name -> rti.RequestModifyOrder.PriceType
	3, // 1: rti.RequestModifyOrder.manual_or_auto:type_name -> rti.RequestModifyOrder.OrderPlacement
	2, // 2: rti.RequestModifyOrder.if_touched_condition:type_name -> rti.RequestModifyOrder.Condition
	1, // 3: rti.RequestModifyOrder.if_touched_price_field:type_name -> rti.RequestModifyOrder.PriceField
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_request_modify_order_proto_init() }
func file_request_modify_order_proto_init() {
	if File_request_modify_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_request_modify_order_proto_rawDesc), len(file_request_modify_order_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_request_modify_order_proto_goTypes,
		DependencyIndexes: file_request_modify_order_proto_depIdxs,
		EnumInfos:         file_request_modify_order_proto_enumTypes,
		MessageInfos:      file_request_modify_order_proto_msgTypes,
	}.Build()
	File_request_modify_order_proto = out.File
	file_request_modify_order_proto_goTypes = nil
	file_request_modify_order_proto_depIdxs = nil
}
