// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: request_market_data_update.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// bit constants are defined using enum
type RequestMarketDataUpdate_UpdateBits int32

const (
	RequestMarketDataUpdate_LAST_TRADE           RequestMarketDataUpdate_UpdateBits = 1
	RequestMarketDataUpdate_BBO                  RequestMarketDataUpdate_UpdateBits = 2
	RequestMarketDataUpdate_ORDER_BOOK           RequestMarketDataUpdate_UpdateBits = 4
	RequestMarketDataUpdate_OPEN                 RequestMarketDataUpdate_UpdateBits = 8
	RequestMarketDataUpdate_OPENING_INDICATOR    RequestMarketDataUpdate_UpdateBits = 16
	RequestMarketDataUpdate_HIGH_LOW             RequestMarketDataUpdate_UpdateBits = 32
	RequestMarketDataUpdate_HIGH_BID_LOW_ASK     RequestMarketDataUpdate_UpdateBits = 64
	RequestMarketDataUpdate_CLOSE                RequestMarketDataUpdate_UpdateBits = 128
	RequestMarketDataUpdate_CLOSING_INDICATOR    RequestMarketDataUpdate_UpdateBits = 256
	RequestMarketDataUpdate_SETTLEMENT           RequestMarketDataUpdate_UpdateBits = 512
	RequestMarketDataUpdate_MARKET_MODE          RequestMarketDataUpdate_UpdateBits = 1024
	RequestMarketDataUpdate_OPEN_INTEREST        RequestMarketDataUpdate_UpdateBits = 2048
	RequestMarketDataUpdate_MARGIN_RATE          RequestMarketDataUpdate_UpdateBits = 4096
	RequestMarketDataUpdate_HIGH_PRICE_LIMIT     RequestMarketDataUpdate_UpdateBits = 8192
	RequestMarketDataUpdate_LOW_PRICE_LIMIT      RequestMarketDataUpdate_UpdateBits = 16384
	RequestMarketDataUpdate_PROJECTED_SETTLEMENT RequestMarketDataUpdate_UpdateBits = 32768
	RequestMarketDataUpdate_ADJUSTED_CLOSE       RequestMarketDataUpdate_UpdateBits = 65536
)

// Enum value maps for RequestMarketDataUpdate_UpdateBits.
var (
	RequestMarketDataUpdate_UpdateBits_name = map[int32]string{
		1:     "LAST_TRADE",
		2:     "BBO",
		4:     "ORDER_BOOK",
		8:     "OPEN",
		16:    "OPENING_INDICATOR",
		32:    "HIGH_LOW",
		64:    "HIGH_BID_LOW_ASK",
		128:   "CLOSE",
		256:   "CLOSING_INDICATOR",
		512:   "SETTLEMENT",
		1024:  "MARKET_MODE",
		2048:  "OPEN_INTEREST",
		4096:  "MARGIN_RATE",
		8192:  "HIGH_PRICE_LIMIT",
		16384: "LOW_PRICE_LIMIT",
		32768: "PROJECTED_SETTLEMENT",
		65536: "ADJUSTED_CLOSE",
	}
	RequestMarketDataUpdate_UpdateBits_value = map[string]int32{
		"LAST_TRADE":           1,
		"BBO":                  2,
		"ORDER_BOOK":           4,
		"OPEN":                 8,
		"OPENING_INDICATOR":    16,
		"HIGH_LOW":             32,
		"HIGH_BID_LOW_ASK":     64,
		"CLOSE":                128,
		"CLOSING_INDICATOR":    256,
		"SETTLEMENT":           512,
		"MARKET_MODE":          1024,
		"OPEN_INTEREST":        2048,
		"MARGIN_RATE":          4096,
		"HIGH_PRICE_LIMIT":     8192,
		"LOW_PRICE_LIMIT":      16384,
		"PROJECTED_SETTLEMENT": 32768,
		"ADJUSTED_CLOSE":       65536,
	}
)

func (x RequestMarketDataUpdate_UpdateBits) Enum() *RequestMarketDataUpdate_UpdateBits {
	p := new(RequestMarketDataUpdate_UpdateBits)
	*p = x
	return p
}

func (x RequestMarketDataUpdate_UpdateBits) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestMarketDataUpdate_UpdateBits) Descriptor() protoreflect.EnumDescriptor {
	return file_request_market_data_update_proto_enumTypes[0].Descriptor()
}

func (RequestMarketDataUpdate_UpdateBits) Type() protoreflect.EnumType {
	return &file_request_market_data_update_proto_enumTypes[0]
}

func (x RequestMarketDataUpdate_UpdateBits) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RequestMarketDataUpdate_UpdateBits) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RequestMarketDataUpdate_UpdateBits(num)
	return nil
}

// Deprecated: Use RequestMarketDataUpdate_UpdateBits.Descriptor instead.
func (RequestMarketDataUpdate_UpdateBits) EnumDescriptor() ([]byte, []int) {
	return file_request_market_data_update_proto_rawDescGZIP(), []int{0, 0}
}

type RequestMarketDataUpdate_Request int32

const (
	RequestMarketDataUpdate_SUBSCRIBE   RequestMarketDataUpdate_Request = 1
	RequestMarketDataUpdate_UNSUBSCRIBE RequestMarketDataUpdate_Request = 2
)

// Enum value maps for RequestMarketDataUpdate_Request.
var (
	RequestMarketDataUpdate_Request_name = map[int32]string{
		1: "SUBSCRIBE",
		2: "UNSUBSCRIBE",
	}
	RequestMarketDataUpdate_Request_value = map[string]int32{
		"SUBSCRIBE":   1,
		"UNSUBSCRIBE": 2,
	}
)

func (x RequestMarketDataUpdate_Request) Enum() *RequestMarketDataUpdate_Request {
	p := new(RequestMarketDataUpdate_Request)
	*p = x
	return p
}

func (x RequestMarketDataUpdate_Request) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestMarketDataUpdate_Request) Descriptor() protoreflect.EnumDescriptor {
	return file_request_market_data_update_proto_enumTypes[1].Descriptor()
}

func (RequestMarketDataUpdate_Request) Type() protoreflect.EnumType {
	return &file_request_market_data_update_proto_enumTypes[1]
}

func (x RequestMarketDataUpdate_Request) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RequestMarketDataUpdate_Request) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RequestMarketDataUpdate_Request(num)
	return nil
}

// Deprecated: Use RequestMarketDataUpdate_Request.Descriptor instead.
func (RequestMarketDataUpdate_Request) EnumDescriptor() ([]byte, []int) {
	return file_request_market_data_update_proto_rawDescGZIP(), []int{0, 1}
}

type RequestMarketDataUpdate struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	TemplateId    *int32                           `protobuf:"varint,154467,req,name=template_id,json=templateId" json:"template_id,omitempty"`
	UserMsg       []string                         `protobuf:"bytes,132760,rep,name=user_msg,json=userMsg" json:"user_msg,omitempty"`
	Symbol        *string                          `protobuf:"bytes,110100,opt,name=symbol" json:"symbol,omitempty"`
	Exchange      *string                          `protobuf:"bytes,110101,opt,name=exchange" json:"exchange,omitempty"`
	Request       *RequestMarketDataUpdate_Request `protobuf:"varint,100000,opt,name=request,enum=rti.RequestMarketDataUpdate_Request" json:"request,omitempty"`
	UpdateBits    *uint32                          `protobuf:"varint,154211,opt,name=update_bits,json=updateBits" json:"update_bits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestMarketDataUpdate) Reset() {
	*x = RequestMarketDataUpdate{}
	mi := &file_request_market_data_update_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestMarketDataUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestMarketDataUpdate) ProtoMessage() {}

func (x *RequestMarketDataUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_request_market_data_update_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestMarketDataUpdate.ProtoReflect.Descriptor instead.
func (*RequestMarketDataUpdate) Descriptor() ([]byte, []int) {
	return file_request_market_data_update_proto_rawDescGZIP(), []int{0}
}

func (x *RequestMarketDataUpdate) GetTemplateId() int32 {
	if x != nil && x.TemplateId != nil {
		return *x.TemplateId
	}
	return 0
}

func (x *RequestMarketDataUpdate) GetUserMsg() []string {
	if x != nil {
		return x.UserMsg
	}
	return nil
}

func (x *RequestMarketDataUpdate) GetSymbol() string {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return ""
}

func (x *RequestMarketDataUpdate) GetExchange() string {
	if x != nil && x.Exchange != nil {
		return *x.Exchange
	}
	return ""
}

func (x *RequestMarketDataUpdate) GetRequest() RequestMarketDataUpdate_Request {
	if x != nil && x.Request != nil {
		return *x.Request
	}
	return RequestMarketDataUpdate_SUBSCRIBE
}

func (x *RequestMarketDataUpdate) GetUpdateBits() uint32 {
	if x != nil && x.UpdateBits != nil {
		return *x.UpdateBits
	}
	return 0
}

var File_request_market_data_update_proto protoreflect.FileDescriptor

const file_request_market_data_update_proto_rawDesc = "" +
	"\n" +
	" request_market_data_update.proto\x12\x03rti\"\xeb\x04\n" +
	"\x17RequestMarketDataUpdate\x12!\n" +
	"\vtemplate_id\x18\xe3\xb6\t \x02(\x05R\n" +
	"templateId\x12\x1b\n" +
	"\buser_msg\x18\x98\x8d\b \x03(\tR\auserMsg\x12\x18\n" +
	"\x06symbol\x18\x94\xdc\x06 \x01(\tR\x06symbol\x12\x1c\n" +
	"\bexchange\x18\x95\xdc\x06 \x01(\tR\bexchange\x12@\n" +
	"\arequest\x18\xa0\x8d\x06 \x01(\x0e2$.rti.RequestMarketDataUpdate.RequestR\arequest\x12!\n" +
	"\vupdate_bits\x18\xe3\xb4\t \x01(\rR\n" +
	"updateBits\"\xc7\x02\n" +
	"\n" +
	"UpdateBits\x12\x0e\n" +
	"\n" +
	"LAST_TRADE\x10\x01\x12\a\n" +
	"\x03BBO\x10\x02\x12\x0e\n" +
	"\n" +
	"ORDER_BOOK\x10\x04\x12\b\n" +
	"\x04OPEN\x10\b\x12\x15\n" +
	"\x11OPENING_INDICATOR\x10\x10\x12\f\n" +
	"\bHIGH_LOW\x10 \x12\x14\n" +
	"\x10HIGH_BID_LOW_ASK\x10@\x12\n" +
	"\n" +
	"\x05CLOSE\x10\x80\x01\x12\x16\n" +
	"\x11CLOSING_INDICATOR\x10\x80\x02\x12\x0f\n" +
	"\n" +
	"SETTLEMENT\x10\x80\x04\x12\x10\n" +
	"\vMARKET_MODE\x10\x80\b\x12\x12\n" +
	"\rOPEN_INTEREST\x10\x80\x10\x12\x10\n" +
	"\vMARGIN_RATE\x10\x80 \x12\x15\n" +
	"\x10HIGH_PRICE_LIMIT\x10\x80@\x12\x15\n" +
	"\x0fLOW_PRICE_LIMIT\x10\x80\x80\x01\x12\x1a\n" +
	"\x14PROJECTED_SETTLEMENT\x10\x80\x80\x02\x12\x14\n" +
	"\x0eADJUSTED_CLOSE\x10\x80\x80\x04\")\n" +
	"\aRequest\x12\r\n" +
	"\tSUBSCRIBE\x10\x01\x12\x0f\n" +
	"\vUNSUBSCRIBE\x10\x02B\x1eZ\x1cquant/extensions/rithmic/api"

var (
	file_request_market_data_update_proto_rawDescOnce sync.Once
	file_request_market_data_update_proto_rawDescData []byte
)

func file_request_market_data_update_proto_rawDescGZIP() []byte {
	file_request_market_data_update_proto_rawDescOnce.Do(func() {
		file_request_market_data_update_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_request_market_data_update_proto_rawDesc), len(file_request_market_data_update_proto_rawDesc)))
	})
	return file_request_market_data_update_proto_rawDescData
}

var file_request_market_data_update_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_request_market_data_update_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_request_market_data_update_proto_goTypes = []any{
	(RequestMarketDataUpdate_UpdateBits)(0), // 0: rti.RequestMarketDataUpdate.UpdateBits
	(RequestMarketDataUpdate_Request)(0),    // 1: rti.RequestMarketDataUpdate.Request
	(*RequestMarketDataUpdate)(nil),         // 2: rti.RequestMarketDataUpdate
}
var file_request_market_data_update_proto_depIdxs = []int32{
	1, // 0: rti.RequestMarketDataUpdate.request:type_name -> rti.RequestMarketDataUpdate.Request
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_request_market_data_update_proto_init() }
func file_request_market_data_update_proto_init() {
	if File_request_market_data_update_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_request_market_data_update_proto_rawDesc), len(file_request_market_data_update_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_request_market_data_update_proto_goTypes,
		DependencyIndexes: file_request_market_data_update_proto_depIdxs,
		EnumInfos:         file_request_market_data_update_proto_enumTypes,
		MessageInfos:      file_request_market_data_update_proto_msgTypes,
	}.Build()
	File_request_market_data_update_proto = out.File
	file_request_market_data_update_proto_goTypes = nil
	file_request_market_data_update_proto_depIdxs = nil
}
