// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: request_update_target_bracket_level.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestUpdateTargetBracketLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    *int32                 `protobuf:"varint,154467,req,name=template_id,json=templateId" json:"template_id,omitempty"`    // PB_OFFSET + MNM_TEMPLATE_ID
	UserMsg       []string               `protobuf:"bytes,132760,rep,name=user_msg,json=userMsg" json:"user_msg,omitempty"`              // PB_OFFSET + MNM_USER_MSG
	FcmId         *string                `protobuf:"bytes,154013,opt,name=fcm_id,json=fcmId" json:"fcm_id,omitempty"`                    // PB_OFFSET + MNM_FCM_ID
	IbId          *string                `protobuf:"bytes,154014,opt,name=ib_id,json=ibId" json:"ib_id,omitempty"`                       // PB_OFFSET + MNM_IB_ID
	AccountId     *string                `protobuf:"bytes,154008,opt,name=account_id,json=accountId" json:"account_id,omitempty"`        // PB_OFFSET + MNM_ACCOUNT_ID
	BasketId      *string                `protobuf:"bytes,110300,opt,name=basket_id,json=basketId" json:"basket_id,omitempty"`           // PB_OFFSET + MNM_BASKET_ID
	Level         *int32                 `protobuf:"varint,154244,opt,name=level" json:"level,omitempty"`                                // PB_OFFSET + MNM_LEVEL
	TargetTicks   *int32                 `protobuf:"varint,154456,opt,name=target_ticks,json=targetTicks" json:"target_ticks,omitempty"` // PB_OFFSET + MNM_TARGET_TICKS
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestUpdateTargetBracketLevel) Reset() {
	*x = RequestUpdateTargetBracketLevel{}
	mi := &file_request_update_target_bracket_level_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestUpdateTargetBracketLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestUpdateTargetBracketLevel) ProtoMessage() {}

func (x *RequestUpdateTargetBracketLevel) ProtoReflect() protoreflect.Message {
	mi := &file_request_update_target_bracket_level_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestUpdateTargetBracketLevel.ProtoReflect.Descriptor instead.
func (*RequestUpdateTargetBracketLevel) Descriptor() ([]byte, []int) {
	return file_request_update_target_bracket_level_proto_rawDescGZIP(), []int{0}
}

func (x *RequestUpdateTargetBracketLevel) GetTemplateId() int32 {
	if x != nil && x.TemplateId != nil {
		return *x.TemplateId
	}
	return 0
}

func (x *RequestUpdateTargetBracketLevel) GetUserMsg() []string {
	if x != nil {
		return x.UserMsg
	}
	return nil
}

func (x *RequestUpdateTargetBracketLevel) GetFcmId() string {
	if x != nil && x.FcmId != nil {
		return *x.FcmId
	}
	return ""
}

func (x *RequestUpdateTargetBracketLevel) GetIbId() string {
	if x != nil && x.IbId != nil {
		return *x.IbId
	}
	return ""
}

func (x *RequestUpdateTargetBracketLevel) GetAccountId() string {
	if x != nil && x.AccountId != nil {
		return *x.AccountId
	}
	return ""
}

func (x *RequestUpdateTargetBracketLevel) GetBasketId() string {
	if x != nil && x.BasketId != nil {
		return *x.BasketId
	}
	return ""
}

func (x *RequestUpdateTargetBracketLevel) GetLevel() int32 {
	if x != nil && x.Level != nil {
		return *x.Level
	}
	return 0
}

func (x *RequestUpdateTargetBracketLevel) GetTargetTicks() int32 {
	if x != nil && x.TargetTicks != nil {
		return *x.TargetTicks
	}
	return 0
}

var File_request_update_target_bracket_level_proto protoreflect.FileDescriptor

const file_request_update_target_bracket_level_proto_rawDesc = "" +
	"\n" +
	")request_update_target_bracket_level.proto\x12\x03rti\"\x8e\x02\n" +
	"\x1fRequestUpdateTargetBracketLevel\x12!\n" +
	"\vtemplate_id\x18\xe3\xb6\t \x02(\x05R\n" +
	"templateId\x12\x1b\n" +
	"\buser_msg\x18\x98\x8d\b \x03(\tR\auserMsg\x12\x17\n" +
	"\x06fcm_id\x18\x9d\xb3\t \x01(\tR\x05fcmId\x12\x15\n" +
	"\x05ib_id\x18\x9e\xb3\t \x01(\tR\x04ibId\x12\x1f\n" +
	"\n" +
	"account_id\x18\x98\xb3\t \x01(\tR\taccountId\x12\x1d\n" +
	"\tbasket_id\x18\xdc\xdd\x06 \x01(\tR\bbasketId\x12\x16\n" +
	"\x05level\x18\x84\xb5\t \x01(\x05R\x05level\x12#\n" +
	"\ftarget_ticks\x18ض\t \x01(\x05R\vtargetTicksB\x1eZ\x1cquant/extensions/rithmic/api"

var (
	file_request_update_target_bracket_level_proto_rawDescOnce sync.Once
	file_request_update_target_bracket_level_proto_rawDescData []byte
)

func file_request_update_target_bracket_level_proto_rawDescGZIP() []byte {
	file_request_update_target_bracket_level_proto_rawDescOnce.Do(func() {
		file_request_update_target_bracket_level_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_request_update_target_bracket_level_proto_rawDesc), len(file_request_update_target_bracket_level_proto_rawDesc)))
	})
	return file_request_update_target_bracket_level_proto_rawDescData
}

var file_request_update_target_bracket_level_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_request_update_target_bracket_level_proto_goTypes = []any{
	(*RequestUpdateTargetBracketLevel)(nil), // 0: rti.RequestUpdateTargetBracketLevel
}
var file_request_update_target_bracket_level_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_request_update_target_bracket_level_proto_init() }
func file_request_update_target_bracket_level_proto_init() {
	if File_request_update_target_bracket_level_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_request_update_target_bracket_level_proto_rawDesc), len(file_request_update_target_bracket_level_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_request_update_target_bracket_level_proto_goTypes,
		DependencyIndexes: file_request_update_target_bracket_level_proto_depIdxs,
		MessageInfos:      file_request_update_target_bracket_level_proto_msgTypes,
	}.Build()
	File_request_update_target_bracket_level_proto = out.File
	file_request_update_target_bracket_level_proto_goTypes = nil
	file_request_update_target_bracket_level_proto_depIdxs = nil
}
