// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: request_set_rithmic_mrkt_data_self_cert_status.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestSetRithmicMrktDataSelfCertStatus struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	TemplateId              *int32                 `protobuf:"varint,154467,req,name=template_id,json=templateId" json:"template_id,omitempty"`
	UserMsg                 []string               `protobuf:"bytes,132760,rep,name=user_msg,json=userMsg" json:"user_msg,omitempty"`
	AgreementId             *string                `protobuf:"bytes,153407,opt,name=agreement_id,json=agreementId" json:"agreement_id,omitempty"`
	MarketDataUsageCapacity *string                `protobuf:"bytes,153431,opt,name=market_data_usage_capacity,json=marketDataUsageCapacity" json:"market_data_usage_capacity,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *RequestSetRithmicMrktDataSelfCertStatus) Reset() {
	*x = RequestSetRithmicMrktDataSelfCertStatus{}
	mi := &file_request_set_rithmic_mrkt_data_self_cert_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestSetRithmicMrktDataSelfCertStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestSetRithmicMrktDataSelfCertStatus) ProtoMessage() {}

func (x *RequestSetRithmicMrktDataSelfCertStatus) ProtoReflect() protoreflect.Message {
	mi := &file_request_set_rithmic_mrkt_data_self_cert_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestSetRithmicMrktDataSelfCertStatus.ProtoReflect.Descriptor instead.
func (*RequestSetRithmicMrktDataSelfCertStatus) Descriptor() ([]byte, []int) {
	return file_request_set_rithmic_mrkt_data_self_cert_status_proto_rawDescGZIP(), []int{0}
}

func (x *RequestSetRithmicMrktDataSelfCertStatus) GetTemplateId() int32 {
	if x != nil && x.TemplateId != nil {
		return *x.TemplateId
	}
	return 0
}

func (x *RequestSetRithmicMrktDataSelfCertStatus) GetUserMsg() []string {
	if x != nil {
		return x.UserMsg
	}
	return nil
}

func (x *RequestSetRithmicMrktDataSelfCertStatus) GetAgreementId() string {
	if x != nil && x.AgreementId != nil {
		return *x.AgreementId
	}
	return ""
}

func (x *RequestSetRithmicMrktDataSelfCertStatus) GetMarketDataUsageCapacity() string {
	if x != nil && x.MarketDataUsageCapacity != nil {
		return *x.MarketDataUsageCapacity
	}
	return ""
}

var File_request_set_rithmic_mrkt_data_self_cert_status_proto protoreflect.FileDescriptor

const file_request_set_rithmic_mrkt_data_self_cert_status_proto_rawDesc = "" +
	"\n" +
	"4request_set_rithmic_mrkt_data_self_cert_status.proto\x12\x03rti\"\xcd\x01\n" +
	"'RequestSetRithmicMrktDataSelfCertStatus\x12!\n" +
	"\vtemplate_id\x18\xe3\xb6\t \x02(\x05R\n" +
	"templateId\x12\x1b\n" +
	"\buser_msg\x18\x98\x8d\b \x03(\tR\auserMsg\x12#\n" +
	"\fagreement_id\x18\xbf\xae\t \x01(\tR\vagreementId\x12=\n" +
	"\x1amarket_data_usage_capacity\x18\u05ee\t \x01(\tR\x17marketDataUsageCapacityB\x1eZ\x1cquant/extensions/rithmic/api"

var (
	file_request_set_rithmic_mrkt_data_self_cert_status_proto_rawDescOnce sync.Once
	file_request_set_rithmic_mrkt_data_self_cert_status_proto_rawDescData []byte
)

func file_request_set_rithmic_mrkt_data_self_cert_status_proto_rawDescGZIP() []byte {
	file_request_set_rithmic_mrkt_data_self_cert_status_proto_rawDescOnce.Do(func() {
		file_request_set_rithmic_mrkt_data_self_cert_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_request_set_rithmic_mrkt_data_self_cert_status_proto_rawDesc), len(file_request_set_rithmic_mrkt_data_self_cert_status_proto_rawDesc)))
	})
	return file_request_set_rithmic_mrkt_data_self_cert_status_proto_rawDescData
}

var file_request_set_rithmic_mrkt_data_self_cert_status_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_request_set_rithmic_mrkt_data_self_cert_status_proto_goTypes = []any{
	(*RequestSetRithmicMrktDataSelfCertStatus)(nil), // 0: rti.RequestSetRithmicMrktDataSelfCertStatus
}
var file_request_set_rithmic_mrkt_data_self_cert_status_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_request_set_rithmic_mrkt_data_self_cert_status_proto_init() }
func file_request_set_rithmic_mrkt_data_self_cert_status_proto_init() {
	if File_request_set_rithmic_mrkt_data_self_cert_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_request_set_rithmic_mrkt_data_self_cert_status_proto_rawDesc), len(file_request_set_rithmic_mrkt_data_self_cert_status_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_request_set_rithmic_mrkt_data_self_cert_status_proto_goTypes,
		DependencyIndexes: file_request_set_rithmic_mrkt_data_self_cert_status_proto_depIdxs,
		MessageInfos:      file_request_set_rithmic_mrkt_data_self_cert_status_proto_msgTypes,
	}.Build()
	File_request_set_rithmic_mrkt_data_self_cert_status_proto = out.File
	file_request_set_rithmic_mrkt_data_self_cert_status_proto_goTypes = nil
	file_request_set_rithmic_mrkt_data_self_cert_status_proto_depIdxs = nil
}
