// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: request_product_codes.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestProductCodes struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TemplateId          *int32                 `protobuf:"varint,154467,req,name=template_id,json=templateId" json:"template_id,omitempty"`                                // PB_OFFSET + MNM_TEMPLATE_ID
	UserMsg             []string               `protobuf:"bytes,132760,rep,name=user_msg,json=userMsg" json:"user_msg,omitempty"`                                          // PB_OFFSET + MNM_USER_MSG
	Exchange            *string                `protobuf:"bytes,110101,opt,name=exchange" json:"exchange,omitempty"`                                                       // PB_OFFSET + MNM_EXCHANGE
	GiveToiProductsOnly *bool                  `protobuf:"varint,153499,opt,name=give_toi_products_only,json=giveToiProductsOnly" json:"give_toi_products_only,omitempty"` // PB_OFFSET + MNM_TOI_PRODUCTS_ONLY
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *RequestProductCodes) Reset() {
	*x = RequestProductCodes{}
	mi := &file_request_product_codes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestProductCodes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestProductCodes) ProtoMessage() {}

func (x *RequestProductCodes) ProtoReflect() protoreflect.Message {
	mi := &file_request_product_codes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestProductCodes.ProtoReflect.Descriptor instead.
func (*RequestProductCodes) Descriptor() ([]byte, []int) {
	return file_request_product_codes_proto_rawDescGZIP(), []int{0}
}

func (x *RequestProductCodes) GetTemplateId() int32 {
	if x != nil && x.TemplateId != nil {
		return *x.TemplateId
	}
	return 0
}

func (x *RequestProductCodes) GetUserMsg() []string {
	if x != nil {
		return x.UserMsg
	}
	return nil
}

func (x *RequestProductCodes) GetExchange() string {
	if x != nil && x.Exchange != nil {
		return *x.Exchange
	}
	return ""
}

func (x *RequestProductCodes) GetGiveToiProductsOnly() bool {
	if x != nil && x.GiveToiProductsOnly != nil {
		return *x.GiveToiProductsOnly
	}
	return false
}

var File_request_product_codes_proto protoreflect.FileDescriptor

const file_request_product_codes_proto_rawDesc = "" +
	"\n" +
	"\x1brequest_product_codes.proto\x12\x03rti\"\xaa\x01\n" +
	"\x13RequestProductCodes\x12!\n" +
	"\vtemplate_id\x18\xe3\xb6\t \x02(\x05R\n" +
	"templateId\x12\x1b\n" +
	"\buser_msg\x18\x98\x8d\b \x03(\tR\auserMsg\x12\x1c\n" +
	"\bexchange\x18\x95\xdc\x06 \x01(\tR\bexchange\x125\n" +
	"\x16give_toi_products_only\x18\x9b\xaf\t \x01(\bR\x13giveToiProductsOnlyB\x1eZ\x1cquant/extensions/rithmic/api"

var (
	file_request_product_codes_proto_rawDescOnce sync.Once
	file_request_product_codes_proto_rawDescData []byte
)

func file_request_product_codes_proto_rawDescGZIP() []byte {
	file_request_product_codes_proto_rawDescOnce.Do(func() {
		file_request_product_codes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_request_product_codes_proto_rawDesc), len(file_request_product_codes_proto_rawDesc)))
	})
	return file_request_product_codes_proto_rawDescData
}

var file_request_product_codes_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_request_product_codes_proto_goTypes = []any{
	(*RequestProductCodes)(nil), // 0: rti.RequestProductCodes
}
var file_request_product_codes_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_request_product_codes_proto_init() }
func file_request_product_codes_proto_init() {
	if File_request_product_codes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_request_product_codes_proto_rawDesc), len(file_request_product_codes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_request_product_codes_proto_goTypes,
		DependencyIndexes: file_request_product_codes_proto_depIdxs,
		MessageInfos:      file_request_product_codes_proto_msgTypes,
	}.Build()
	File_request_product_codes_proto = out.File
	file_request_product_codes_proto_goTypes = nil
	file_request_product_codes_proto_depIdxs = nil
}
