// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: request_cancel_order.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestCancelOrder_OrderPlacement int32

const (
	RequestCancelOrder_MANUAL RequestCancelOrder_OrderPlacement = 1
	RequestCancelOrder_AUTO   RequestCancelOrder_OrderPlacement = 2
)

// Enum value maps for RequestCancelOrder_OrderPlacement.
var (
	RequestCancelOrder_OrderPlacement_name = map[int32]string{
		1: "MANUAL",
		2: "AUTO",
	}
	RequestCancelOrder_OrderPlacement_value = map[string]int32{
		"MANUAL": 1,
		"AUTO":   2,
	}
)

func (x RequestCancelOrder_OrderPlacement) Enum() *RequestCancelOrder_OrderPlacement {
	p := new(RequestCancelOrder_OrderPlacement)
	*p = x
	return p
}

func (x RequestCancelOrder_OrderPlacement) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestCancelOrder_OrderPlacement) Descriptor() protoreflect.EnumDescriptor {
	return file_request_cancel_order_proto_enumTypes[0].Descriptor()
}

func (RequestCancelOrder_OrderPlacement) Type() protoreflect.EnumType {
	return &file_request_cancel_order_proto_enumTypes[0]
}

func (x RequestCancelOrder_OrderPlacement) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RequestCancelOrder_OrderPlacement) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RequestCancelOrder_OrderPlacement(num)
	return nil
}

// Deprecated: Use RequestCancelOrder_OrderPlacement.Descriptor instead.
func (RequestCancelOrder_OrderPlacement) EnumDescriptor() ([]byte, []int) {
	return file_request_cancel_order_proto_rawDescGZIP(), []int{0, 0}
}

type RequestCancelOrder struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	TemplateId    *int32                             `protobuf:"varint,154467,req,name=template_id,json=templateId" json:"template_id,omitempty"`
	UserMsg       []string                           `protobuf:"bytes,132760,rep,name=user_msg,json=userMsg" json:"user_msg,omitempty"`
	WindowName    *string                            `protobuf:"bytes,154629,opt,name=window_name,json=windowName" json:"window_name,omitempty"`
	FcmId         *string                            `protobuf:"bytes,154013,opt,name=fcm_id,json=fcmId" json:"fcm_id,omitempty"`
	IbId          *string                            `protobuf:"bytes,154014,opt,name=ib_id,json=ibId" json:"ib_id,omitempty"`
	AccountId     *string                            `protobuf:"bytes,154008,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
	BasketId      *string                            `protobuf:"bytes,110300,opt,name=basket_id,json=basketId" json:"basket_id,omitempty"`
	ManualOrAuto  *RequestCancelOrder_OrderPlacement `protobuf:"varint,154710,opt,name=manual_or_auto,json=manualOrAuto,enum=rti.RequestCancelOrder_OrderPlacement" json:"manual_or_auto,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestCancelOrder) Reset() {
	*x = RequestCancelOrder{}
	mi := &file_request_cancel_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestCancelOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestCancelOrder) ProtoMessage() {}

func (x *RequestCancelOrder) ProtoReflect() protoreflect.Message {
	mi := &file_request_cancel_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestCancelOrder.ProtoReflect.Descriptor instead.
func (*RequestCancelOrder) Descriptor() ([]byte, []int) {
	return file_request_cancel_order_proto_rawDescGZIP(), []int{0}
}

func (x *RequestCancelOrder) GetTemplateId() int32 {
	if x != nil && x.TemplateId != nil {
		return *x.TemplateId
	}
	return 0
}

func (x *RequestCancelOrder) GetUserMsg() []string {
	if x != nil {
		return x.UserMsg
	}
	return nil
}

func (x *RequestCancelOrder) GetWindowName() string {
	if x != nil && x.WindowName != nil {
		return *x.WindowName
	}
	return ""
}

func (x *RequestCancelOrder) GetFcmId() string {
	if x != nil && x.FcmId != nil {
		return *x.FcmId
	}
	return ""
}

func (x *RequestCancelOrder) GetIbId() string {
	if x != nil && x.IbId != nil {
		return *x.IbId
	}
	return ""
}

func (x *RequestCancelOrder) GetAccountId() string {
	if x != nil && x.AccountId != nil {
		return *x.AccountId
	}
	return ""
}

func (x *RequestCancelOrder) GetBasketId() string {
	if x != nil && x.BasketId != nil {
		return *x.BasketId
	}
	return ""
}

func (x *RequestCancelOrder) GetManualOrAuto() RequestCancelOrder_OrderPlacement {
	if x != nil && x.ManualOrAuto != nil {
		return *x.ManualOrAuto
	}
	return RequestCancelOrder_MANUAL
}

var File_request_cancel_order_proto protoreflect.FileDescriptor

const file_request_cancel_order_proto_rawDesc = "" +
	"\n" +
	"\x1arequest_cancel_order.proto\x12\x03rti\"\xdf\x02\n" +
	"\x12RequestCancelOrder\x12!\n" +
	"\vtemplate_id\x18\xe3\xb6\t \x02(\x05R\n" +
	"templateId\x12\x1b\n" +
	"\buser_msg\x18\x98\x8d\b \x03(\tR\auserMsg\x12!\n" +
	"\vwindow_name\x18\x85\xb8\t \x01(\tR\n" +
	"windowName\x12\x17\n" +
	"\x06fcm_id\x18\x9d\xb3\t \x01(\tR\x05fcmId\x12\x15\n" +
	"\x05ib_id\x18\x9e\xb3\t \x01(\tR\x04ibId\x12\x1f\n" +
	"\n" +
	"account_id\x18\x98\xb3\t \x01(\tR\taccountId\x12\x1d\n" +
	"\tbasket_id\x18\xdc\xdd\x06 \x01(\tR\bbasketId\x12N\n" +
	"\x0emanual_or_auto\x18ָ\t \x01(\x0e2&.rti.RequestCancelOrder.OrderPlacementR\fmanualOrAuto\"&\n" +
	"\x0eOrderPlacement\x12\n" +
	"\n" +
	"\x06MANUAL\x10\x01\x12\b\n" +
	"\x04AUTO\x10\x02B\x1eZ\x1cquant/extensions/rithmic/api"

var (
	file_request_cancel_order_proto_rawDescOnce sync.Once
	file_request_cancel_order_proto_rawDescData []byte
)

func file_request_cancel_order_proto_rawDescGZIP() []byte {
	file_request_cancel_order_proto_rawDescOnce.Do(func() {
		file_request_cancel_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_request_cancel_order_proto_rawDesc), len(file_request_cancel_order_proto_rawDesc)))
	})
	return file_request_cancel_order_proto_rawDescData
}

var file_request_cancel_order_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_request_cancel_order_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_request_cancel_order_proto_goTypes = []any{
	(RequestCancelOrder_OrderPlacement)(0), // 0: rti.RequestCancelOrder.OrderPlacement
	(*RequestCancelOrder)(nil),             // 1: rti.RequestCancelOrder
}
var file_request_cancel_order_proto_depIdxs = []int32{
	0, // 0: rti.RequestCancelOrder.manual_or_auto:type_name -> rti.RequestCancelOrder.OrderPlacement
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_request_cancel_order_proto_init() }
func file_request_cancel_order_proto_init() {
	if File_request_cancel_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_request_cancel_order_proto_rawDesc), len(file_request_cancel_order_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_request_cancel_order_proto_goTypes,
		DependencyIndexes: file_request_cancel_order_proto_depIdxs,
		EnumInfos:         file_request_cancel_order_proto_enumTypes,
		MessageInfos:      file_request_cancel_order_proto_msgTypes,
	}.Build()
	File_request_cancel_order_proto = out.File
	file_request_cancel_order_proto_goTypes = nil
	file_request_cancel_order_proto_depIdxs = nil
}
