// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: response_list_exchange_permissions.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseListExchangePermissions_EntitlementFlag int32

const (
	ResponseListExchangePermissions_ENABLED  ResponseListExchangePermissions_EntitlementFlag = 1
	ResponseListExchangePermissions_DISABLED ResponseListExchangePermissions_EntitlementFlag = 2
)

// Enum value maps for ResponseListExchangePermissions_EntitlementFlag.
var (
	ResponseListExchangePermissions_EntitlementFlag_name = map[int32]string{
		1: "ENABLED",
		2: "DISABLED",
	}
	ResponseListExchangePermissions_EntitlementFlag_value = map[string]int32{
		"ENABLED":  1,
		"DISABLED": 2,
	}
)

func (x ResponseListExchangePermissions_EntitlementFlag) Enum() *ResponseListExchangePermissions_EntitlementFlag {
	p := new(ResponseListExchangePermissions_EntitlementFlag)
	*p = x
	return p
}

func (x ResponseListExchangePermissions_EntitlementFlag) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseListExchangePermissions_EntitlementFlag) Descriptor() protoreflect.EnumDescriptor {
	return file_response_list_exchange_permissions_proto_enumTypes[0].Descriptor()
}

func (ResponseListExchangePermissions_EntitlementFlag) Type() protoreflect.EnumType {
	return &file_response_list_exchange_permissions_proto_enumTypes[0]
}

func (x ResponseListExchangePermissions_EntitlementFlag) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ResponseListExchangePermissions_EntitlementFlag) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ResponseListExchangePermissions_EntitlementFlag(num)
	return nil
}

// Deprecated: Use ResponseListExchangePermissions_EntitlementFlag.Descriptor instead.
func (ResponseListExchangePermissions_EntitlementFlag) EnumDescriptor() ([]byte, []int) {
	return file_response_list_exchange_permissions_proto_rawDescGZIP(), []int{0, 0}
}

type ResponseListExchangePermissions struct {
	state           protoimpl.MessageState                           `protogen:"open.v1"`
	TemplateId      *int32                                           `protobuf:"varint,154467,req,name=template_id,json=templateId" json:"template_id,omitempty"`                                                                         // PB_OFFSET + MNM_TEMPLATE_ID
	UserMsg         []string                                         `protobuf:"bytes,132760,rep,name=user_msg,json=userMsg" json:"user_msg,omitempty"`                                                                                   // PB_OFFSET + MNM_USER_MSG
	RqHandlerRpCode []string                                         `protobuf:"bytes,132764,rep,name=rq_handler_rp_code,json=rqHandlerRpCode" json:"rq_handler_rp_code,omitempty"`                                                       // PB_OFFSET + MNM_REQUEST_HANDLER_RESPONSE_CODE
	RpCode          []string                                         `protobuf:"bytes,132766,rep,name=rp_code,json=rpCode" json:"rp_code,omitempty"`                                                                                      // PB_OFFSET + MNM_RESPONSE_CODE
	Exchange        *string                                          `protobuf:"bytes,110101,opt,name=exchange" json:"exchange,omitempty"`                                                                                                // PB_OFFSET + MNM_EXCHANGE
	EntitlementFlag *ResponseListExchangePermissions_EntitlementFlag `protobuf:"varint,153400,opt,name=entitlement_flag,json=entitlementFlag,enum=rti.ResponseListExchangePermissions_EntitlementFlag" json:"entitlement_flag,omitempty"` // PB_OFFSET + MNM_ENTITLEMENT_FLAG
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResponseListExchangePermissions) Reset() {
	*x = ResponseListExchangePermissions{}
	mi := &file_response_list_exchange_permissions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseListExchangePermissions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseListExchangePermissions) ProtoMessage() {}

func (x *ResponseListExchangePermissions) ProtoReflect() protoreflect.Message {
	mi := &file_response_list_exchange_permissions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseListExchangePermissions.ProtoReflect.Descriptor instead.
func (*ResponseListExchangePermissions) Descriptor() ([]byte, []int) {
	return file_response_list_exchange_permissions_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseListExchangePermissions) GetTemplateId() int32 {
	if x != nil && x.TemplateId != nil {
		return *x.TemplateId
	}
	return 0
}

func (x *ResponseListExchangePermissions) GetUserMsg() []string {
	if x != nil {
		return x.UserMsg
	}
	return nil
}

func (x *ResponseListExchangePermissions) GetRqHandlerRpCode() []string {
	if x != nil {
		return x.RqHandlerRpCode
	}
	return nil
}

func (x *ResponseListExchangePermissions) GetRpCode() []string {
	if x != nil {
		return x.RpCode
	}
	return nil
}

func (x *ResponseListExchangePermissions) GetExchange() string {
	if x != nil && x.Exchange != nil {
		return *x.Exchange
	}
	return ""
}

func (x *ResponseListExchangePermissions) GetEntitlementFlag() ResponseListExchangePermissions_EntitlementFlag {
	if x != nil && x.EntitlementFlag != nil {
		return *x.EntitlementFlag
	}
	return ResponseListExchangePermissions_ENABLED
}

var File_response_list_exchange_permissions_proto protoreflect.FileDescriptor

const file_response_list_exchange_permissions_proto_rawDesc = "" +
	"\n" +
	"(response_list_exchange_permissions.proto\x12\x03rti\"\xda\x02\n" +
	"\x1fResponseListExchangePermissions\x12!\n" +
	"\vtemplate_id\x18\xe3\xb6\t \x02(\x05R\n" +
	"templateId\x12\x1b\n" +
	"\buser_msg\x18\x98\x8d\b \x03(\tR\auserMsg\x12-\n" +
	"\x12rq_handler_rp_code\x18\x9c\x8d\b \x03(\tR\x0frqHandlerRpCode\x12\x19\n" +
	"\arp_code\x18\x9e\x8d\b \x03(\tR\x06rpCode\x12\x1c\n" +
	"\bexchange\x18\x95\xdc\x06 \x01(\tR\bexchange\x12a\n" +
	"\x10entitlement_flag\x18\xb8\xae\t \x01(\x0e24.rti.ResponseListExchangePermissions.EntitlementFlagR\x0fentitlementFlag\",\n" +
	"\x0fEntitlementFlag\x12\v\n" +
	"\aENABLED\x10\x01\x12\f\n" +
	"\bDISABLED\x10\x02B\x1eZ\x1cquant/extensions/rithmic/api"

var (
	file_response_list_exchange_permissions_proto_rawDescOnce sync.Once
	file_response_list_exchange_permissions_proto_rawDescData []byte
)

func file_response_list_exchange_permissions_proto_rawDescGZIP() []byte {
	file_response_list_exchange_permissions_proto_rawDescOnce.Do(func() {
		file_response_list_exchange_permissions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_response_list_exchange_permissions_proto_rawDesc), len(file_response_list_exchange_permissions_proto_rawDesc)))
	})
	return file_response_list_exchange_permissions_proto_rawDescData
}

var file_response_list_exchange_permissions_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_response_list_exchange_permissions_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_response_list_exchange_permissions_proto_goTypes = []any{
	(ResponseListExchangePermissions_EntitlementFlag)(0), // 0: rti.ResponseListExchangePermissions.EntitlementFlag
	(*ResponseListExchangePermissions)(nil),              // 1: rti.ResponseListExchangePermissions
}
var file_response_list_exchange_permissions_proto_depIdxs = []int32{
	0, // 0: rti.ResponseListExchangePermissions.entitlement_flag:type_name -> rti.ResponseListExchangePermissions.EntitlementFlag
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_response_list_exchange_permissions_proto_init() }
func file_response_list_exchange_permissions_proto_init() {
	if File_response_list_exchange_permissions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_response_list_exchange_permissions_proto_rawDesc), len(file_response_list_exchange_permissions_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_response_list_exchange_permissions_proto_goTypes,
		DependencyIndexes: file_response_list_exchange_permissions_proto_depIdxs,
		EnumInfos:         file_response_list_exchange_permissions_proto_enumTypes,
		MessageInfos:      file_response_list_exchange_permissions_proto_msgTypes,
	}.Build()
	File_response_list_exchange_permissions_proto = out.File
	file_response_list_exchange_permissions_proto_goTypes = nil
	file_response_list_exchange_permissions_proto_depIdxs = nil
}
