// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: response_get_instrument_by_underlying.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// bit constants are defined using enum
type ResponseGetInstrumentByUnderlying_PresenceBits int32

const (
	ResponseGetInstrumentByUnderlying_EXCHANGE_SYMBOL      ResponseGetInstrumentByUnderlying_PresenceBits = 1
	ResponseGetInstrumentByUnderlying_SYMBOL_NAME          ResponseGetInstrumentByUnderlying_PresenceBits = 2
	ResponseGetInstrumentByUnderlying_PRODUCT_CODE         ResponseGetInstrumentByUnderlying_PresenceBits = 4
	ResponseGetInstrumentByUnderlying_INSTRUMENT_TYPE      ResponseGetInstrumentByUnderlying_PresenceBits = 8
	ResponseGetInstrumentByUnderlying_UNDERLYING_SYMBOL    ResponseGetInstrumentByUnderlying_PresenceBits = 16
	ResponseGetInstrumentByUnderlying_EXPIRATION_DATE      ResponseGetInstrumentByUnderlying_PresenceBits = 32
	ResponseGetInstrumentByUnderlying_CURRENCY             ResponseGetInstrumentByUnderlying_PresenceBits = 64
	ResponseGetInstrumentByUnderlying_PUT_CALL_INDICATOR   ResponseGetInstrumentByUnderlying_PresenceBits = 128
	ResponseGetInstrumentByUnderlying_STRIKE_PRICE         ResponseGetInstrumentByUnderlying_PresenceBits = 256
	ResponseGetInstrumentByUnderlying_FPRICE_TO_QPRICE     ResponseGetInstrumentByUnderlying_PresenceBits = 512
	ResponseGetInstrumentByUnderlying_QPRICE_TO_FPRICE     ResponseGetInstrumentByUnderlying_PresenceBits = 1024
	ResponseGetInstrumentByUnderlying_MIN_QPRICE_CHANGE    ResponseGetInstrumentByUnderlying_PresenceBits = 2048
	ResponseGetInstrumentByUnderlying_MIN_FRPICE_CHANGE    ResponseGetInstrumentByUnderlying_PresenceBits = 4096
	ResponseGetInstrumentByUnderlying_SINGLE_POINT_VALUE   ResponseGetInstrumentByUnderlying_PresenceBits = 8192
	ResponseGetInstrumentByUnderlying_TICK_SIZE_TYPE       ResponseGetInstrumentByUnderlying_PresenceBits = 16384
	ResponseGetInstrumentByUnderlying_PRICE_DISPLAY_FORMAT ResponseGetInstrumentByUnderlying_PresenceBits = 32768
)

// Enum value maps for ResponseGetInstrumentByUnderlying_PresenceBits.
var (
	ResponseGetInstrumentByUnderlying_PresenceBits_name = map[int32]string{
		1:     "EXCHANGE_SYMBOL",
		2:     "SYMBOL_NAME",
		4:     "PRODUCT_CODE",
		8:     "INSTRUMENT_TYPE",
		16:    "UNDERLYING_SYMBOL",
		32:    "EXPIRATION_DATE",
		64:    "CURRENCY",
		128:   "PUT_CALL_INDICATOR",
		256:   "STRIKE_PRICE",
		512:   "FPRICE_TO_QPRICE",
		1024:  "QPRICE_TO_FPRICE",
		2048:  "MIN_QPRICE_CHANGE",
		4096:  "MIN_FRPICE_CHANGE",
		8192:  "SINGLE_POINT_VALUE",
		16384: "TICK_SIZE_TYPE",
		32768: "PRICE_DISPLAY_FORMAT",
	}
	ResponseGetInstrumentByUnderlying_PresenceBits_value = map[string]int32{
		"EXCHANGE_SYMBOL":      1,
		"SYMBOL_NAME":          2,
		"PRODUCT_CODE":         4,
		"INSTRUMENT_TYPE":      8,
		"UNDERLYING_SYMBOL":    16,
		"EXPIRATION_DATE":      32,
		"CURRENCY":             64,
		"PUT_CALL_INDICATOR":   128,
		"STRIKE_PRICE":         256,
		"FPRICE_TO_QPRICE":     512,
		"QPRICE_TO_FPRICE":     1024,
		"MIN_QPRICE_CHANGE":    2048,
		"MIN_FRPICE_CHANGE":    4096,
		"SINGLE_POINT_VALUE":   8192,
		"TICK_SIZE_TYPE":       16384,
		"PRICE_DISPLAY_FORMAT": 32768,
	}
)

func (x ResponseGetInstrumentByUnderlying_PresenceBits) Enum() *ResponseGetInstrumentByUnderlying_PresenceBits {
	p := new(ResponseGetInstrumentByUnderlying_PresenceBits)
	*p = x
	return p
}

func (x ResponseGetInstrumentByUnderlying_PresenceBits) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseGetInstrumentByUnderlying_PresenceBits) Descriptor() protoreflect.EnumDescriptor {
	return file_response_get_instrument_by_underlying_proto_enumTypes[0].Descriptor()
}

func (ResponseGetInstrumentByUnderlying_PresenceBits) Type() protoreflect.EnumType {
	return &file_response_get_instrument_by_underlying_proto_enumTypes[0]
}

func (x ResponseGetInstrumentByUnderlying_PresenceBits) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ResponseGetInstrumentByUnderlying_PresenceBits) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ResponseGetInstrumentByUnderlying_PresenceBits(num)
	return nil
}

// Deprecated: Use ResponseGetInstrumentByUnderlying_PresenceBits.Descriptor instead.
func (ResponseGetInstrumentByUnderlying_PresenceBits) EnumDescriptor() ([]byte, []int) {
	return file_response_get_instrument_by_underlying_proto_rawDescGZIP(), []int{0, 0}
}

type ResponseGetInstrumentByUnderlying struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TemplateId         *int32                 `protobuf:"varint,154467,req,name=template_id,json=templateId" json:"template_id,omitempty"`                          // PB_OFFSET + MNM_TEMPLATE_ID
	UserMsg            []string               `protobuf:"bytes,132760,rep,name=user_msg,json=userMsg" json:"user_msg,omitempty"`                                    // PB_OFFSET + MNM_USER_MSG
	RqHandlerRpCode    []string               `protobuf:"bytes,132764,rep,name=rq_handler_rp_code,json=rqHandlerRpCode" json:"rq_handler_rp_code,omitempty"`        // PB_OFFSET + MNM_REQUEST_HANDLER_RESPONSE_CODE
	RpCode             []string               `protobuf:"bytes,132766,rep,name=rp_code,json=rpCode" json:"rp_code,omitempty"`                                       // PB_OFFSET + MNM_RESPONSE_CODE
	PresenceBits       *uint32                `protobuf:"varint,149138,opt,name=presence_bits,json=presenceBits" json:"presence_bits,omitempty"`                    // PB_OFFSET + MNM_PRICING_INDICATOR
	ClearBits          *uint32                `protobuf:"varint,154571,opt,name=clear_bits,json=clearBits" json:"clear_bits,omitempty"`                             // PB_OFFSET + MNM_DISPLAY_INDICATOR
	Symbol             *string                `protobuf:"bytes,110100,opt,name=symbol" json:"symbol,omitempty"`                                                     // PB_OFFSET + MNM_SYMBOL
	Exchange           *string                `protobuf:"bytes,110101,opt,name=exchange" json:"exchange,omitempty"`                                                 // PB_OFFSET + MNM_EXCHANGE
	ExchangeSymbol     *string                `protobuf:"bytes,110114,opt,name=exchange_symbol,json=exchangeSymbol" json:"exchange_symbol,omitempty"`               // PB_OFFSET + MNM_EXCHANGE_SYMBOL
	SymbolName         *string                `protobuf:"bytes,100003,opt,name=symbol_name,json=symbolName" json:"symbol_name,omitempty"`                           // PB_OFFSET + MNM_SYMBOL_NAME
	ProductCode        *string                `protobuf:"bytes,100749,opt,name=product_code,json=productCode" json:"product_code,omitempty"`                        // PB_OFFSET + MNM_PRODUCT_CODE
	InstrumentType     *string                `protobuf:"bytes,110116,opt,name=instrument_type,json=instrumentType" json:"instrument_type,omitempty"`               // PB_OFFSET + MNM_INSTRUMENT_TYPE
	UnderlyingSymbol   *string                `protobuf:"bytes,101026,opt,name=underlying_symbol,json=underlyingSymbol" json:"underlying_symbol,omitempty"`         // PB_OFFSET + MNM_UNDERLYING_SYMBOL
	ExpirationDate     *string                `protobuf:"bytes,100067,opt,name=expiration_date,json=expirationDate" json:"expiration_date,omitempty"`               // PB_OFFSET + MNM_EXPIRATION_DATE
	Currency           *string                `protobuf:"bytes,154382,opt,name=currency" json:"currency,omitempty"`                                                 // PB_OFFSET + MNM_SYMBOL_CURRENCY
	PutCallIndicator   *string                `protobuf:"bytes,100109,opt,name=put_call_indicator,json=putCallIndicator" json:"put_call_indicator,omitempty"`       // PB_OFFSET + MNM_PUT_CALL_INDICATOR
	TickSizeType       *string                `protobuf:"bytes,154167,opt,name=tick_size_type,json=tickSizeType" json:"tick_size_type,omitempty"`                   // PB_OFFSET + MNM_TICK_SIZE_TYPE
	PriceDisplayFormat *string                `protobuf:"bytes,154390,opt,name=price_display_format,json=priceDisplayFormat" json:"price_display_format,omitempty"` // PB_OFFSET + MNM_PRICE_DISPLAY_FORMAT
	StrikePrice        *float64               `protobuf:"fixed64,100066,opt,name=strike_price,json=strikePrice" json:"strike_price,omitempty"`                      // PB_OFFSET + MNM_STRIKE_PRICE
	FtoqPrice          *float64               `protobuf:"fixed64,154384,opt,name=ftoq_price,json=ftoqPrice" json:"ftoq_price,omitempty"`                            // PB_OFFSET + MNM_FPRICE_TO_QPRICE
	QtofPrice          *float64               `protobuf:"fixed64,154385,opt,name=qtof_price,json=qtofPrice" json:"qtof_price,omitempty"`                            // PB_OFFSET + MNM_QPRICE_TO_FPRICE
	MinQpriceChange    *float64               `protobuf:"fixed64,154386,opt,name=min_qprice_change,json=minQpriceChange" json:"min_qprice_change,omitempty"`        // PB_OFFSET + MNM_MIN_QPRICE_CHANGE
	MinFpriceChange    *float64               `protobuf:"fixed64,154387,opt,name=min_fprice_change,json=minFpriceChange" json:"min_fprice_change,omitempty"`        // PB_OFFSET + MNM_MIN_FPRICE_CHANGE
	SinglePointValue   *float64               `protobuf:"fixed64,154389,opt,name=single_point_value,json=singlePointValue" json:"single_point_value,omitempty"`     // PB_OFFSET + MNM_SINGLE_POINT_VALUE
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ResponseGetInstrumentByUnderlying) Reset() {
	*x = ResponseGetInstrumentByUnderlying{}
	mi := &file_response_get_instrument_by_underlying_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGetInstrumentByUnderlying) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetInstrumentByUnderlying) ProtoMessage() {}

func (x *ResponseGetInstrumentByUnderlying) ProtoReflect() protoreflect.Message {
	mi := &file_response_get_instrument_by_underlying_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetInstrumentByUnderlying.ProtoReflect.Descriptor instead.
func (*ResponseGetInstrumentByUnderlying) Descriptor() ([]byte, []int) {
	return file_response_get_instrument_by_underlying_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseGetInstrumentByUnderlying) GetTemplateId() int32 {
	if x != nil && x.TemplateId != nil {
		return *x.TemplateId
	}
	return 0
}

func (x *ResponseGetInstrumentByUnderlying) GetUserMsg() []string {
	if x != nil {
		return x.UserMsg
	}
	return nil
}

func (x *ResponseGetInstrumentByUnderlying) GetRqHandlerRpCode() []string {
	if x != nil {
		return x.RqHandlerRpCode
	}
	return nil
}

func (x *ResponseGetInstrumentByUnderlying) GetRpCode() []string {
	if x != nil {
		return x.RpCode
	}
	return nil
}

func (x *ResponseGetInstrumentByUnderlying) GetPresenceBits() uint32 {
	if x != nil && x.PresenceBits != nil {
		return *x.PresenceBits
	}
	return 0
}

func (x *ResponseGetInstrumentByUnderlying) GetClearBits() uint32 {
	if x != nil && x.ClearBits != nil {
		return *x.ClearBits
	}
	return 0
}

func (x *ResponseGetInstrumentByUnderlying) GetSymbol() string {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return ""
}

func (x *ResponseGetInstrumentByUnderlying) GetExchange() string {
	if x != nil && x.Exchange != nil {
		return *x.Exchange
	}
	return ""
}

func (x *ResponseGetInstrumentByUnderlying) GetExchangeSymbol() string {
	if x != nil && x.ExchangeSymbol != nil {
		return *x.ExchangeSymbol
	}
	return ""
}

func (x *ResponseGetInstrumentByUnderlying) GetSymbolName() string {
	if x != nil && x.SymbolName != nil {
		return *x.SymbolName
	}
	return ""
}

func (x *ResponseGetInstrumentByUnderlying) GetProductCode() string {
	if x != nil && x.ProductCode != nil {
		return *x.ProductCode
	}
	return ""
}

func (x *ResponseGetInstrumentByUnderlying) GetInstrumentType() string {
	if x != nil && x.InstrumentType != nil {
		return *x.InstrumentType
	}
	return ""
}

func (x *ResponseGetInstrumentByUnderlying) GetUnderlyingSymbol() string {
	if x != nil && x.UnderlyingSymbol != nil {
		return *x.UnderlyingSymbol
	}
	return ""
}

func (x *ResponseGetInstrumentByUnderlying) GetExpirationDate() string {
	if x != nil && x.ExpirationDate != nil {
		return *x.ExpirationDate
	}
	return ""
}

func (x *ResponseGetInstrumentByUnderlying) GetCurrency() string {
	if x != nil && x.Currency != nil {
		return *x.Currency
	}
	return ""
}

func (x *ResponseGetInstrumentByUnderlying) GetPutCallIndicator() string {
	if x != nil && x.PutCallIndicator != nil {
		return *x.PutCallIndicator
	}
	return ""
}

func (x *ResponseGetInstrumentByUnderlying) GetTickSizeType() string {
	if x != nil && x.TickSizeType != nil {
		return *x.TickSizeType
	}
	return ""
}

func (x *ResponseGetInstrumentByUnderlying) GetPriceDisplayFormat() string {
	if x != nil && x.PriceDisplayFormat != nil {
		return *x.PriceDisplayFormat
	}
	return ""
}

func (x *ResponseGetInstrumentByUnderlying) GetStrikePrice() float64 {
	if x != nil && x.StrikePrice != nil {
		return *x.StrikePrice
	}
	return 0
}

func (x *ResponseGetInstrumentByUnderlying) GetFtoqPrice() float64 {
	if x != nil && x.FtoqPrice != nil {
		return *x.FtoqPrice
	}
	return 0
}

func (x *ResponseGetInstrumentByUnderlying) GetQtofPrice() float64 {
	if x != nil && x.QtofPrice != nil {
		return *x.QtofPrice
	}
	return 0
}

func (x *ResponseGetInstrumentByUnderlying) GetMinQpriceChange() float64 {
	if x != nil && x.MinQpriceChange != nil {
		return *x.MinQpriceChange
	}
	return 0
}

func (x *ResponseGetInstrumentByUnderlying) GetMinFpriceChange() float64 {
	if x != nil && x.MinFpriceChange != nil {
		return *x.MinFpriceChange
	}
	return 0
}

func (x *ResponseGetInstrumentByUnderlying) GetSinglePointValue() float64 {
	if x != nil && x.SinglePointValue != nil {
		return *x.SinglePointValue
	}
	return 0
}

var File_response_get_instrument_by_underlying_proto protoreflect.FileDescriptor

const file_response_get_instrument_by_underlying_proto_rawDesc = "" +
	"\n" +
	"+response_get_instrument_by_underlying.proto\x12\x03rti\"\xaf\n" +
	"\n" +
	"!ResponseGetInstrumentByUnderlying\x12!\n" +
	"\vtemplate_id\x18\xe3\xb6\t \x02(\x05R\n" +
	"templateId\x12\x1b\n" +
	"\buser_msg\x18\x98\x8d\b \x03(\tR\auserMsg\x12-\n" +
	"\x12rq_handler_rp_code\x18\x9c\x8d\b \x03(\tR\x0frqHandlerRpCode\x12\x19\n" +
	"\arp_code\x18\x9e\x8d\b \x03(\tR\x06rpCode\x12%\n" +
	"\rpresence_bits\x18\x92\x8d\t \x01(\rR\fpresenceBits\x12\x1f\n" +
	"\n" +
	"clear_bits\x18˷\t \x01(\rR\tclearBits\x12\x18\n" +
	"\x06symbol\x18\x94\xdc\x06 \x01(\tR\x06symbol\x12\x1c\n" +
	"\bexchange\x18\x95\xdc\x06 \x01(\tR\bexchange\x12)\n" +
	"\x0fexchange_symbol\x18\xa2\xdc\x06 \x01(\tR\x0eexchangeSymbol\x12!\n" +
	"\vsymbol_name\x18\xa3\x8d\x06 \x01(\tR\n" +
	"symbolName\x12#\n" +
	"\fproduct_code\x18\x8d\x93\x06 \x01(\tR\vproductCode\x12)\n" +
	"\x0finstrument_type\x18\xa4\xdc\x06 \x01(\tR\x0einstrumentType\x12-\n" +
	"\x11underlying_symbol\x18\xa2\x95\x06 \x01(\tR\x10underlyingSymbol\x12)\n" +
	"\x0fexpiration_date\x18\xe3\x8d\x06 \x01(\tR\x0eexpirationDate\x12\x1c\n" +
	"\bcurrency\x18\x8e\xb6\t \x01(\tR\bcurrency\x12.\n" +
	"\x12put_call_indicator\x18\x8d\x8e\x06 \x01(\tR\x10putCallIndicator\x12&\n" +
	"\x0etick_size_type\x18\xb7\xb4\t \x01(\tR\ftickSizeType\x122\n" +
	"\x14price_display_format\x18\x96\xb6\t \x01(\tR\x12priceDisplayFormat\x12#\n" +
	"\fstrike_price\x18\xe2\x8d\x06 \x01(\x01R\vstrikePrice\x12\x1f\n" +
	"\n" +
	"ftoq_price\x18\x90\xb6\t \x01(\x01R\tftoqPrice\x12\x1f\n" +
	"\n" +
	"qtof_price\x18\x91\xb6\t \x01(\x01R\tqtofPrice\x12,\n" +
	"\x11min_qprice_change\x18\x92\xb6\t \x01(\x01R\x0fminQpriceChange\x12,\n" +
	"\x11min_fprice_change\x18\x93\xb6\t \x01(\x01R\x0fminFpriceChange\x12.\n" +
	"\x12single_point_value\x18\x95\xb6\t \x01(\x01R\x10singlePointValue\"\xea\x02\n" +
	"\fPresenceBits\x12\x13\n" +
	"\x0fEXCHANGE_SYMBOL\x10\x01\x12\x0f\n" +
	"\vSYMBOL_NAME\x10\x02\x12\x10\n" +
	"\fPRODUCT_CODE\x10\x04\x12\x13\n" +
	"\x0fINSTRUMENT_TYPE\x10\b\x12\x15\n" +
	"\x11UNDERLYING_SYMBOL\x10\x10\x12\x13\n" +
	"\x0fEXPIRATION_DATE\x10 \x12\f\n" +
	"\bCURRENCY\x10@\x12\x17\n" +
	"\x12PUT_CALL_INDICATOR\x10\x80\x01\x12\x11\n" +
	"\fSTRIKE_PRICE\x10\x80\x02\x12\x15\n" +
	"\x10FPRICE_TO_QPRICE\x10\x80\x04\x12\x15\n" +
	"\x10QPRICE_TO_FPRICE\x10\x80\b\x12\x16\n" +
	"\x11MIN_QPRICE_CHANGE\x10\x80\x10\x12\x16\n" +
	"\x11MIN_FRPICE_CHANGE\x10\x80 \x12\x17\n" +
	"\x12SINGLE_POINT_VALUE\x10\x80@\x12\x14\n" +
	"\x0eTICK_SIZE_TYPE\x10\x80\x80\x01\x12\x1a\n" +
	"\x14PRICE_DISPLAY_FORMAT\x10\x80\x80\x02B\x1eZ\x1cquant/extensions/rithmic/api"

var (
	file_response_get_instrument_by_underlying_proto_rawDescOnce sync.Once
	file_response_get_instrument_by_underlying_proto_rawDescData []byte
)

func file_response_get_instrument_by_underlying_proto_rawDescGZIP() []byte {
	file_response_get_instrument_by_underlying_proto_rawDescOnce.Do(func() {
		file_response_get_instrument_by_underlying_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_response_get_instrument_by_underlying_proto_rawDesc), len(file_response_get_instrument_by_underlying_proto_rawDesc)))
	})
	return file_response_get_instrument_by_underlying_proto_rawDescData
}

var file_response_get_instrument_by_underlying_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_response_get_instrument_by_underlying_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_response_get_instrument_by_underlying_proto_goTypes = []any{
	(ResponseGetInstrumentByUnderlying_PresenceBits)(0), // 0: rti.ResponseGetInstrumentByUnderlying.PresenceBits
	(*ResponseGetInstrumentByUnderlying)(nil),           // 1: rti.ResponseGetInstrumentByUnderlying
}
var file_response_get_instrument_by_underlying_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_response_get_instrument_by_underlying_proto_init() }
func file_response_get_instrument_by_underlying_proto_init() {
	if File_response_get_instrument_by_underlying_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_response_get_instrument_by_underlying_proto_rawDesc), len(file_response_get_instrument_by_underlying_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_response_get_instrument_by_underlying_proto_goTypes,
		DependencyIndexes: file_response_get_instrument_by_underlying_proto_depIdxs,
		EnumInfos:         file_response_get_instrument_by_underlying_proto_enumTypes,
		MessageInfos:      file_response_get_instrument_by_underlying_proto_msgTypes,
	}.Build()
	File_response_get_instrument_by_underlying_proto = out.File
	file_response_get_instrument_by_underlying_proto_goTypes = nil
	file_response_get_instrument_by_underlying_proto_depIdxs = nil
}
