// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: response_subscribe_for_order_updates.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseSubscribeForOrderUpdates struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    *int32                 `protobuf:"varint,154467,req,name=template_id,json=templateId" json:"template_id,omitempty"` // PB_OFFSET + MNM_TEMPLATE_ID
	UserMsg       []string               `protobuf:"bytes,132760,rep,name=user_msg,json=userMsg" json:"user_msg,omitempty"`           // PB_OFFSET + MNM_USER_MSG
	RpCode        []string               `protobuf:"bytes,132766,rep,name=rp_code,json=rpCode" json:"rp_code,omitempty"`              // PB_OFFSET + MNM_RESPONSE_CODE
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseSubscribeForOrderUpdates) Reset() {
	*x = ResponseSubscribeForOrderUpdates{}
	mi := &file_response_subscribe_for_order_updates_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseSubscribeForOrderUpdates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseSubscribeForOrderUpdates) ProtoMessage() {}

func (x *ResponseSubscribeForOrderUpdates) ProtoReflect() protoreflect.Message {
	mi := &file_response_subscribe_for_order_updates_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseSubscribeForOrderUpdates.ProtoReflect.Descriptor instead.
func (*ResponseSubscribeForOrderUpdates) Descriptor() ([]byte, []int) {
	return file_response_subscribe_for_order_updates_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseSubscribeForOrderUpdates) GetTemplateId() int32 {
	if x != nil && x.TemplateId != nil {
		return *x.TemplateId
	}
	return 0
}

func (x *ResponseSubscribeForOrderUpdates) GetUserMsg() []string {
	if x != nil {
		return x.UserMsg
	}
	return nil
}

func (x *ResponseSubscribeForOrderUpdates) GetRpCode() []string {
	if x != nil {
		return x.RpCode
	}
	return nil
}

var File_response_subscribe_for_order_updates_proto protoreflect.FileDescriptor

const file_response_subscribe_for_order_updates_proto_rawDesc = "" +
	"\n" +
	"*response_subscribe_for_order_updates.proto\x12\x03rti\"}\n" +
	" ResponseSubscribeForOrderUpdates\x12!\n" +
	"\vtemplate_id\x18\xe3\xb6\t \x02(\x05R\n" +
	"templateId\x12\x1b\n" +
	"\buser_msg\x18\x98\x8d\b \x03(\tR\auserMsg\x12\x19\n" +
	"\arp_code\x18\x9e\x8d\b \x03(\tR\x06rpCodeB\x1eZ\x1cquant/extensions/rithmic/api"

var (
	file_response_subscribe_for_order_updates_proto_rawDescOnce sync.Once
	file_response_subscribe_for_order_updates_proto_rawDescData []byte
)

func file_response_subscribe_for_order_updates_proto_rawDescGZIP() []byte {
	file_response_subscribe_for_order_updates_proto_rawDescOnce.Do(func() {
		file_response_subscribe_for_order_updates_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_response_subscribe_for_order_updates_proto_rawDesc), len(file_response_subscribe_for_order_updates_proto_rawDesc)))
	})
	return file_response_subscribe_for_order_updates_proto_rawDescData
}

var file_response_subscribe_for_order_updates_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_response_subscribe_for_order_updates_proto_goTypes = []any{
	(*ResponseSubscribeForOrderUpdates)(nil), // 0: rti.ResponseSubscribeForOrderUpdates
}
var file_response_subscribe_for_order_updates_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_response_subscribe_for_order_updates_proto_init() }
func file_response_subscribe_for_order_updates_proto_init() {
	if File_response_subscribe_for_order_updates_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_response_subscribe_for_order_updates_proto_rawDesc), len(file_response_subscribe_for_order_updates_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_response_subscribe_for_order_updates_proto_goTypes,
		DependencyIndexes: file_response_subscribe_for_order_updates_proto_depIdxs,
		MessageInfos:      file_response_subscribe_for_order_updates_proto_msgTypes,
	}.Build()
	File_response_subscribe_for_order_updates_proto = out.File
	file_response_subscribe_for_order_updates_proto_goTypes = nil
	file_response_subscribe_for_order_updates_proto_depIdxs = nil
}
