// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: symbol_margin_rate.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SymbolMarginRate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    *int32                 `protobuf:"varint,154467,req,name=template_id,json=templateId" json:"template_id,omitempty"`  // PB_OFFSET + MNM_TEMPLATE_ID
	Symbol        *string                `protobuf:"bytes,110100,opt,name=symbol" json:"symbol,omitempty"`                             // PB_OFFSET + MNM_SYMBOL
	Exchange      *string                `protobuf:"bytes,110101,opt,name=exchange" json:"exchange,omitempty"`                         // PB_OFFSET + MNM_EXCHANGE
	IsSnapshot    *bool                  `protobuf:"varint,110121,opt,name=is_snapshot,json=isSnapshot" json:"is_snapshot,omitempty"`  // PB_OFFSET + MNM_UPDATE_TYPE
	MarginRate    *float64               `protobuf:"fixed64,154103,opt,name=margin_rate,json=marginRate" json:"margin_rate,omitempty"` // PB_OFFSET + MNM_MARGIN_RATE
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SymbolMarginRate) Reset() {
	*x = SymbolMarginRate{}
	mi := &file_symbol_margin_rate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SymbolMarginRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymbolMarginRate) ProtoMessage() {}

func (x *SymbolMarginRate) ProtoReflect() protoreflect.Message {
	mi := &file_symbol_margin_rate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymbolMarginRate.ProtoReflect.Descriptor instead.
func (*SymbolMarginRate) Descriptor() ([]byte, []int) {
	return file_symbol_margin_rate_proto_rawDescGZIP(), []int{0}
}

func (x *SymbolMarginRate) GetTemplateId() int32 {
	if x != nil && x.TemplateId != nil {
		return *x.TemplateId
	}
	return 0
}

func (x *SymbolMarginRate) GetSymbol() string {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return ""
}

func (x *SymbolMarginRate) GetExchange() string {
	if x != nil && x.Exchange != nil {
		return *x.Exchange
	}
	return ""
}

func (x *SymbolMarginRate) GetIsSnapshot() bool {
	if x != nil && x.IsSnapshot != nil {
		return *x.IsSnapshot
	}
	return false
}

func (x *SymbolMarginRate) GetMarginRate() float64 {
	if x != nil && x.MarginRate != nil {
		return *x.MarginRate
	}
	return 0
}

var File_symbol_margin_rate_proto protoreflect.FileDescriptor

const file_symbol_margin_rate_proto_rawDesc = "" +
	"\n" +
	"\x18symbol_margin_rate.proto\x12\x03rti\"\xb3\x01\n" +
	"\x10SymbolMarginRate\x12!\n" +
	"\vtemplate_id\x18\xe3\xb6\t \x02(\x05R\n" +
	"templateId\x12\x18\n" +
	"\x06symbol\x18\x94\xdc\x06 \x01(\tR\x06symbol\x12\x1c\n" +
	"\bexchange\x18\x95\xdc\x06 \x01(\tR\bexchange\x12!\n" +
	"\vis_snapshot\x18\xa9\xdc\x06 \x01(\bR\n" +
	"isSnapshot\x12!\n" +
	"\vmargin_rate\x18\xf7\xb3\t \x01(\x01R\n" +
	"marginRateB\x1eZ\x1cquant/extensions/rithmic/api"

var (
	file_symbol_margin_rate_proto_rawDescOnce sync.Once
	file_symbol_margin_rate_proto_rawDescData []byte
)

func file_symbol_margin_rate_proto_rawDescGZIP() []byte {
	file_symbol_margin_rate_proto_rawDescOnce.Do(func() {
		file_symbol_margin_rate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_symbol_margin_rate_proto_rawDesc), len(file_symbol_margin_rate_proto_rawDesc)))
	})
	return file_symbol_margin_rate_proto_rawDescData
}

var file_symbol_margin_rate_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_symbol_margin_rate_proto_goTypes = []any{
	(*SymbolMarginRate)(nil), // 0: rti.SymbolMarginRate
}
var file_symbol_margin_rate_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_symbol_margin_rate_proto_init() }
func file_symbol_margin_rate_proto_init() {
	if File_symbol_margin_rate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_symbol_margin_rate_proto_rawDesc), len(file_symbol_margin_rate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_symbol_margin_rate_proto_goTypes,
		DependencyIndexes: file_symbol_margin_rate_proto_depIdxs,
		MessageInfos:      file_symbol_margin_rate_proto_msgTypes,
	}.Build()
	File_symbol_margin_rate_proto = out.File
	file_symbol_margin_rate_proto_goTypes = nil
	file_symbol_margin_rate_proto_depIdxs = nil
}
