// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: update_easy_to_borrow_list.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateEasyToBorrowList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    *int32                 `protobuf:"varint,154467,req,name=template_id,json=templateId" json:"template_id,omitempty"`       // PB_OFFSET + MNM_TEMPLATE_ID
	BrokerDealer  *string                `protobuf:"bytes,154612,opt,name=broker_dealer,json=brokerDealer" json:"broker_dealer,omitempty"`  // PB_OFFSET + MNM_BROKER_DEALER
	Symbol        *string                `protobuf:"bytes,110100,opt,name=symbol" json:"symbol,omitempty"`                                  // PB_OFFSET + MNM_SYMBOL
	SymbolName    *string                `protobuf:"bytes,100003,opt,name=symbol_name,json=symbolName" json:"symbol_name,omitempty"`        // PB_OFFSET + MNM_SYMBOL_NAME
	QtyAvailable  *int32                 `protobuf:"varint,154613,opt,name=qty_available,json=qtyAvailable" json:"qty_available,omitempty"` // PB_OFFSET + MNM_TOTAL_AVAILABLE_QTY
	QtyNeeded     *int32                 `protobuf:"varint,154614,opt,name=qty_needed,json=qtyNeeded" json:"qty_needed,omitempty"`          // PB_OFFSET + MNM_TOTAL_USED_QTY
	Borrowable    *bool                  `protobuf:"varint,110353,opt,name=borrowable" json:"borrowable,omitempty"`                         // PB_OFFSET + MNM_SHORT_LIST_INDICATOR
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEasyToBorrowList) Reset() {
	*x = UpdateEasyToBorrowList{}
	mi := &file_update_easy_to_borrow_list_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEasyToBorrowList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEasyToBorrowList) ProtoMessage() {}

func (x *UpdateEasyToBorrowList) ProtoReflect() protoreflect.Message {
	mi := &file_update_easy_to_borrow_list_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEasyToBorrowList.ProtoReflect.Descriptor instead.
func (*UpdateEasyToBorrowList) Descriptor() ([]byte, []int) {
	return file_update_easy_to_borrow_list_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateEasyToBorrowList) GetTemplateId() int32 {
	if x != nil && x.TemplateId != nil {
		return *x.TemplateId
	}
	return 0
}

func (x *UpdateEasyToBorrowList) GetBrokerDealer() string {
	if x != nil && x.BrokerDealer != nil {
		return *x.BrokerDealer
	}
	return ""
}

func (x *UpdateEasyToBorrowList) GetSymbol() string {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return ""
}

func (x *UpdateEasyToBorrowList) GetSymbolName() string {
	if x != nil && x.SymbolName != nil {
		return *x.SymbolName
	}
	return ""
}

func (x *UpdateEasyToBorrowList) GetQtyAvailable() int32 {
	if x != nil && x.QtyAvailable != nil {
		return *x.QtyAvailable
	}
	return 0
}

func (x *UpdateEasyToBorrowList) GetQtyNeeded() int32 {
	if x != nil && x.QtyNeeded != nil {
		return *x.QtyNeeded
	}
	return 0
}

func (x *UpdateEasyToBorrowList) GetBorrowable() bool {
	if x != nil && x.Borrowable != nil {
		return *x.Borrowable
	}
	return false
}

var File_update_easy_to_borrow_list_proto protoreflect.FileDescriptor

const file_update_easy_to_borrow_list_proto_rawDesc = "" +
	"\n" +
	" update_easy_to_borrow_list.proto\x12\x03rti\"\x89\x02\n" +
	"\x16UpdateEasyToBorrowList\x12!\n" +
	"\vtemplate_id\x18\xe3\xb6\t \x02(\x05R\n" +
	"templateId\x12%\n" +
	"\rbroker_dealer\x18\xf4\xb7\t \x01(\tR\fbrokerDealer\x12\x18\n" +
	"\x06symbol\x18\x94\xdc\x06 \x01(\tR\x06symbol\x12!\n" +
	"\vsymbol_name\x18\xa3\x8d\x06 \x01(\tR\n" +
	"symbolName\x12%\n" +
	"\rqty_available\x18\xf5\xb7\t \x01(\x05R\fqtyAvailable\x12\x1f\n" +
	"\n" +
	"qty_needed\x18\xf6\xb7\t \x01(\x05R\tqtyNeeded\x12 \n" +
	"\n" +
	"borrowable\x18\x91\xde\x06 \x01(\bR\n" +
	"borrowableB\x1eZ\x1cquant/extensions/rithmic/api"

var (
	file_update_easy_to_borrow_list_proto_rawDescOnce sync.Once
	file_update_easy_to_borrow_list_proto_rawDescData []byte
)

func file_update_easy_to_borrow_list_proto_rawDescGZIP() []byte {
	file_update_easy_to_borrow_list_proto_rawDescOnce.Do(func() {
		file_update_easy_to_borrow_list_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_update_easy_to_borrow_list_proto_rawDesc), len(file_update_easy_to_borrow_list_proto_rawDesc)))
	})
	return file_update_easy_to_borrow_list_proto_rawDescData
}

var file_update_easy_to_borrow_list_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_update_easy_to_borrow_list_proto_goTypes = []any{
	(*UpdateEasyToBorrowList)(nil), // 0: rti.UpdateEasyToBorrowList
}
var file_update_easy_to_borrow_list_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_update_easy_to_borrow_list_proto_init() }
func file_update_easy_to_borrow_list_proto_init() {
	if File_update_easy_to_borrow_list_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_update_easy_to_borrow_list_proto_rawDesc), len(file_update_easy_to_borrow_list_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_update_easy_to_borrow_list_proto_goTypes,
		DependencyIndexes: file_update_easy_to_borrow_list_proto_depIdxs,
		MessageInfos:      file_update_easy_to_borrow_list_proto_msgTypes,
	}.Build()
	File_update_easy_to_borrow_list_proto = out.File
	file_update_easy_to_borrow_list_proto_goTypes = nil
	file_update_easy_to_borrow_list_proto_depIdxs = nil
}
