// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: user_account_update.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserAccountUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    *int32                 `protobuf:"varint,154467,req,name=template_id,json=templateId" json:"template_id,omitempty"`
	UpdateType    *string                `protobuf:"bytes,154288,opt,name=update_type,json=updateType" json:"update_type,omitempty"` // add_account, modify_account, assign_account_to_user, remove_account_from_user
	AccessType    *string                `protobuf:"bytes,154000,opt,name=access_type,json=accessType" json:"access_type,omitempty"` // 0 - read_only, 1 - read_write
	SourceUserId  *string                `protobuf:"bytes,154247,opt,name=source_user_id,json=sourceUserId" json:"source_user_id,omitempty"`
	User          *string                `protobuf:"bytes,131003,opt,name=user" json:"user,omitempty"`
	FcmId         *string                `protobuf:"bytes,154013,opt,name=fcm_id,json=fcmId" json:"fcm_id,omitempty"`
	IbId          *string                `protobuf:"bytes,154014,opt,name=ib_id,json=ibId" json:"ib_id,omitempty"`
	AccountId     *string                `protobuf:"bytes,154008,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
	AccountName   *string                `protobuf:"bytes,154002,opt,name=account_name,json=accountName" json:"account_name,omitempty"`
	AccountStatus *string                `protobuf:"bytes,154003,opt,name=account_status,json=accountStatus" json:"account_status,omitempty"`
	Ssboe         *int32                 `protobuf:"varint,150100,opt,name=ssboe" json:"ssboe,omitempty"`
	Usecs         *int32                 `protobuf:"varint,150101,opt,name=usecs" json:"usecs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserAccountUpdate) Reset() {
	*x = UserAccountUpdate{}
	mi := &file_user_account_update_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserAccountUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAccountUpdate) ProtoMessage() {}

func (x *UserAccountUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_user_account_update_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAccountUpdate.ProtoReflect.Descriptor instead.
func (*UserAccountUpdate) Descriptor() ([]byte, []int) {
	return file_user_account_update_proto_rawDescGZIP(), []int{0}
}

func (x *UserAccountUpdate) GetTemplateId() int32 {
	if x != nil && x.TemplateId != nil {
		return *x.TemplateId
	}
	return 0
}

func (x *UserAccountUpdate) GetUpdateType() string {
	if x != nil && x.UpdateType != nil {
		return *x.UpdateType
	}
	return ""
}

func (x *UserAccountUpdate) GetAccessType() string {
	if x != nil && x.AccessType != nil {
		return *x.AccessType
	}
	return ""
}

func (x *UserAccountUpdate) GetSourceUserId() string {
	if x != nil && x.SourceUserId != nil {
		return *x.SourceUserId
	}
	return ""
}

func (x *UserAccountUpdate) GetUser() string {
	if x != nil && x.User != nil {
		return *x.User
	}
	return ""
}

func (x *UserAccountUpdate) GetFcmId() string {
	if x != nil && x.FcmId != nil {
		return *x.FcmId
	}
	return ""
}

func (x *UserAccountUpdate) GetIbId() string {
	if x != nil && x.IbId != nil {
		return *x.IbId
	}
	return ""
}

func (x *UserAccountUpdate) GetAccountId() string {
	if x != nil && x.AccountId != nil {
		return *x.AccountId
	}
	return ""
}

func (x *UserAccountUpdate) GetAccountName() string {
	if x != nil && x.AccountName != nil {
		return *x.AccountName
	}
	return ""
}

func (x *UserAccountUpdate) GetAccountStatus() string {
	if x != nil && x.AccountStatus != nil {
		return *x.AccountStatus
	}
	return ""
}

func (x *UserAccountUpdate) GetSsboe() int32 {
	if x != nil && x.Ssboe != nil {
		return *x.Ssboe
	}
	return 0
}

func (x *UserAccountUpdate) GetUsecs() int32 {
	if x != nil && x.Usecs != nil {
		return *x.Usecs
	}
	return 0
}

var File_user_account_update_proto protoreflect.FileDescriptor

const file_user_account_update_proto_rawDesc = "" +
	"\n" +
	"\x19user_account_update.proto\x12\x03rti\"\x89\x03\n" +
	"\x11UserAccountUpdate\x12!\n" +
	"\vtemplate_id\x18\xe3\xb6\t \x02(\x05R\n" +
	"templateId\x12!\n" +
	"\vupdate_type\x18\xb0\xb5\t \x01(\tR\n" +
	"updateType\x12!\n" +
	"\vaccess_type\x18\x90\xb3\t \x01(\tR\n" +
	"accessType\x12&\n" +
	"\x0esource_user_id\x18\x87\xb5\t \x01(\tR\fsourceUserId\x12\x14\n" +
	"\x04user\x18\xbb\xff\a \x01(\tR\x04user\x12\x17\n" +
	"\x06fcm_id\x18\x9d\xb3\t \x01(\tR\x05fcmId\x12\x15\n" +
	"\x05ib_id\x18\x9e\xb3\t \x01(\tR\x04ibId\x12\x1f\n" +
	"\n" +
	"account_id\x18\x98\xb3\t \x01(\tR\taccountId\x12#\n" +
	"\faccount_name\x18\x92\xb3\t \x01(\tR\vaccountName\x12'\n" +
	"\x0eaccount_status\x18\x93\xb3\t \x01(\tR\raccountStatus\x12\x16\n" +
	"\x05ssboe\x18Ԕ\t \x01(\x05R\x05ssboe\x12\x16\n" +
	"\x05usecs\x18Ք\t \x01(\x05R\x05usecsB\x1eZ\x1cquant/extensions/rithmic/api"

var (
	file_user_account_update_proto_rawDescOnce sync.Once
	file_user_account_update_proto_rawDescData []byte
)

func file_user_account_update_proto_rawDescGZIP() []byte {
	file_user_account_update_proto_rawDescOnce.Do(func() {
		file_user_account_update_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_account_update_proto_rawDesc), len(file_user_account_update_proto_rawDesc)))
	})
	return file_user_account_update_proto_rawDescData
}

var file_user_account_update_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_user_account_update_proto_goTypes = []any{
	(*UserAccountUpdate)(nil), // 0: rti.UserAccountUpdate
}
var file_user_account_update_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_account_update_proto_init() }
func file_user_account_update_proto_init() {
	if File_user_account_update_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_account_update_proto_rawDesc), len(file_user_account_update_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_account_update_proto_goTypes,
		DependencyIndexes: file_user_account_update_proto_depIdxs,
		MessageInfos:      file_user_account_update_proto_msgTypes,
	}.Build()
	File_user_account_update_proto = out.File
	file_user_account_update_proto_goTypes = nil
	file_user_account_update_proto_depIdxs = nil
}
