minio_root_user: "{{ lookup('env', 'MINIO_ROOT_USER') | default('quanux_admin', true) }}"
minio_root_password: "{{ lookup('env', 'MINIO_ROOT_PASSWORD') }}"
opensearch_admin_password: "{{ lookup('env', 'OPENSEARCH_ADMIN_PASSWORD') }}"
hasura_admin_secret: "{{ lookup('env', 'HASURA_ADMIN_SECRET') }}"
