.nh
.TH "QXCTL" "1" "Mar 2026" "QuanuX Hardware Bounds" "QuanuX Operator Manual"

.SH NAME
qxctl-node-deploy - Deploy the QuanuX Execution Node to a remote server via SSH


.SH SYNOPSIS
\fBqxctl node deploy [target] [flags]\fP


.SH DESCRIPTION
Deploy the QuanuX Execution Node to a remote server via SSH


.SH OPTIONS
\fB--dry-run\fP[=false]
	Print command without executing

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for deploy

.PP
\fB--hub\fP=""
	NATS Hub URL (Falls back to app trajectory by default)

.PP
\fB--token\fP=""
	Registration Token


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	Explicit config file trajectory

.PP
\fB--output\fP="text"
	Set the output UX mode (text, json, yaml, quiet)

.PP
\fB--trace\fP[=false]
	Enable extreme diagnostic observability bounds

.PP
\fB--verbose\fP[=false]
	Enable verbose payload outputs


.SH SEE ALSO
\fBqxctl-node(1)\fP
