.nh
.TH "QXCTL" "1" "Mar 2026" "QuanuX Hardware Bounds" "QuanuX Operator Manual"

.SH NAME
qxctl-ext - Manage QXP Extensions (List, Run)


.SH SYNOPSIS
\fBqxctl ext [flags]\fP


.SH DESCRIPTION
Manage QXP Extensions (List, Run)


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for ext


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	Explicit config file trajectory

.PP
\fB--hub\fP="nats://127.0.0.1:4222"
	QuanuX JetStream Engine Hub target

.PP
\fB--output\fP="text"
	Set the output UX mode (text, json, yaml, quiet)

.PP
\fB--trace\fP[=false]
	Enable extreme diagnostic observability bounds

.PP
\fB--verbose\fP[=false]
	Enable verbose payload outputs


.SH SEE ALSO
\fBqxctl(1)\fP, \fBqxctl-ext-clean(1)\fP, \fBqxctl-ext-enhance(1)\fP, \fBqxctl-ext-install(1)\fP, \fBqxctl-ext-integrate(1)\fP, \fBqxctl-ext-list(1)\fP, \fBqxctl-ext-manifest(1)\fP, \fBqxctl-ext-remove(1)\fP, \fBqxctl-ext-run(1)\fP, \fBqxctl-ext-start(1)\fP, \fBqxctl-ext-status(1)\fP, \fBqxctl-ext-stop(1)\fP, \fBqxctl-ext-uninstall(1)\fP, \fBqxctl-ext-upgrade(1)\fP, \fBqxctl-ext-upgradeable(1)\fP
