.nh
.TH "QXCTL" "1" "Mar 2026" "QuanuX Hardware Bounds" "QuanuX Operator Manual"

.SH NAME
qxctl-secrets - Manage API keys and secrets via OS Keyring natively


.SH SYNOPSIS
\fBqxctl secrets [flags]\fP


.SH DESCRIPTION
Manage API keys and secrets via OS Keyring natively


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for secrets


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	Explicit config file trajectory

.PP
\fB--hub\fP="nats://127.0.0.1:4222"
	QuanuX JetStream Engine Hub target

.PP
\fB--output\fP="text"
	Set the output UX mode (text, json, yaml, quiet)

.PP
\fB--trace\fP[=false]
	Enable extreme diagnostic observability bounds

.PP
\fB--verbose\fP[=false]
	Enable verbose payload outputs


.SH SEE ALSO
\fBqxctl(1)\fP, \fBqxctl-secrets-get(1)\fP, \fBqxctl-secrets-list-keys(1)\fP, \fBqxctl-secrets-set(1)\fP, \fBqxctl-secrets-setup(1)\fP
