.nh
.TH "QXCTL" "1" "Mar 2026" "QuanuX Hardware Bounds" "QuanuX Operator Manual"

.SH NAME
qxctl-telemetry-restart - Restart a remote telemetry service


.SH SYNOPSIS
\fBqxctl telemetry restart [flags]\fP


.SH DESCRIPTION
Restart a remote telemetry service


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for restart

.PP
\fB-n\fP, \fB--node\fP=""
	Target node hostname

.PP
\fB-s\fP, \fB--service\fP=""
	Service name: nerve or envoy


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	Explicit config file trajectory

.PP
\fB--hub\fP="nats://127.0.0.1:4222"
	QuanuX JetStream Engine Hub target

.PP
\fB--output\fP="text"
	Set the output UX mode (text, json, yaml, quiet)

.PP
\fB--trace\fP[=false]
	Enable extreme diagnostic observability bounds

.PP
\fB--verbose\fP[=false]
	Enable verbose payload outputs


.SH SEE ALSO
\fBqxctl-telemetry(1)\fP
