.nh
.TH "QXCTL" "1" "Mar 2026" "QuanuX Hardware Bounds" "QuanuX Operator Manual"

.SH NAME
qxctl-telemetry-stop - Stop a remote telemetry service


.SH SYNOPSIS
\fBqxctl telemetry stop [flags]\fP


.SH DESCRIPTION
Stop a remote telemetry service


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for stop

.PP
\fB-n\fP, \fB--node\fP=""
	Target node hostname

.PP
\fB-s\fP, \fB--service\fP=""
	Service name


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	Explicit config file trajectory

.PP
\fB--hub\fP="nats://127.0.0.1:4222"
	QuanuX JetStream Engine Hub target

.PP
\fB--output\fP="text"
	Set the output UX mode (text, json, yaml, quiet)

.PP
\fB--trace\fP[=false]
	Enable extreme diagnostic observability bounds

.PP
\fB--verbose\fP[=false]
	Enable verbose payload outputs


.SH SEE ALSO
\fBqxctl-telemetry(1)\fP
