.nh
.TH "QXCTL" "1" "Mar 2026" "QuanuX Hardware Bounds" "QuanuX Operator Manual"

.SH NAME
qxctl-vcs - Version Control System Connectors natively bound without memory leaks


.SH SYNOPSIS
\fBqxctl vcs [flags]\fP


.SH DESCRIPTION
Version Control System Connectors natively bound without memory leaks


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for vcs


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	Explicit config file trajectory

.PP
\fB--hub\fP="nats://127.0.0.1:4222"
	QuanuX JetStream Engine Hub target

.PP
\fB--output\fP="text"
	Set the output UX mode (text, json, yaml, quiet)

.PP
\fB--trace\fP[=false]
	Enable extreme diagnostic observability bounds

.PP
\fB--verbose\fP[=false]
	Enable verbose payload outputs


.SH SEE ALSO
\fBqxctl(1)\fP, \fBqxctl-vcs-clone(1)\fP, \fBqxctl-vcs-commit(1)\fP, \fBqxctl-vcs-connect(1)\fP, \fBqxctl-vcs-publish(1)\fP, \fBqxctl-vcs-push(1)\fP, \fBqxctl-vcs-setup(1)\fP, \fBqxctl-vcs-status(1)\fP, \fBqxctl-vcs-sync(1)\fP
