.nh
.TH "QXCTL" "1" "Mar 2026" "QuanuX Hardware Bounds" "QuanuX Operator Manual"

.SH NAME
qxctl-vcs-clone - Clone a remote repository


.SH SYNOPSIS
\fBqxctl vcs clone [url] [flags]\fP


.SH DESCRIPTION
Clone a remote repository


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for clone

.PP
\fB--target\fP=""
	Target directory name


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	Explicit config file trajectory

.PP
\fB--hub\fP="nats://127.0.0.1:4222"
	QuanuX JetStream Engine Hub target

.PP
\fB--output\fP="text"
	Set the output UX mode (text, json, yaml, quiet)

.PP
\fB--trace\fP[=false]
	Enable extreme diagnostic observability bounds

.PP
\fB--verbose\fP[=false]
	Enable verbose payload outputs


.SH SEE ALSO
\fBqxctl-vcs(1)\fP
