/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface EventEnvelope {
  event_type: string;
  sequence: number;
  correlation_id: string;
  source: string;
  timestamp: string;
  payload: {
    [k: string]: unknown;
  };
}
