# generated by datamodel-codegen:
#   filename:  trading/order_request.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import AwareDatetime, BaseModel, ConfigDict, confloat


class Side(Enum):
    BUY = 'BUY'
    SELL = 'SELL'


class Type(Enum):
    MARKET = 'MARKET'
    LIMIT = 'LIMIT'
    STOP = 'STOP'
    STOP_LIMIT = 'STOP_LIMIT'


class TimeInForce(Enum):
    DAY = 'DAY'
    GTC = 'GTC'
    IOC = 'IOC'
    FOK = 'FOK'


class OrderRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    symbol: str
    exchange: str | None = None
    side: Side
    type: Type
    price: float | None = None
    stop_price: float | None = None
    time_in_force: TimeInForce
    quantity: confloat(ge=0.0)
    client_order_id: str
    flags: dict[str, Any] | None = None
    """
    vendor-specific flags (adapter-local)
    """
    idempotency_key: str | None = None
    timestamp: AwareDatetime | None = None
