# generated by datamodel-codegen:
#   filename:  trading/precision.schema.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, PositiveFloat


class InstrumentPrecision(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    symbol: str
    price_tick: PositiveFloat
    quantity_step: PositiveFloat
    multiplier: float | None = None
    decimals: int | None = None
