// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: account_pnl_position_update.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountPnLPositionUpdate struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	TemplateId                  *int32                 `protobuf:"varint,154467,req,name=template_id,json=templateId" json:"template_id,omitempty"`
	IsSnapshot                  *bool                  `protobuf:"varint,110121,opt,name=is_snapshot,json=isSnapshot" json:"is_snapshot,omitempty"`
	FcmId                       *string                `protobuf:"bytes,154013,opt,name=fcm_id,json=fcmId" json:"fcm_id,omitempty"`
	IbId                        *string                `protobuf:"bytes,154014,opt,name=ib_id,json=ibId" json:"ib_id,omitempty"`
	AccountId                   *string                `protobuf:"bytes,154008,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
	FillBuyQty                  *int32                 `protobuf:"varint,154041,opt,name=fill_buy_qty,json=fillBuyQty" json:"fill_buy_qty,omitempty"`
	FillSellQty                 *int32                 `protobuf:"varint,154042,opt,name=fill_sell_qty,json=fillSellQty" json:"fill_sell_qty,omitempty"`
	OrderBuyQty                 *int32                 `protobuf:"varint,154037,opt,name=order_buy_qty,json=orderBuyQty" json:"order_buy_qty,omitempty"`
	OrderSellQty                *int32                 `protobuf:"varint,154038,opt,name=order_sell_qty,json=orderSellQty" json:"order_sell_qty,omitempty"`
	BuyQty                      *int32                 `protobuf:"varint,154260,opt,name=buy_qty,json=buyQty" json:"buy_qty,omitempty"`
	SellQty                     *int32                 `protobuf:"varint,154261,opt,name=sell_qty,json=sellQty" json:"sell_qty,omitempty"`
	OpenLongOptionsValue        *string                `protobuf:"bytes,157105,opt,name=open_long_options_value,json=openLongOptionsValue" json:"open_long_options_value,omitempty"`
	OpenShortOptionsValue       *string                `protobuf:"bytes,157106,opt,name=open_short_options_value,json=openShortOptionsValue" json:"open_short_options_value,omitempty"`
	ClosedOptionsValue          *string                `protobuf:"bytes,157107,opt,name=closed_options_value,json=closedOptionsValue" json:"closed_options_value,omitempty"`
	OptionCashReserved          *string                `protobuf:"bytes,157111,opt,name=option_cash_reserved,json=optionCashReserved" json:"option_cash_reserved,omitempty"`
	RmsAccountCommission        *string                `protobuf:"bytes,157113,opt,name=rms_account_commission,json=rmsAccountCommission" json:"rms_account_commission,omitempty"`
	OpenPositionPnl             *string                `protobuf:"bytes,156961,opt,name=open_position_pnl,json=openPositionPnl" json:"open_position_pnl,omitempty"`
	OpenPositionQuantity        *int32                 `protobuf:"varint,156962,opt,name=open_position_quantity,json=openPositionQuantity" json:"open_position_quantity,omitempty"`
	ClosedPositionPnl           *string                `protobuf:"bytes,156963,opt,name=closed_position_pnl,json=closedPositionPnl" json:"closed_position_pnl,omitempty"`
	ClosedPositionQuantity      *int32                 `protobuf:"varint,156964,opt,name=closed_position_quantity,json=closedPositionQuantity" json:"closed_position_quantity,omitempty"`
	NetQuantity                 *int32                 `protobuf:"varint,156967,opt,name=net_quantity,json=netQuantity" json:"net_quantity,omitempty"`
	ExcessBuyMargin             *string                `protobuf:"bytes,156991,opt,name=excess_buy_margin,json=excessBuyMargin" json:"excess_buy_margin,omitempty"`
	MarginBalance               *string                `protobuf:"bytes,156977,opt,name=margin_balance,json=marginBalance" json:"margin_balance,omitempty"`
	MinMarginBalance            *string                `protobuf:"bytes,156976,opt,name=min_margin_balance,json=minMarginBalance" json:"min_margin_balance,omitempty"`
	MinAccountBalance           *string                `protobuf:"bytes,156968,opt,name=min_account_balance,json=minAccountBalance" json:"min_account_balance,omitempty"`
	AccountBalance              *string                `protobuf:"bytes,156970,opt,name=account_balance,json=accountBalance" json:"account_balance,omitempty"`
	CashOnHand                  *string                `protobuf:"bytes,156971,opt,name=cash_on_hand,json=cashOnHand" json:"cash_on_hand,omitempty"`
	OptionClosedPnl             *string                `protobuf:"bytes,157118,opt,name=option_closed_pnl,json=optionClosedPnl" json:"option_closed_pnl,omitempty"`
	PercentMaximumAllowableLoss *string                `protobuf:"bytes,156965,opt,name=percent_maximum_allowable_loss,json=percentMaximumAllowableLoss" json:"percent_maximum_allowable_loss,omitempty"`
	OptionOpenPnl               *string                `protobuf:"bytes,157117,opt,name=option_open_pnl,json=optionOpenPnl" json:"option_open_pnl,omitempty"`
	MtmAccount                  *string                `protobuf:"bytes,154262,opt,name=mtm_account,json=mtmAccount" json:"mtm_account,omitempty"`
	AvailableBuyingPower        *string                `protobuf:"bytes,157015,opt,name=available_buying_power,json=availableBuyingPower" json:"available_buying_power,omitempty"`
	UsedBuyingPower             *string                `protobuf:"bytes,157014,opt,name=used_buying_power,json=usedBuyingPower" json:"used_buying_power,omitempty"`
	ReservedBuyingPower         *string                `protobuf:"bytes,157013,opt,name=reserved_buying_power,json=reservedBuyingPower" json:"reserved_buying_power,omitempty"`
	ExcessSellMargin            *string                `protobuf:"bytes,156992,opt,name=excess_sell_margin,json=excessSellMargin" json:"excess_sell_margin,omitempty"`
	DayOpenPnl                  *string                `protobuf:"bytes,157954,opt,name=day_open_pnl,json=dayOpenPnl" json:"day_open_pnl,omitempty"`
	DayClosedPnl                *string                `protobuf:"bytes,157955,opt,name=day_closed_pnl,json=dayClosedPnl" json:"day_closed_pnl,omitempty"`
	DayPnl                      *string                `protobuf:"bytes,157956,opt,name=day_pnl,json=dayPnl" json:"day_pnl,omitempty"`
	DayOpenPnlOffset            *string                `protobuf:"bytes,157957,opt,name=day_open_pnl_offset,json=dayOpenPnlOffset" json:"day_open_pnl_offset,omitempty"`
	DayClosedPnlOffset          *string                `protobuf:"bytes,157958,opt,name=day_closed_pnl_offset,json=dayClosedPnlOffset" json:"day_closed_pnl_offset,omitempty"`
	Ssboe                       *int32                 `protobuf:"varint,150100,opt,name=ssboe" json:"ssboe,omitempty"`
	Usecs                       *int32                 `protobuf:"varint,150101,opt,name=usecs" json:"usecs,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *AccountPnLPositionUpdate) Reset() {
	*x = AccountPnLPositionUpdate{}
	mi := &file_account_pnl_position_update_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountPnLPositionUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountPnLPositionUpdate) ProtoMessage() {}

func (x *AccountPnLPositionUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_account_pnl_position_update_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountPnLPositionUpdate.ProtoReflect.Descriptor instead.
func (*AccountPnLPositionUpdate) Descriptor() ([]byte, []int) {
	return file_account_pnl_position_update_proto_rawDescGZIP(), []int{0}
}

func (x *AccountPnLPositionUpdate) GetTemplateId() int32 {
	if x != nil && x.TemplateId != nil {
		return *x.TemplateId
	}
	return 0
}

func (x *AccountPnLPositionUpdate) GetIsSnapshot() bool {
	if x != nil && x.IsSnapshot != nil {
		return *x.IsSnapshot
	}
	return false
}

func (x *AccountPnLPositionUpdate) GetFcmId() string {
	if x != nil && x.FcmId != nil {
		return *x.FcmId
	}
	return ""
}

func (x *AccountPnLPositionUpdate) GetIbId() string {
	if x != nil && x.IbId != nil {
		return *x.IbId
	}
	return ""
}

func (x *AccountPnLPositionUpdate) GetAccountId() string {
	if x != nil && x.AccountId != nil {
		return *x.AccountId
	}
	return ""
}

func (x *AccountPnLPositionUpdate) GetFillBuyQty() int32 {
	if x != nil && x.FillBuyQty != nil {
		return *x.FillBuyQty
	}
	return 0
}

func (x *AccountPnLPositionUpdate) GetFillSellQty() int32 {
	if x != nil && x.FillSellQty != nil {
		return *x.FillSellQty
	}
	return 0
}

func (x *AccountPnLPositionUpdate) GetOrderBuyQty() int32 {
	if x != nil && x.OrderBuyQty != nil {
		return *x.OrderBuyQty
	}
	return 0
}

func (x *AccountPnLPositionUpdate) GetOrderSellQty() int32 {
	if x != nil && x.OrderSellQty != nil {
		return *x.OrderSellQty
	}
	return 0
}

func (x *AccountPnLPositionUpdate) GetBuyQty() int32 {
	if x != nil && x.BuyQty != nil {
		return *x.BuyQty
	}
	return 0
}

func (x *AccountPnLPositionUpdate) GetSellQty() int32 {
	if x != nil && x.SellQty != nil {
		return *x.SellQty
	}
	return 0
}

func (x *AccountPnLPositionUpdate) GetOpenLongOptionsValue() string {
	if x != nil && x.OpenLongOptionsValue != nil {
		return *x.OpenLongOptionsValue
	}
	return ""
}

func (x *AccountPnLPositionUpdate) GetOpenShortOptionsValue() string {
	if x != nil && x.OpenShortOptionsValue != nil {
		return *x.OpenShortOptionsValue
	}
	return ""
}

func (x *AccountPnLPositionUpdate) GetClosedOptionsValue() string {
	if x != nil && x.ClosedOptionsValue != nil {
		return *x.ClosedOptionsValue
	}
	return ""
}

func (x *AccountPnLPositionUpdate) GetOptionCashReserved() string {
	if x != nil && x.OptionCashReserved != nil {
		return *x.OptionCashReserved
	}
	return ""
}

func (x *AccountPnLPositionUpdate) GetRmsAccountCommission() string {
	if x != nil && x.RmsAccountCommission != nil {
		return *x.RmsAccountCommission
	}
	return ""
}

func (x *AccountPnLPositionUpdate) GetOpenPositionPnl() string {
	if x != nil && x.OpenPositionPnl != nil {
		return *x.OpenPositionPnl
	}
	return ""
}

func (x *AccountPnLPositionUpdate) GetOpenPositionQuantity() int32 {
	if x != nil && x.OpenPositionQuantity != nil {
		return *x.OpenPositionQuantity
	}
	return 0
}

func (x *AccountPnLPositionUpdate) GetClosedPositionPnl() string {
	if x != nil && x.ClosedPositionPnl != nil {
		return *x.ClosedPositionPnl
	}
	return ""
}

func (x *AccountPnLPositionUpdate) GetClosedPositionQuantity() int32 {
	if x != nil && x.ClosedPositionQuantity != nil {
		return *x.ClosedPositionQuantity
	}
	return 0
}

func (x *AccountPnLPositionUpdate) GetNetQuantity() int32 {
	if x != nil && x.NetQuantity != nil {
		return *x.NetQuantity
	}
	return 0
}

func (x *AccountPnLPositionUpdate) GetExcessBuyMargin() string {
	if x != nil && x.ExcessBuyMargin != nil {
		return *x.ExcessBuyMargin
	}
	return ""
}

func (x *AccountPnLPositionUpdate) GetMarginBalance() string {
	if x != nil && x.MarginBalance != nil {
		return *x.MarginBalance
	}
	return ""
}

func (x *AccountPnLPositionUpdate) GetMinMarginBalance() string {
	if x != nil && x.MinMarginBalance != nil {
		return *x.MinMarginBalance
	}
	return ""
}

func (x *AccountPnLPositionUpdate) GetMinAccountBalance() string {
	if x != nil && x.MinAccountBalance != nil {
		return *x.MinAccountBalance
	}
	return ""
}

func (x *AccountPnLPositionUpdate) GetAccountBalance() string {
	if x != nil && x.AccountBalance != nil {
		return *x.AccountBalance
	}
	return ""
}

func (x *AccountPnLPositionUpdate) GetCashOnHand() string {
	if x != nil && x.CashOnHand != nil {
		return *x.CashOnHand
	}
	return ""
}

func (x *AccountPnLPositionUpdate) GetOptionClosedPnl() string {
	if x != nil && x.OptionClosedPnl != nil {
		return *x.OptionClosedPnl
	}
	return ""
}

func (x *AccountPnLPositionUpdate) GetPercentMaximumAllowableLoss() string {
	if x != nil && x.PercentMaximumAllowableLoss != nil {
		return *x.PercentMaximumAllowableLoss
	}
	return ""
}

func (x *AccountPnLPositionUpdate) GetOptionOpenPnl() string {
	if x != nil && x.OptionOpenPnl != nil {
		return *x.OptionOpenPnl
	}
	return ""
}

func (x *AccountPnLPositionUpdate) GetMtmAccount() string {
	if x != nil && x.MtmAccount != nil {
		return *x.MtmAccount
	}
	return ""
}

func (x *AccountPnLPositionUpdate) GetAvailableBuyingPower() string {
	if x != nil && x.AvailableBuyingPower != nil {
		return *x.AvailableBuyingPower
	}
	return ""
}

func (x *AccountPnLPositionUpdate) GetUsedBuyingPower() string {
	if x != nil && x.UsedBuyingPower != nil {
		return *x.UsedBuyingPower
	}
	return ""
}

func (x *AccountPnLPositionUpdate) GetReservedBuyingPower() string {
	if x != nil && x.ReservedBuyingPower != nil {
		return *x.ReservedBuyingPower
	}
	return ""
}

func (x *AccountPnLPositionUpdate) GetExcessSellMargin() string {
	if x != nil && x.ExcessSellMargin != nil {
		return *x.ExcessSellMargin
	}
	return ""
}

func (x *AccountPnLPositionUpdate) GetDayOpenPnl() string {
	if x != nil && x.DayOpenPnl != nil {
		return *x.DayOpenPnl
	}
	return ""
}

func (x *AccountPnLPositionUpdate) GetDayClosedPnl() string {
	if x != nil && x.DayClosedPnl != nil {
		return *x.DayClosedPnl
	}
	return ""
}

func (x *AccountPnLPositionUpdate) GetDayPnl() string {
	if x != nil && x.DayPnl != nil {
		return *x.DayPnl
	}
	return ""
}

func (x *AccountPnLPositionUpdate) GetDayOpenPnlOffset() string {
	if x != nil && x.DayOpenPnlOffset != nil {
		return *x.DayOpenPnlOffset
	}
	return ""
}

func (x *AccountPnLPositionUpdate) GetDayClosedPnlOffset() string {
	if x != nil && x.DayClosedPnlOffset != nil {
		return *x.DayClosedPnlOffset
	}
	return ""
}

func (x *AccountPnLPositionUpdate) GetSsboe() int32 {
	if x != nil && x.Ssboe != nil {
		return *x.Ssboe
	}
	return 0
}

func (x *AccountPnLPositionUpdate) GetUsecs() int32 {
	if x != nil && x.Usecs != nil {
		return *x.Usecs
	}
	return 0
}

var File_account_pnl_position_update_proto protoreflect.FileDescriptor

const file_account_pnl_position_update_proto_rawDesc = "" +
	"\n" +
	"!account_pnl_position_update.proto\x12\x03rti\"\xa1\x0e\n" +
	"\x18AccountPnLPositionUpdate\x12!\n" +
	"\vtemplate_id\x18\xe3\xb6\t \x02(\x05R\n" +
	"templateId\x12!\n" +
	"\vis_snapshot\x18\xa9\xdc\x06 \x01(\bR\n" +
	"isSnapshot\x12\x17\n" +
	"\x06fcm_id\x18\x9d\xb3\t \x01(\tR\x05fcmId\x12\x15\n" +
	"\x05ib_id\x18\x9e\xb3\t \x01(\tR\x04ibId\x12\x1f\n" +
	"\n" +
	"account_id\x18\x98\xb3\t \x01(\tR\taccountId\x12\"\n" +
	"\ffill_buy_qty\x18\xb9\xb3\t \x01(\x05R\n" +
	"fillBuyQty\x12$\n" +
	"\rfill_sell_qty\x18\xba\xb3\t \x01(\x05R\vfillSellQty\x12$\n" +
	"\rorder_buy_qty\x18\xb5\xb3\t \x01(\x05R\vorderBuyQty\x12&\n" +
	"\x0eorder_sell_qty\x18\xb6\xb3\t \x01(\x05R\forderSellQty\x12\x19\n" +
	"\abuy_qty\x18\x94\xb5\t \x01(\x05R\x06buyQty\x12\x1b\n" +
	"\bsell_qty\x18\x95\xb5\t \x01(\x05R\asellQty\x127\n" +
	"\x17open_long_options_value\x18\xb1\xcb\t \x01(\tR\x14openLongOptionsValue\x129\n" +
	"\x18open_short_options_value\x18\xb2\xcb\t \x01(\tR\x15openShortOptionsValue\x122\n" +
	"\x14closed_options_value\x18\xb3\xcb\t \x01(\tR\x12closedOptionsValue\x122\n" +
	"\x14option_cash_reserved\x18\xb7\xcb\t \x01(\tR\x12optionCashReserved\x126\n" +
	"\x16rms_account_commission\x18\xb9\xcb\t \x01(\tR\x14rmsAccountCommission\x12,\n" +
	"\x11open_position_pnl\x18\xa1\xca\t \x01(\tR\x0fopenPositionPnl\x126\n" +
	"\x16open_position_quantity\x18\xa2\xca\t \x01(\x05R\x14openPositionQuantity\x120\n" +
	"\x13closed_position_pnl\x18\xa3\xca\t \x01(\tR\x11closedPositionPnl\x12:\n" +
	"\x18closed_position_quantity\x18\xa4\xca\t \x01(\x05R\x16closedPositionQuantity\x12#\n" +
	"\fnet_quantity\x18\xa7\xca\t \x01(\x05R\vnetQuantity\x12,\n" +
	"\x11excess_buy_margin\x18\xbf\xca\t \x01(\tR\x0fexcessBuyMargin\x12'\n" +
	"\x0emargin_balance\x18\xb1\xca\t \x01(\tR\rmarginBalance\x12.\n" +
	"\x12min_margin_balance\x18\xb0\xca\t \x01(\tR\x10minMarginBalance\x120\n" +
	"\x13min_account_balance\x18\xa8\xca\t \x01(\tR\x11minAccountBalance\x12)\n" +
	"\x0faccount_balance\x18\xaa\xca\t \x01(\tR\x0eaccountBalance\x12\"\n" +
	"\fcash_on_hand\x18\xab\xca\t \x01(\tR\n" +
	"cashOnHand\x12,\n" +
	"\x11option_closed_pnl\x18\xbe\xcb\t \x01(\tR\x0foptionClosedPnl\x12E\n" +
	"\x1epercent_maximum_allowable_loss\x18\xa5\xca\t \x01(\tR\x1bpercentMaximumAllowableLoss\x12(\n" +
	"\x0foption_open_pnl\x18\xbd\xcb\t \x01(\tR\roptionOpenPnl\x12!\n" +
	"\vmtm_account\x18\x96\xb5\t \x01(\tR\n" +
	"mtmAccount\x126\n" +
	"\x16available_buying_power\x18\xd7\xca\t \x01(\tR\x14availableBuyingPower\x12,\n" +
	"\x11used_buying_power\x18\xd6\xca\t \x01(\tR\x0fusedBuyingPower\x124\n" +
	"\x15reserved_buying_power\x18\xd5\xca\t \x01(\tR\x13reservedBuyingPower\x12.\n" +
	"\x12excess_sell_margin\x18\xc0\xca\t \x01(\tR\x10excessSellMargin\x12\"\n" +
	"\fday_open_pnl\x18\x82\xd2\t \x01(\tR\n" +
	"dayOpenPnl\x12&\n" +
	"\x0eday_closed_pnl\x18\x83\xd2\t \x01(\tR\fdayClosedPnl\x12\x19\n" +
	"\aday_pnl\x18\x84\xd2\t \x01(\tR\x06dayPnl\x12/\n" +
	"\x13day_open_pnl_offset\x18\x85\xd2\t \x01(\tR\x10dayOpenPnlOffset\x123\n" +
	"\x15day_closed_pnl_offset\x18\x86\xd2\t \x01(\tR\x12dayClosedPnlOffset\x12\x16\n" +
	"\x05ssboe\x18Ԕ\t \x01(\x05R\x05ssboe\x12\x16\n" +
	"\x05usecs\x18Ք\t \x01(\x05R\x05usecsB\x1eZ\x1cquant/extensions/rithmic/api"

var (
	file_account_pnl_position_update_proto_rawDescOnce sync.Once
	file_account_pnl_position_update_proto_rawDescData []byte
)

func file_account_pnl_position_update_proto_rawDescGZIP() []byte {
	file_account_pnl_position_update_proto_rawDescOnce.Do(func() {
		file_account_pnl_position_update_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_pnl_position_update_proto_rawDesc), len(file_account_pnl_position_update_proto_rawDesc)))
	})
	return file_account_pnl_position_update_proto_rawDescData
}

var file_account_pnl_position_update_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_account_pnl_position_update_proto_goTypes = []any{
	(*AccountPnLPositionUpdate)(nil), // 0: rti.AccountPnLPositionUpdate
}
var file_account_pnl_position_update_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_account_pnl_position_update_proto_init() }
func file_account_pnl_position_update_proto_init() {
	if File_account_pnl_position_update_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_pnl_position_update_proto_rawDesc), len(file_account_pnl_position_update_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_account_pnl_position_update_proto_goTypes,
		DependencyIndexes: file_account_pnl_position_update_proto_depIdxs,
		MessageInfos:      file_account_pnl_position_update_proto_msgTypes,
	}.Build()
	File_account_pnl_position_update_proto = out.File
	file_account_pnl_position_update_proto_goTypes = nil
	file_account_pnl_position_update_proto_depIdxs = nil
}
