// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: account_rms_updates.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountRmsUpdates_UpdateBits int32

const (
	AccountRmsUpdates_AUTO_LIQ_THRESHOLD_CURRENT_VALUE AccountRmsUpdates_UpdateBits = 1
)

// Enum value maps for AccountRmsUpdates_UpdateBits.
var (
	AccountRmsUpdates_UpdateBits_name = map[int32]string{
		1: "AUTO_LIQ_THRESHOLD_CURRENT_VALUE",
	}
	AccountRmsUpdates_UpdateBits_value = map[string]int32{
		"AUTO_LIQ_THRESHOLD_CURRENT_VALUE": 1,
	}
)

func (x AccountRmsUpdates_UpdateBits) Enum() *AccountRmsUpdates_UpdateBits {
	p := new(AccountRmsUpdates_UpdateBits)
	*p = x
	return p
}

func (x AccountRmsUpdates_UpdateBits) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountRmsUpdates_UpdateBits) Descriptor() protoreflect.EnumDescriptor {
	return file_account_rms_updates_proto_enumTypes[0].Descriptor()
}

func (AccountRmsUpdates_UpdateBits) Type() protoreflect.EnumType {
	return &file_account_rms_updates_proto_enumTypes[0]
}

func (x AccountRmsUpdates_UpdateBits) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *AccountRmsUpdates_UpdateBits) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = AccountRmsUpdates_UpdateBits(num)
	return nil
}

// Deprecated: Use AccountRmsUpdates_UpdateBits.Descriptor instead.
func (AccountRmsUpdates_UpdateBits) EnumDescriptor() ([]byte, []int) {
	return file_account_rms_updates_proto_rawDescGZIP(), []int{0, 0}
}

type AccountRmsUpdates struct {
	state                          protoimpl.MessageState `protogen:"open.v1"`
	TemplateId                     *int32                 `protobuf:"varint,154467,req,name=template_id,json=templateId" json:"template_id,omitempty"`
	UpdateBits                     *int32                 `protobuf:"varint,154211,opt,name=update_bits,json=updateBits" json:"update_bits,omitempty"`
	FcmId                          *string                `protobuf:"bytes,154013,opt,name=fcm_id,json=fcmId" json:"fcm_id,omitempty"`
	IbId                           *string                `protobuf:"bytes,154014,opt,name=ib_id,json=ibId" json:"ib_id,omitempty"`
	AccountId                      *string                `protobuf:"bytes,154008,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
	AutoLiqThresholdCurrentValue   *string                `protobuf:"bytes,131040,opt,name=auto_liq_threshold_current_value,json=autoLiqThresholdCurrentValue" json:"auto_liq_threshold_current_value,omitempty"`
	AutoLiqPeakAccountBalance      *string                `protobuf:"bytes,131049,opt,name=auto_liq_peak_account_balance,json=autoLiqPeakAccountBalance" json:"auto_liq_peak_account_balance,omitempty"`
	AutoLiqPeakAccountBalanceSsboe *string                `protobuf:"bytes,131050,opt,name=auto_liq_peak_account_balance_ssboe,json=autoLiqPeakAccountBalanceSsboe" json:"auto_liq_peak_account_balance_ssboe,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *AccountRmsUpdates) Reset() {
	*x = AccountRmsUpdates{}
	mi := &file_account_rms_updates_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountRmsUpdates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountRmsUpdates) ProtoMessage() {}

func (x *AccountRmsUpdates) ProtoReflect() protoreflect.Message {
	mi := &file_account_rms_updates_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountRmsUpdates.ProtoReflect.Descriptor instead.
func (*AccountRmsUpdates) Descriptor() ([]byte, []int) {
	return file_account_rms_updates_proto_rawDescGZIP(), []int{0}
}

func (x *AccountRmsUpdates) GetTemplateId() int32 {
	if x != nil && x.TemplateId != nil {
		return *x.TemplateId
	}
	return 0
}

func (x *AccountRmsUpdates) GetUpdateBits() int32 {
	if x != nil && x.UpdateBits != nil {
		return *x.UpdateBits
	}
	return 0
}

func (x *AccountRmsUpdates) GetFcmId() string {
	if x != nil && x.FcmId != nil {
		return *x.FcmId
	}
	return ""
}

func (x *AccountRmsUpdates) GetIbId() string {
	if x != nil && x.IbId != nil {
		return *x.IbId
	}
	return ""
}

func (x *AccountRmsUpdates) GetAccountId() string {
	if x != nil && x.AccountId != nil {
		return *x.AccountId
	}
	return ""
}

func (x *AccountRmsUpdates) GetAutoLiqThresholdCurrentValue() string {
	if x != nil && x.AutoLiqThresholdCurrentValue != nil {
		return *x.AutoLiqThresholdCurrentValue
	}
	return ""
}

func (x *AccountRmsUpdates) GetAutoLiqPeakAccountBalance() string {
	if x != nil && x.AutoLiqPeakAccountBalance != nil {
		return *x.AutoLiqPeakAccountBalance
	}
	return ""
}

func (x *AccountRmsUpdates) GetAutoLiqPeakAccountBalanceSsboe() string {
	if x != nil && x.AutoLiqPeakAccountBalanceSsboe != nil {
		return *x.AutoLiqPeakAccountBalanceSsboe
	}
	return ""
}

var File_account_rms_updates_proto protoreflect.FileDescriptor

const file_account_rms_updates_proto_rawDesc = "" +
	"\n" +
	"\x19account_rms_updates.proto\x12\x03rti\"\xbb\x03\n" +
	"\x11AccountRmsUpdates\x12!\n" +
	"\vtemplate_id\x18\xe3\xb6\t \x02(\x05R\n" +
	"templateId\x12!\n" +
	"\vupdate_bits\x18\xe3\xb4\t \x01(\x05R\n" +
	"updateBits\x12\x17\n" +
	"\x06fcm_id\x18\x9d\xb3\t \x01(\tR\x05fcmId\x12\x15\n" +
	"\x05ib_id\x18\x9e\xb3\t \x01(\tR\x04ibId\x12\x1f\n" +
	"\n" +
	"account_id\x18\x98\xb3\t \x01(\tR\taccountId\x12H\n" +
	" auto_liq_threshold_current_value\x18\xe0\xff\a \x01(\tR\x1cautoLiqThresholdCurrentValue\x12B\n" +
	"\x1dauto_liq_peak_account_balance\x18\xe9\xff\a \x01(\tR\x19autoLiqPeakAccountBalance\x12M\n" +
	"#auto_liq_peak_account_balance_ssboe\x18\xea\xff\a \x01(\tR\x1eautoLiqPeakAccountBalanceSsboe\"2\n" +
	"\n" +
	"UpdateBits\x12$\n" +
	" AUTO_LIQ_THRESHOLD_CURRENT_VALUE\x10\x01B\x1eZ\x1cquant/extensions/rithmic/api"

var (
	file_account_rms_updates_proto_rawDescOnce sync.Once
	file_account_rms_updates_proto_rawDescData []byte
)

func file_account_rms_updates_proto_rawDescGZIP() []byte {
	file_account_rms_updates_proto_rawDescOnce.Do(func() {
		file_account_rms_updates_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_rms_updates_proto_rawDesc), len(file_account_rms_updates_proto_rawDesc)))
	})
	return file_account_rms_updates_proto_rawDescData
}

var file_account_rms_updates_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_account_rms_updates_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_account_rms_updates_proto_goTypes = []any{
	(AccountRmsUpdates_UpdateBits)(0), // 0: rti.AccountRmsUpdates.UpdateBits
	(*AccountRmsUpdates)(nil),         // 1: rti.AccountRmsUpdates
}
var file_account_rms_updates_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_account_rms_updates_proto_init() }
func file_account_rms_updates_proto_init() {
	if File_account_rms_updates_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_rms_updates_proto_rawDesc), len(file_account_rms_updates_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_account_rms_updates_proto_goTypes,
		DependencyIndexes: file_account_rms_updates_proto_depIdxs,
		EnumInfos:         file_account_rms_updates_proto_enumTypes,
		MessageInfos:      file_account_rms_updates_proto_msgTypes,
	}.Build()
	File_account_rms_updates_proto = out.File
	file_account_rms_updates_proto_goTypes = nil
	file_account_rms_updates_proto_depIdxs = nil
}
