// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: indicator_prices.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// below enum is just for reference only, not used in this message
type IndicatorPrices_PresenceBits int32

const (
	IndicatorPrices_OPENING_INDICATOR IndicatorPrices_PresenceBits = 1
	IndicatorPrices_CLOSING_INDICATOR IndicatorPrices_PresenceBits = 2
)

// Enum value maps for IndicatorPrices_PresenceBits.
var (
	IndicatorPrices_PresenceBits_name = map[int32]string{
		1: "OPENING_INDICATOR",
		2: "CLOSING_INDICATOR",
	}
	IndicatorPrices_PresenceBits_value = map[string]int32{
		"OPENING_INDICATOR": 1,
		"CLOSING_INDICATOR": 2,
	}
)

func (x IndicatorPrices_PresenceBits) Enum() *IndicatorPrices_PresenceBits {
	p := new(IndicatorPrices_PresenceBits)
	*p = x
	return p
}

func (x IndicatorPrices_PresenceBits) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IndicatorPrices_PresenceBits) Descriptor() protoreflect.EnumDescriptor {
	return file_indicator_prices_proto_enumTypes[0].Descriptor()
}

func (IndicatorPrices_PresenceBits) Type() protoreflect.EnumType {
	return &file_indicator_prices_proto_enumTypes[0]
}

func (x IndicatorPrices_PresenceBits) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *IndicatorPrices_PresenceBits) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = IndicatorPrices_PresenceBits(num)
	return nil
}

// Deprecated: Use IndicatorPrices_PresenceBits.Descriptor instead.
func (IndicatorPrices_PresenceBits) EnumDescriptor() ([]byte, []int) {
	return file_indicator_prices_proto_rawDescGZIP(), []int{0, 0}
}

type IndicatorPrices struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TemplateId       *int32                 `protobuf:"varint,154467,req,name=template_id,json=templateId" json:"template_id,omitempty"`                    // PB_OFFSET + MNM_TEMPLATE_ID
	Symbol           *string                `protobuf:"bytes,110100,opt,name=symbol" json:"symbol,omitempty"`                                               // PB_OFFSET + MNM_SYMBOL
	Exchange         *string                `protobuf:"bytes,110101,opt,name=exchange" json:"exchange,omitempty"`                                           // PB_OFFSET + MNM_EXCHANGE
	PresenceBits     *uint32                `protobuf:"varint,149138,opt,name=presence_bits,json=presenceBits" json:"presence_bits,omitempty"`              // PB_OFFSET + MNM_PRICING_INDICATOR
	ClearBits        *uint32                `protobuf:"varint,154571,opt,name=clear_bits,json=clearBits" json:"clear_bits,omitempty"`                       // PB_OFFSET + MNM_DISPLAY_INDICATOR
	IsSnapshot       *bool                  `protobuf:"varint,110121,opt,name=is_snapshot,json=isSnapshot" json:"is_snapshot,omitempty"`                    // PB_OFFSET + MNM_UPDATE_TYPE
	OpeningIndicator *float64               `protobuf:"fixed64,154522,opt,name=opening_indicator,json=openingIndicator" json:"opening_indicator,omitempty"` // PB_OFFSET + MNM_OPENING_INDICATOR
	ClosingIndicator *float64               `protobuf:"fixed64,154064,opt,name=closing_indicator,json=closingIndicator" json:"closing_indicator,omitempty"` // PB_OFFSET + MNM_CLOSING_INDICATOR
	Ssboe            *int32                 `protobuf:"varint,150100,opt,name=ssboe" json:"ssboe,omitempty"`                                                // PB_OFFSET + MNM_SECONDS_SINCE_BOE
	Usecs            *int32                 `protobuf:"varint,150101,opt,name=usecs" json:"usecs,omitempty"`                                                // PB_OFFSET + MNM_USECS
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *IndicatorPrices) Reset() {
	*x = IndicatorPrices{}
	mi := &file_indicator_prices_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IndicatorPrices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IndicatorPrices) ProtoMessage() {}

func (x *IndicatorPrices) ProtoReflect() protoreflect.Message {
	mi := &file_indicator_prices_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IndicatorPrices.ProtoReflect.Descriptor instead.
func (*IndicatorPrices) Descriptor() ([]byte, []int) {
	return file_indicator_prices_proto_rawDescGZIP(), []int{0}
}

func (x *IndicatorPrices) GetTemplateId() int32 {
	if x != nil && x.TemplateId != nil {
		return *x.TemplateId
	}
	return 0
}

func (x *IndicatorPrices) GetSymbol() string {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return ""
}

func (x *IndicatorPrices) GetExchange() string {
	if x != nil && x.Exchange != nil {
		return *x.Exchange
	}
	return ""
}

func (x *IndicatorPrices) GetPresenceBits() uint32 {
	if x != nil && x.PresenceBits != nil {
		return *x.PresenceBits
	}
	return 0
}

func (x *IndicatorPrices) GetClearBits() uint32 {
	if x != nil && x.ClearBits != nil {
		return *x.ClearBits
	}
	return 0
}

func (x *IndicatorPrices) GetIsSnapshot() bool {
	if x != nil && x.IsSnapshot != nil {
		return *x.IsSnapshot
	}
	return false
}

func (x *IndicatorPrices) GetOpeningIndicator() float64 {
	if x != nil && x.OpeningIndicator != nil {
		return *x.OpeningIndicator
	}
	return 0
}

func (x *IndicatorPrices) GetClosingIndicator() float64 {
	if x != nil && x.ClosingIndicator != nil {
		return *x.ClosingIndicator
	}
	return 0
}

func (x *IndicatorPrices) GetSsboe() int32 {
	if x != nil && x.Ssboe != nil {
		return *x.Ssboe
	}
	return 0
}

func (x *IndicatorPrices) GetUsecs() int32 {
	if x != nil && x.Usecs != nil {
		return *x.Usecs
	}
	return 0
}

var File_indicator_prices_proto protoreflect.FileDescriptor

const file_indicator_prices_proto_rawDesc = "" +
	"\n" +
	"\x16indicator_prices.proto\x12\x03rti\"\xa3\x03\n" +
	"\x0fIndicatorPrices\x12!\n" +
	"\vtemplate_id\x18\xe3\xb6\t \x02(\x05R\n" +
	"templateId\x12\x18\n" +
	"\x06symbol\x18\x94\xdc\x06 \x01(\tR\x06symbol\x12\x1c\n" +
	"\bexchange\x18\x95\xdc\x06 \x01(\tR\bexchange\x12%\n" +
	"\rpresence_bits\x18\x92\x8d\t \x01(\rR\fpresenceBits\x12\x1f\n" +
	"\n" +
	"clear_bits\x18˷\t \x01(\rR\tclearBits\x12!\n" +
	"\vis_snapshot\x18\xa9\xdc\x06 \x01(\bR\n" +
	"isSnapshot\x12-\n" +
	"\x11opening_indicator\x18\x9a\xb7\t \x01(\x01R\x10openingIndicator\x12-\n" +
	"\x11closing_indicator\x18г\t \x01(\x01R\x10closingIndicator\x12\x16\n" +
	"\x05ssboe\x18Ԕ\t \x01(\x05R\x05ssboe\x12\x16\n" +
	"\x05usecs\x18Ք\t \x01(\x05R\x05usecs\"<\n" +
	"\fPresenceBits\x12\x15\n" +
	"\x11OPENING_INDICATOR\x10\x01\x12\x15\n" +
	"\x11CLOSING_INDICATOR\x10\x02B\x1eZ\x1cquant/extensions/rithmic/api"

var (
	file_indicator_prices_proto_rawDescOnce sync.Once
	file_indicator_prices_proto_rawDescData []byte
)

func file_indicator_prices_proto_rawDescGZIP() []byte {
	file_indicator_prices_proto_rawDescOnce.Do(func() {
		file_indicator_prices_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_indicator_prices_proto_rawDesc), len(file_indicator_prices_proto_rawDesc)))
	})
	return file_indicator_prices_proto_rawDescData
}

var file_indicator_prices_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_indicator_prices_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_indicator_prices_proto_goTypes = []any{
	(IndicatorPrices_PresenceBits)(0), // 0: rti.IndicatorPrices.PresenceBits
	(*IndicatorPrices)(nil),           // 1: rti.IndicatorPrices
}
var file_indicator_prices_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_indicator_prices_proto_init() }
func file_indicator_prices_proto_init() {
	if File_indicator_prices_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_indicator_prices_proto_rawDesc), len(file_indicator_prices_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_indicator_prices_proto_goTypes,
		DependencyIndexes: file_indicator_prices_proto_depIdxs,
		EnumInfos:         file_indicator_prices_proto_enumTypes,
		MessageInfos:      file_indicator_prices_proto_msgTypes,
	}.Build()
	File_indicator_prices_proto = out.File
	file_indicator_prices_proto_goTypes = nil
	file_indicator_prices_proto_depIdxs = nil
}
