// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: request_subscribe_to_bracket_updates.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestSubscribeToBracketUpdates struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TemplateId    *int32                 `protobuf:"varint,154467,req,name=template_id,json=templateId" json:"template_id,omitempty"` // PB_OFFSET + MNM_TEMPLATE_ID
	UserMsg       []string               `protobuf:"bytes,132760,rep,name=user_msg,json=userMsg" json:"user_msg,omitempty"`           // PB_OFFSET + MNM_USER_MSG
	FcmId         *string                `protobuf:"bytes,154013,opt,name=fcm_id,json=fcmId" json:"fcm_id,omitempty"`                 // PB_OFFSET + MNM_FCM_ID
	IbId          *string                `protobuf:"bytes,154014,opt,name=ib_id,json=ibId" json:"ib_id,omitempty"`                    // PB_OFFSET + MNM_IB_ID
	AccountId     *string                `protobuf:"bytes,154008,opt,name=account_id,json=accountId" json:"account_id,omitempty"`     // PB_OFFSET + MNM_ACCOUNT_ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestSubscribeToBracketUpdates) Reset() {
	*x = RequestSubscribeToBracketUpdates{}
	mi := &file_request_subscribe_to_bracket_updates_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestSubscribeToBracketUpdates) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestSubscribeToBracketUpdates) ProtoMessage() {}

func (x *RequestSubscribeToBracketUpdates) ProtoReflect() protoreflect.Message {
	mi := &file_request_subscribe_to_bracket_updates_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestSubscribeToBracketUpdates.ProtoReflect.Descriptor instead.
func (*RequestSubscribeToBracketUpdates) Descriptor() ([]byte, []int) {
	return file_request_subscribe_to_bracket_updates_proto_rawDescGZIP(), []int{0}
}

func (x *RequestSubscribeToBracketUpdates) GetTemplateId() int32 {
	if x != nil && x.TemplateId != nil {
		return *x.TemplateId
	}
	return 0
}

func (x *RequestSubscribeToBracketUpdates) GetUserMsg() []string {
	if x != nil {
		return x.UserMsg
	}
	return nil
}

func (x *RequestSubscribeToBracketUpdates) GetFcmId() string {
	if x != nil && x.FcmId != nil {
		return *x.FcmId
	}
	return ""
}

func (x *RequestSubscribeToBracketUpdates) GetIbId() string {
	if x != nil && x.IbId != nil {
		return *x.IbId
	}
	return ""
}

func (x *RequestSubscribeToBracketUpdates) GetAccountId() string {
	if x != nil && x.AccountId != nil {
		return *x.AccountId
	}
	return ""
}

var File_request_subscribe_to_bracket_updates_proto protoreflect.FileDescriptor

const file_request_subscribe_to_bracket_updates_proto_rawDesc = "" +
	"\n" +
	"*request_subscribe_to_bracket_updates.proto\x12\x03rti\"\xb3\x01\n" +
	" RequestSubscribeToBracketUpdates\x12!\n" +
	"\vtemplate_id\x18\xe3\xb6\t \x02(\x05R\n" +
	"templateId\x12\x1b\n" +
	"\buser_msg\x18\x98\x8d\b \x03(\tR\auserMsg\x12\x17\n" +
	"\x06fcm_id\x18\x9d\xb3\t \x01(\tR\x05fcmId\x12\x15\n" +
	"\x05ib_id\x18\x9e\xb3\t \x01(\tR\x04ibId\x12\x1f\n" +
	"\n" +
	"account_id\x18\x98\xb3\t \x01(\tR\taccountIdB\x1eZ\x1cquant/extensions/rithmic/api"

var (
	file_request_subscribe_to_bracket_updates_proto_rawDescOnce sync.Once
	file_request_subscribe_to_bracket_updates_proto_rawDescData []byte
)

func file_request_subscribe_to_bracket_updates_proto_rawDescGZIP() []byte {
	file_request_subscribe_to_bracket_updates_proto_rawDescOnce.Do(func() {
		file_request_subscribe_to_bracket_updates_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_request_subscribe_to_bracket_updates_proto_rawDesc), len(file_request_subscribe_to_bracket_updates_proto_rawDesc)))
	})
	return file_request_subscribe_to_bracket_updates_proto_rawDescData
}

var file_request_subscribe_to_bracket_updates_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_request_subscribe_to_bracket_updates_proto_goTypes = []any{
	(*RequestSubscribeToBracketUpdates)(nil), // 0: rti.RequestSubscribeToBracketUpdates
}
var file_request_subscribe_to_bracket_updates_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_request_subscribe_to_bracket_updates_proto_init() }
func file_request_subscribe_to_bracket_updates_proto_init() {
	if File_request_subscribe_to_bracket_updates_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_request_subscribe_to_bracket_updates_proto_rawDesc), len(file_request_subscribe_to_bracket_updates_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_request_subscribe_to_bracket_updates_proto_goTypes,
		DependencyIndexes: file_request_subscribe_to_bracket_updates_proto_depIdxs,
		MessageInfos:      file_request_subscribe_to_bracket_updates_proto_msgTypes,
	}.Build()
	File_request_subscribe_to_bracket_updates_proto = out.File
	file_request_subscribe_to_bracket_updates_proto_goTypes = nil
	file_request_subscribe_to_bracket_updates_proto_depIdxs = nil
}
