// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: request_tick_bar_update.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestTickBarUpdate_BarType int32

const (
	RequestTickBarUpdate_TICK_BAR   RequestTickBarUpdate_BarType = 1
	RequestTickBarUpdate_RANGE_BAR  RequestTickBarUpdate_BarType = 2
	RequestTickBarUpdate_VOLUME_BAR RequestTickBarUpdate_BarType = 3
)

// Enum value maps for RequestTickBarUpdate_BarType.
var (
	RequestTickBarUpdate_BarType_name = map[int32]string{
		1: "TICK_BAR",
		2: "RANGE_BAR",
		3: "VOLUME_BAR",
	}
	RequestTickBarUpdate_BarType_value = map[string]int32{
		"TICK_BAR":   1,
		"RANGE_BAR":  2,
		"VOLUME_BAR": 3,
	}
)

func (x RequestTickBarUpdate_BarType) Enum() *RequestTickBarUpdate_BarType {
	p := new(RequestTickBarUpdate_BarType)
	*p = x
	return p
}

func (x RequestTickBarUpdate_BarType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestTickBarUpdate_BarType) Descriptor() protoreflect.EnumDescriptor {
	return file_request_tick_bar_update_proto_enumTypes[0].Descriptor()
}

func (RequestTickBarUpdate_BarType) Type() protoreflect.EnumType {
	return &file_request_tick_bar_update_proto_enumTypes[0]
}

func (x RequestTickBarUpdate_BarType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RequestTickBarUpdate_BarType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RequestTickBarUpdate_BarType(num)
	return nil
}

// Deprecated: Use RequestTickBarUpdate_BarType.Descriptor instead.
func (RequestTickBarUpdate_BarType) EnumDescriptor() ([]byte, []int) {
	return file_request_tick_bar_update_proto_rawDescGZIP(), []int{0, 0}
}

type RequestTickBarUpdate_BarSubType int32

const (
	RequestTickBarUpdate_REGULAR RequestTickBarUpdate_BarSubType = 1
	RequestTickBarUpdate_CUSTOM  RequestTickBarUpdate_BarSubType = 2
)

// Enum value maps for RequestTickBarUpdate_BarSubType.
var (
	RequestTickBarUpdate_BarSubType_name = map[int32]string{
		1: "REGULAR",
		2: "CUSTOM",
	}
	RequestTickBarUpdate_BarSubType_value = map[string]int32{
		"REGULAR": 1,
		"CUSTOM":  2,
	}
)

func (x RequestTickBarUpdate_BarSubType) Enum() *RequestTickBarUpdate_BarSubType {
	p := new(RequestTickBarUpdate_BarSubType)
	*p = x
	return p
}

func (x RequestTickBarUpdate_BarSubType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestTickBarUpdate_BarSubType) Descriptor() protoreflect.EnumDescriptor {
	return file_request_tick_bar_update_proto_enumTypes[1].Descriptor()
}

func (RequestTickBarUpdate_BarSubType) Type() protoreflect.EnumType {
	return &file_request_tick_bar_update_proto_enumTypes[1]
}

func (x RequestTickBarUpdate_BarSubType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RequestTickBarUpdate_BarSubType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RequestTickBarUpdate_BarSubType(num)
	return nil
}

// Deprecated: Use RequestTickBarUpdate_BarSubType.Descriptor instead.
func (RequestTickBarUpdate_BarSubType) EnumDescriptor() ([]byte, []int) {
	return file_request_tick_bar_update_proto_rawDescGZIP(), []int{0, 1}
}

type RequestTickBarUpdate_Request int32

const (
	RequestTickBarUpdate_SUBSCRIBE   RequestTickBarUpdate_Request = 1
	RequestTickBarUpdate_UNSUBSCRIBE RequestTickBarUpdate_Request = 2
)

// Enum value maps for RequestTickBarUpdate_Request.
var (
	RequestTickBarUpdate_Request_name = map[int32]string{
		1: "SUBSCRIBE",
		2: "UNSUBSCRIBE",
	}
	RequestTickBarUpdate_Request_value = map[string]int32{
		"SUBSCRIBE":   1,
		"UNSUBSCRIBE": 2,
	}
)

func (x RequestTickBarUpdate_Request) Enum() *RequestTickBarUpdate_Request {
	p := new(RequestTickBarUpdate_Request)
	*p = x
	return p
}

func (x RequestTickBarUpdate_Request) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestTickBarUpdate_Request) Descriptor() protoreflect.EnumDescriptor {
	return file_request_tick_bar_update_proto_enumTypes[2].Descriptor()
}

func (RequestTickBarUpdate_Request) Type() protoreflect.EnumType {
	return &file_request_tick_bar_update_proto_enumTypes[2]
}

func (x RequestTickBarUpdate_Request) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RequestTickBarUpdate_Request) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RequestTickBarUpdate_Request(num)
	return nil
}

// Deprecated: Use RequestTickBarUpdate_Request.Descriptor instead.
func (RequestTickBarUpdate_Request) EnumDescriptor() ([]byte, []int) {
	return file_request_tick_bar_update_proto_rawDescGZIP(), []int{0, 2}
}

type RequestTickBarUpdate struct {
	state                 protoimpl.MessageState           `protogen:"open.v1"`
	TemplateId            *int32                           `protobuf:"varint,154467,req,name=template_id,json=templateId" json:"template_id,omitempty"`                                            // PB_OFFSET + MNM_TEMPLATE_ID
	UserMsg               []string                         `protobuf:"bytes,132760,rep,name=user_msg,json=userMsg" json:"user_msg,omitempty"`                                                      // PB_OFFSET + MNM_USER_MSG
	Symbol                *string                          `protobuf:"bytes,110100,opt,name=symbol" json:"symbol,omitempty"`                                                                       // PB_OFFSET + MNM_SYMBOL
	Exchange              *string                          `protobuf:"bytes,110101,opt,name=exchange" json:"exchange,omitempty"`                                                                   // PB_OFFSET + MNM_EXCHANGE
	Request               *RequestTickBarUpdate_Request    `protobuf:"varint,100000,opt,name=request,enum=rti.RequestTickBarUpdate_Request" json:"request,omitempty"`                              // PB_OFFSET + MNM_REQUEST
	BarType               *RequestTickBarUpdate_BarType    `protobuf:"varint,119200,opt,name=bar_type,json=barType,enum=rti.RequestTickBarUpdate_BarType" json:"bar_type,omitempty"`               // PB_OFFSET + MNM_DATA_BAR_TYPE
	BarSubType            *RequestTickBarUpdate_BarSubType `protobuf:"varint,119208,opt,name=bar_sub_type,json=barSubType,enum=rti.RequestTickBarUpdate_BarSubType" json:"bar_sub_type,omitempty"` // PB_OFFSET + MNM_DATA_BAR_SUB_TYPE
	BarTypeSpecifier      *string                          `protobuf:"bytes,148162,opt,name=bar_type_specifier,json=barTypeSpecifier" json:"bar_type_specifier,omitempty"`                         // PB_OFFSET + MNM_CATEGORY_SPECIFIC_INFO
	CustomSessionOpenSsm  *int32                           `protobuf:"varint,119209,opt,name=custom_session_open_ssm,json=customSessionOpenSsm" json:"custom_session_open_ssm,omitempty"`          // PB_OFFSET + MNM_CUSTOM_SESSION_OPEN_SSM
	CustomSessionCloseSsm *int32                           `protobuf:"varint,119210,opt,name=custom_session_close_ssm,json=customSessionCloseSsm" json:"custom_session_close_ssm,omitempty"`       // PB_OFFSET + MNM_CUSTOM_SESSION_CLOSE_SSM
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RequestTickBarUpdate) Reset() {
	*x = RequestTickBarUpdate{}
	mi := &file_request_tick_bar_update_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestTickBarUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestTickBarUpdate) ProtoMessage() {}

func (x *RequestTickBarUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_request_tick_bar_update_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestTickBarUpdate.ProtoReflect.Descriptor instead.
func (*RequestTickBarUpdate) Descriptor() ([]byte, []int) {
	return file_request_tick_bar_update_proto_rawDescGZIP(), []int{0}
}

func (x *RequestTickBarUpdate) GetTemplateId() int32 {
	if x != nil && x.TemplateId != nil {
		return *x.TemplateId
	}
	return 0
}

func (x *RequestTickBarUpdate) GetUserMsg() []string {
	if x != nil {
		return x.UserMsg
	}
	return nil
}

func (x *RequestTickBarUpdate) GetSymbol() string {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return ""
}

func (x *RequestTickBarUpdate) GetExchange() string {
	if x != nil && x.Exchange != nil {
		return *x.Exchange
	}
	return ""
}

func (x *RequestTickBarUpdate) GetRequest() RequestTickBarUpdate_Request {
	if x != nil && x.Request != nil {
		return *x.Request
	}
	return RequestTickBarUpdate_SUBSCRIBE
}

func (x *RequestTickBarUpdate) GetBarType() RequestTickBarUpdate_BarType {
	if x != nil && x.BarType != nil {
		return *x.BarType
	}
	return RequestTickBarUpdate_TICK_BAR
}

func (x *RequestTickBarUpdate) GetBarSubType() RequestTickBarUpdate_BarSubType {
	if x != nil && x.BarSubType != nil {
		return *x.BarSubType
	}
	return RequestTickBarUpdate_REGULAR
}

func (x *RequestTickBarUpdate) GetBarTypeSpecifier() string {
	if x != nil && x.BarTypeSpecifier != nil {
		return *x.BarTypeSpecifier
	}
	return ""
}

func (x *RequestTickBarUpdate) GetCustomSessionOpenSsm() int32 {
	if x != nil && x.CustomSessionOpenSsm != nil {
		return *x.CustomSessionOpenSsm
	}
	return 0
}

func (x *RequestTickBarUpdate) GetCustomSessionCloseSsm() int32 {
	if x != nil && x.CustomSessionCloseSsm != nil {
		return *x.CustomSessionCloseSsm
	}
	return 0
}

var File_request_tick_bar_update_proto protoreflect.FileDescriptor

const file_request_tick_bar_update_proto_rawDesc = "" +
	"\n" +
	"\x1drequest_tick_bar_update.proto\x12\x03rti\"\x85\x05\n" +
	"\x14RequestTickBarUpdate\x12!\n" +
	"\vtemplate_id\x18\xe3\xb6\t \x02(\x05R\n" +
	"templateId\x12\x1b\n" +
	"\buser_msg\x18\x98\x8d\b \x03(\tR\auserMsg\x12\x18\n" +
	"\x06symbol\x18\x94\xdc\x06 \x01(\tR\x06symbol\x12\x1c\n" +
	"\bexchange\x18\x95\xdc\x06 \x01(\tR\bexchange\x12=\n" +
	"\arequest\x18\xa0\x8d\x06 \x01(\x0e2!.rti.RequestTickBarUpdate.RequestR\arequest\x12>\n" +
	"\bbar_type\x18\xa0\xa3\a \x01(\x0e2!.rti.RequestTickBarUpdate.BarTypeR\abarType\x12H\n" +
	"\fbar_sub_type\x18\xa8\xa3\a \x01(\x0e2$.rti.RequestTickBarUpdate.BarSubTypeR\n" +
	"barSubType\x12.\n" +
	"\x12bar_type_specifier\x18\u0085\t \x01(\tR\x10barTypeSpecifier\x127\n" +
	"\x17custom_session_open_ssm\x18\xa9\xa3\a \x01(\x05R\x14customSessionOpenSsm\x129\n" +
	"\x18custom_session_close_ssm\x18\xaa\xa3\a \x01(\x05R\x15customSessionCloseSsm\"6\n" +
	"\aBarType\x12\f\n" +
	"\bTICK_BAR\x10\x01\x12\r\n" +
	"\tRANGE_BAR\x10\x02\x12\x0e\n" +
	"\n" +
	"VOLUME_BAR\x10\x03\"%\n" +
	"\n" +
	"BarSubType\x12\v\n" +
	"\aREGULAR\x10\x01\x12\n" +
	"\n" +
	"\x06CUSTOM\x10\x02\")\n" +
	"\aRequest\x12\r\n" +
	"\tSUBSCRIBE\x10\x01\x12\x0f\n" +
	"\vUNSUBSCRIBE\x10\x02B\x1eZ\x1cquant/extensions/rithmic/api"

var (
	file_request_tick_bar_update_proto_rawDescOnce sync.Once
	file_request_tick_bar_update_proto_rawDescData []byte
)

func file_request_tick_bar_update_proto_rawDescGZIP() []byte {
	file_request_tick_bar_update_proto_rawDescOnce.Do(func() {
		file_request_tick_bar_update_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_request_tick_bar_update_proto_rawDesc), len(file_request_tick_bar_update_proto_rawDesc)))
	})
	return file_request_tick_bar_update_proto_rawDescData
}

var file_request_tick_bar_update_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_request_tick_bar_update_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_request_tick_bar_update_proto_goTypes = []any{
	(RequestTickBarUpdate_BarType)(0),    // 0: rti.RequestTickBarUpdate.BarType
	(RequestTickBarUpdate_BarSubType)(0), // 1: rti.RequestTickBarUpdate.BarSubType
	(RequestTickBarUpdate_Request)(0),    // 2: rti.RequestTickBarUpdate.Request
	(*RequestTickBarUpdate)(nil),         // 3: rti.RequestTickBarUpdate
}
var file_request_tick_bar_update_proto_depIdxs = []int32{
	2, // 0: rti.RequestTickBarUpdate.request:type_name -> rti.RequestTickBarUpdate.Request
	0, // 1: rti.RequestTickBarUpdate.bar_type:type_name -> rti.RequestTickBarUpdate.BarType
	1, // 2: rti.RequestTickBarUpdate.bar_sub_type:type_name -> rti.RequestTickBarUpdate.BarSubType
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_request_tick_bar_update_proto_init() }
func file_request_tick_bar_update_proto_init() {
	if File_request_tick_bar_update_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_request_tick_bar_update_proto_rawDesc), len(file_request_tick_bar_update_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_request_tick_bar_update_proto_goTypes,
		DependencyIndexes: file_request_tick_bar_update_proto_depIdxs,
		EnumInfos:         file_request_tick_bar_update_proto_enumTypes,
		MessageInfos:      file_request_tick_bar_update_proto_msgTypes,
	}.Build()
	File_request_tick_bar_update_proto = out.File
	file_request_tick_bar_update_proto_goTypes = nil
	file_request_tick_bar_update_proto_depIdxs = nil
}
