// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: request_search_symbols.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestSearchSymbols_Pattern int32

const (
	RequestSearchSymbols_EQUALS   RequestSearchSymbols_Pattern = 1
	RequestSearchSymbols_CONTAINS RequestSearchSymbols_Pattern = 2
)

// Enum value maps for RequestSearchSymbols_Pattern.
var (
	RequestSearchSymbols_Pattern_name = map[int32]string{
		1: "EQUALS",
		2: "CONTAINS",
	}
	RequestSearchSymbols_Pattern_value = map[string]int32{
		"EQUALS":   1,
		"CONTAINS": 2,
	}
)

func (x RequestSearchSymbols_Pattern) Enum() *RequestSearchSymbols_Pattern {
	p := new(RequestSearchSymbols_Pattern)
	*p = x
	return p
}

func (x RequestSearchSymbols_Pattern) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestSearchSymbols_Pattern) Descriptor() protoreflect.EnumDescriptor {
	return file_request_search_symbols_proto_enumTypes[0].Descriptor()
}

func (RequestSearchSymbols_Pattern) Type() protoreflect.EnumType {
	return &file_request_search_symbols_proto_enumTypes[0]
}

func (x RequestSearchSymbols_Pattern) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RequestSearchSymbols_Pattern) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RequestSearchSymbols_Pattern(num)
	return nil
}

// Deprecated: Use RequestSearchSymbols_Pattern.Descriptor instead.
func (RequestSearchSymbols_Pattern) EnumDescriptor() ([]byte, []int) {
	return file_request_search_symbols_proto_rawDescGZIP(), []int{0, 0}
}

type RequestSearchSymbols_InstrumentType int32

const (
	RequestSearchSymbols_FUTURE          RequestSearchSymbols_InstrumentType = 1
	RequestSearchSymbols_FUTURE_OPTION   RequestSearchSymbols_InstrumentType = 2
	RequestSearchSymbols_FUTURE_STRATEGY RequestSearchSymbols_InstrumentType = 3
	RequestSearchSymbols_EQUITY          RequestSearchSymbols_InstrumentType = 4
	RequestSearchSymbols_EQUITY_OPTION   RequestSearchSymbols_InstrumentType = 5
	RequestSearchSymbols_EQUITY_STRATEGY RequestSearchSymbols_InstrumentType = 6
	RequestSearchSymbols_INDEX           RequestSearchSymbols_InstrumentType = 7
	RequestSearchSymbols_INDEX_OPTION    RequestSearchSymbols_InstrumentType = 8
	RequestSearchSymbols_SPREAD          RequestSearchSymbols_InstrumentType = 9
	RequestSearchSymbols_SYNTHETIC       RequestSearchSymbols_InstrumentType = 10
)

// Enum value maps for RequestSearchSymbols_InstrumentType.
var (
	RequestSearchSymbols_InstrumentType_name = map[int32]string{
		1:  "FUTURE",
		2:  "FUTURE_OPTION",
		3:  "FUTURE_STRATEGY",
		4:  "EQUITY",
		5:  "EQUITY_OPTION",
		6:  "EQUITY_STRATEGY",
		7:  "INDEX",
		8:  "INDEX_OPTION",
		9:  "SPREAD",
		10: "SYNTHETIC",
	}
	RequestSearchSymbols_InstrumentType_value = map[string]int32{
		"FUTURE":          1,
		"FUTURE_OPTION":   2,
		"FUTURE_STRATEGY": 3,
		"EQUITY":          4,
		"EQUITY_OPTION":   5,
		"EQUITY_STRATEGY": 6,
		"INDEX":           7,
		"INDEX_OPTION":    8,
		"SPREAD":          9,
		"SYNTHETIC":       10,
	}
)

func (x RequestSearchSymbols_InstrumentType) Enum() *RequestSearchSymbols_InstrumentType {
	p := new(RequestSearchSymbols_InstrumentType)
	*p = x
	return p
}

func (x RequestSearchSymbols_InstrumentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestSearchSymbols_InstrumentType) Descriptor() protoreflect.EnumDescriptor {
	return file_request_search_symbols_proto_enumTypes[1].Descriptor()
}

func (RequestSearchSymbols_InstrumentType) Type() protoreflect.EnumType {
	return &file_request_search_symbols_proto_enumTypes[1]
}

func (x RequestSearchSymbols_InstrumentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RequestSearchSymbols_InstrumentType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RequestSearchSymbols_InstrumentType(num)
	return nil
}

// Deprecated: Use RequestSearchSymbols_InstrumentType.Descriptor instead.
func (RequestSearchSymbols_InstrumentType) EnumDescriptor() ([]byte, []int) {
	return file_request_search_symbols_proto_rawDescGZIP(), []int{0, 1}
}

type RequestSearchSymbols struct {
	state          protoimpl.MessageState               `protogen:"open.v1"`
	TemplateId     *int32                               `protobuf:"varint,154467,req,name=template_id,json=templateId" json:"template_id,omitempty"`                                                          // PB_OFFSET + MNM_TEMPLATE_ID
	UserMsg        []string                             `protobuf:"bytes,132760,rep,name=user_msg,json=userMsg" json:"user_msg,omitempty"`                                                                    // PB_OFFSET + MNM_USER_MSG
	SearchText     *string                              `protobuf:"bytes,120008,opt,name=search_text,json=searchText" json:"search_text,omitempty"`                                                           // PB_OFFSET + MNM_TEXT
	Exchange       *string                              `protobuf:"bytes,110101,opt,name=exchange" json:"exchange,omitempty"`                                                                                 // PB_OFFSET + MNM_EXCHANGE
	ProductCode    *string                              `protobuf:"bytes,100749,opt,name=product_code,json=productCode" json:"product_code,omitempty"`                                                        // PB_OFFSET + MNM_PRODUCT_CODE
	InstrumentType *RequestSearchSymbols_InstrumentType `protobuf:"varint,110116,opt,name=instrument_type,json=instrumentType,enum=rti.RequestSearchSymbols_InstrumentType" json:"instrument_type,omitempty"` // PB_OFFSET + MNM_INSTRUMENT_TYPE
	Pattern        *RequestSearchSymbols_Pattern        `protobuf:"varint,155008,opt,name=pattern,enum=rti.RequestSearchSymbols_Pattern" json:"pattern,omitempty"`                                            // PB_OFFSET + MNM_SEARCH_PATTERN
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RequestSearchSymbols) Reset() {
	*x = RequestSearchSymbols{}
	mi := &file_request_search_symbols_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestSearchSymbols) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestSearchSymbols) ProtoMessage() {}

func (x *RequestSearchSymbols) ProtoReflect() protoreflect.Message {
	mi := &file_request_search_symbols_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestSearchSymbols.ProtoReflect.Descriptor instead.
func (*RequestSearchSymbols) Descriptor() ([]byte, []int) {
	return file_request_search_symbols_proto_rawDescGZIP(), []int{0}
}

func (x *RequestSearchSymbols) GetTemplateId() int32 {
	if x != nil && x.TemplateId != nil {
		return *x.TemplateId
	}
	return 0
}

func (x *RequestSearchSymbols) GetUserMsg() []string {
	if x != nil {
		return x.UserMsg
	}
	return nil
}

func (x *RequestSearchSymbols) GetSearchText() string {
	if x != nil && x.SearchText != nil {
		return *x.SearchText
	}
	return ""
}

func (x *RequestSearchSymbols) GetExchange() string {
	if x != nil && x.Exchange != nil {
		return *x.Exchange
	}
	return ""
}

func (x *RequestSearchSymbols) GetProductCode() string {
	if x != nil && x.ProductCode != nil {
		return *x.ProductCode
	}
	return ""
}

func (x *RequestSearchSymbols) GetInstrumentType() RequestSearchSymbols_InstrumentType {
	if x != nil && x.InstrumentType != nil {
		return *x.InstrumentType
	}
	return RequestSearchSymbols_FUTURE
}

func (x *RequestSearchSymbols) GetPattern() RequestSearchSymbols_Pattern {
	if x != nil && x.Pattern != nil {
		return *x.Pattern
	}
	return RequestSearchSymbols_EQUALS
}

var File_request_search_symbols_proto protoreflect.FileDescriptor

const file_request_search_symbols_proto_rawDesc = "" +
	"\n" +
	"\x1crequest_search_symbols.proto\x12\x03rti\"\xa8\x04\n" +
	"\x14RequestSearchSymbols\x12!\n" +
	"\vtemplate_id\x18\xe3\xb6\t \x02(\x05R\n" +
	"templateId\x12\x1b\n" +
	"\buser_msg\x18\x98\x8d\b \x03(\tR\auserMsg\x12!\n" +
	"\vsearch_text\x18ȩ\a \x01(\tR\n" +
	"searchText\x12\x1c\n" +
	"\bexchange\x18\x95\xdc\x06 \x01(\tR\bexchange\x12#\n" +
	"\fproduct_code\x18\x8d\x93\x06 \x01(\tR\vproductCode\x12S\n" +
	"\x0finstrument_type\x18\xa4\xdc\x06 \x01(\x0e2(.rti.RequestSearchSymbols.InstrumentTypeR\x0einstrumentType\x12=\n" +
	"\apattern\x18\x80\xbb\t \x01(\x0e2!.rti.RequestSearchSymbols.PatternR\apattern\"#\n" +
	"\aPattern\x12\n" +
	"\n" +
	"\x06EQUALS\x10\x01\x12\f\n" +
	"\bCONTAINS\x10\x02\"\xb0\x01\n" +
	"\x0eInstrumentType\x12\n" +
	"\n" +
	"\x06FUTURE\x10\x01\x12\x11\n" +
	"\rFUTURE_OPTION\x10\x02\x12\x13\n" +
	"\x0fFUTURE_STRATEGY\x10\x03\x12\n" +
	"\n" +
	"\x06EQUITY\x10\x04\x12\x11\n" +
	"\rEQUITY_OPTION\x10\x05\x12\x13\n" +
	"\x0fEQUITY_STRATEGY\x10\x06\x12\t\n" +
	"\x05INDEX\x10\a\x12\x10\n" +
	"\fINDEX_OPTION\x10\b\x12\n" +
	"\n" +
	"\x06SPREAD\x10\t\x12\r\n" +
	"\tSYNTHETIC\x10\n" +
	"B\x1eZ\x1cquant/extensions/rithmic/api"

var (
	file_request_search_symbols_proto_rawDescOnce sync.Once
	file_request_search_symbols_proto_rawDescData []byte
)

func file_request_search_symbols_proto_rawDescGZIP() []byte {
	file_request_search_symbols_proto_rawDescOnce.Do(func() {
		file_request_search_symbols_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_request_search_symbols_proto_rawDesc), len(file_request_search_symbols_proto_rawDesc)))
	})
	return file_request_search_symbols_proto_rawDescData
}

var file_request_search_symbols_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_request_search_symbols_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_request_search_symbols_proto_goTypes = []any{
	(RequestSearchSymbols_Pattern)(0),        // 0: rti.RequestSearchSymbols.Pattern
	(RequestSearchSymbols_InstrumentType)(0), // 1: rti.RequestSearchSymbols.InstrumentType
	(*RequestSearchSymbols)(nil),             // 2: rti.RequestSearchSymbols
}
var file_request_search_symbols_proto_depIdxs = []int32{
	1, // 0: rti.RequestSearchSymbols.instrument_type:type_name -> rti.RequestSearchSymbols.InstrumentType
	0, // 1: rti.RequestSearchSymbols.pattern:type_name -> rti.RequestSearchSymbols.Pattern
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_request_search_symbols_proto_init() }
func file_request_search_symbols_proto_init() {
	if File_request_search_symbols_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_request_search_symbols_proto_rawDesc), len(file_request_search_symbols_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_request_search_symbols_proto_goTypes,
		DependencyIndexes: file_request_search_symbols_proto_depIdxs,
		EnumInfos:         file_request_search_symbols_proto_enumTypes,
		MessageInfos:      file_request_search_symbols_proto_msgTypes,
	}.Build()
	File_request_search_symbols_proto = out.File
	file_request_search_symbols_proto_goTypes = nil
	file_request_search_symbols_proto_depIdxs = nil
}
