// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: request_cancel_all_orders.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestCancelAllOrders_OrderPlacement int32

const (
	RequestCancelAllOrders_MANUAL RequestCancelAllOrders_OrderPlacement = 1
	RequestCancelAllOrders_AUTO   RequestCancelAllOrders_OrderPlacement = 2
)

// Enum value maps for RequestCancelAllOrders_OrderPlacement.
var (
	RequestCancelAllOrders_OrderPlacement_name = map[int32]string{
		1: "MANUAL",
		2: "AUTO",
	}
	RequestCancelAllOrders_OrderPlacement_value = map[string]int32{
		"MANUAL": 1,
		"AUTO":   2,
	}
)

func (x RequestCancelAllOrders_OrderPlacement) Enum() *RequestCancelAllOrders_OrderPlacement {
	p := new(RequestCancelAllOrders_OrderPlacement)
	*p = x
	return p
}

func (x RequestCancelAllOrders_OrderPlacement) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestCancelAllOrders_OrderPlacement) Descriptor() protoreflect.EnumDescriptor {
	return file_request_cancel_all_orders_proto_enumTypes[0].Descriptor()
}

func (RequestCancelAllOrders_OrderPlacement) Type() protoreflect.EnumType {
	return &file_request_cancel_all_orders_proto_enumTypes[0]
}

func (x RequestCancelAllOrders_OrderPlacement) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RequestCancelAllOrders_OrderPlacement) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RequestCancelAllOrders_OrderPlacement(num)
	return nil
}

// Deprecated: Use RequestCancelAllOrders_OrderPlacement.Descriptor instead.
func (RequestCancelAllOrders_OrderPlacement) EnumDescriptor() ([]byte, []int) {
	return file_request_cancel_all_orders_proto_rawDescGZIP(), []int{0, 0}
}

type RequestCancelAllOrders_UserType int32

const (
	RequestCancelAllOrders_USER_TYPE_ADMIN  RequestCancelAllOrders_UserType = 0
	RequestCancelAllOrders_USER_TYPE_FCM    RequestCancelAllOrders_UserType = 1
	RequestCancelAllOrders_USER_TYPE_IB     RequestCancelAllOrders_UserType = 2
	RequestCancelAllOrders_USER_TYPE_TRADER RequestCancelAllOrders_UserType = 3
)

// Enum value maps for RequestCancelAllOrders_UserType.
var (
	RequestCancelAllOrders_UserType_name = map[int32]string{
		0: "USER_TYPE_ADMIN",
		1: "USER_TYPE_FCM",
		2: "USER_TYPE_IB",
		3: "USER_TYPE_TRADER",
	}
	RequestCancelAllOrders_UserType_value = map[string]int32{
		"USER_TYPE_ADMIN":  0,
		"USER_TYPE_FCM":    1,
		"USER_TYPE_IB":     2,
		"USER_TYPE_TRADER": 3,
	}
)

func (x RequestCancelAllOrders_UserType) Enum() *RequestCancelAllOrders_UserType {
	p := new(RequestCancelAllOrders_UserType)
	*p = x
	return p
}

func (x RequestCancelAllOrders_UserType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestCancelAllOrders_UserType) Descriptor() protoreflect.EnumDescriptor {
	return file_request_cancel_all_orders_proto_enumTypes[1].Descriptor()
}

func (RequestCancelAllOrders_UserType) Type() protoreflect.EnumType {
	return &file_request_cancel_all_orders_proto_enumTypes[1]
}

func (x RequestCancelAllOrders_UserType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RequestCancelAllOrders_UserType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RequestCancelAllOrders_UserType(num)
	return nil
}

// Deprecated: Use RequestCancelAllOrders_UserType.Descriptor instead.
func (RequestCancelAllOrders_UserType) EnumDescriptor() ([]byte, []int) {
	return file_request_cancel_all_orders_proto_rawDescGZIP(), []int{0, 1}
}

type RequestCancelAllOrders struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	TemplateId    *int32                                 `protobuf:"varint,154467,req,name=template_id,json=templateId" json:"template_id,omitempty"`                                                        // PB_OFFSET + MNM_TEMPLATE_ID
	UserMsg       []string                               `protobuf:"bytes,132760,rep,name=user_msg,json=userMsg" json:"user_msg,omitempty"`                                                                  // PB_OFFSET + MNM_USER_MSG
	FcmId         *string                                `protobuf:"bytes,154013,opt,name=fcm_id,json=fcmId" json:"fcm_id,omitempty"`                                                                        // PB_OFFSET + MNM_FCM_ID
	IbId          *string                                `protobuf:"bytes,154014,opt,name=ib_id,json=ibId" json:"ib_id,omitempty"`                                                                           // PB_OFFSET + MNM_IB_ID
	AccountId     *string                                `protobuf:"bytes,154008,opt,name=account_id,json=accountId" json:"account_id,omitempty"`                                                            // PB_OFFSET + MNM_ACCOUNT_ID
	UserType      *RequestCancelAllOrders_UserType       `protobuf:"varint,154036,opt,name=user_type,json=userType,enum=rti.RequestCancelAllOrders_UserType" json:"user_type,omitempty"`                     // PB_OFFSET + MNM_USER_TYPE
	ManualOrAuto  *RequestCancelAllOrders_OrderPlacement `protobuf:"varint,154710,opt,name=manual_or_auto,json=manualOrAuto,enum=rti.RequestCancelAllOrders_OrderPlacement" json:"manual_or_auto,omitempty"` // PB_OFFSET + MNM_MANUAL_OR_AUTO
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestCancelAllOrders) Reset() {
	*x = RequestCancelAllOrders{}
	mi := &file_request_cancel_all_orders_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestCancelAllOrders) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestCancelAllOrders) ProtoMessage() {}

func (x *RequestCancelAllOrders) ProtoReflect() protoreflect.Message {
	mi := &file_request_cancel_all_orders_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestCancelAllOrders.ProtoReflect.Descriptor instead.
func (*RequestCancelAllOrders) Descriptor() ([]byte, []int) {
	return file_request_cancel_all_orders_proto_rawDescGZIP(), []int{0}
}

func (x *RequestCancelAllOrders) GetTemplateId() int32 {
	if x != nil && x.TemplateId != nil {
		return *x.TemplateId
	}
	return 0
}

func (x *RequestCancelAllOrders) GetUserMsg() []string {
	if x != nil {
		return x.UserMsg
	}
	return nil
}

func (x *RequestCancelAllOrders) GetFcmId() string {
	if x != nil && x.FcmId != nil {
		return *x.FcmId
	}
	return ""
}

func (x *RequestCancelAllOrders) GetIbId() string {
	if x != nil && x.IbId != nil {
		return *x.IbId
	}
	return ""
}

func (x *RequestCancelAllOrders) GetAccountId() string {
	if x != nil && x.AccountId != nil {
		return *x.AccountId
	}
	return ""
}

func (x *RequestCancelAllOrders) GetUserType() RequestCancelAllOrders_UserType {
	if x != nil && x.UserType != nil {
		return *x.UserType
	}
	return RequestCancelAllOrders_USER_TYPE_ADMIN
}

func (x *RequestCancelAllOrders) GetManualOrAuto() RequestCancelAllOrders_OrderPlacement {
	if x != nil && x.ManualOrAuto != nil {
		return *x.ManualOrAuto
	}
	return RequestCancelAllOrders_MANUAL
}

var File_request_cancel_all_orders_proto protoreflect.FileDescriptor

const file_request_cancel_all_orders_proto_rawDesc = "" +
	"\n" +
	"\x1frequest_cancel_all_orders.proto\x12\x03rti\"\xc6\x03\n" +
	"\x16RequestCancelAllOrders\x12!\n" +
	"\vtemplate_id\x18\xe3\xb6\t \x02(\x05R\n" +
	"templateId\x12\x1b\n" +
	"\buser_msg\x18\x98\x8d\b \x03(\tR\auserMsg\x12\x17\n" +
	"\x06fcm_id\x18\x9d\xb3\t \x01(\tR\x05fcmId\x12\x15\n" +
	"\x05ib_id\x18\x9e\xb3\t \x01(\tR\x04ibId\x12\x1f\n" +
	"\n" +
	"account_id\x18\x98\xb3\t \x01(\tR\taccountId\x12C\n" +
	"\tuser_type\x18\xb4\xb3\t \x01(\x0e2$.rti.RequestCancelAllOrders.UserTypeR\buserType\x12R\n" +
	"\x0emanual_or_auto\x18ָ\t \x01(\x0e2*.rti.RequestCancelAllOrders.OrderPlacementR\fmanualOrAuto\"&\n" +
	"\x0eOrderPlacement\x12\n" +
	"\n" +
	"\x06MANUAL\x10\x01\x12\b\n" +
	"\x04AUTO\x10\x02\"Z\n" +
	"\bUserType\x12\x13\n" +
	"\x0fUSER_TYPE_ADMIN\x10\x00\x12\x11\n" +
	"\rUSER_TYPE_FCM\x10\x01\x12\x10\n" +
	"\fUSER_TYPE_IB\x10\x02\x12\x14\n" +
	"\x10USER_TYPE_TRADER\x10\x03B\x1eZ\x1cquant/extensions/rithmic/api"

var (
	file_request_cancel_all_orders_proto_rawDescOnce sync.Once
	file_request_cancel_all_orders_proto_rawDescData []byte
)

func file_request_cancel_all_orders_proto_rawDescGZIP() []byte {
	file_request_cancel_all_orders_proto_rawDescOnce.Do(func() {
		file_request_cancel_all_orders_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_request_cancel_all_orders_proto_rawDesc), len(file_request_cancel_all_orders_proto_rawDesc)))
	})
	return file_request_cancel_all_orders_proto_rawDescData
}

var file_request_cancel_all_orders_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_request_cancel_all_orders_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_request_cancel_all_orders_proto_goTypes = []any{
	(RequestCancelAllOrders_OrderPlacement)(0), // 0: rti.RequestCancelAllOrders.OrderPlacement
	(RequestCancelAllOrders_UserType)(0),       // 1: rti.RequestCancelAllOrders.UserType
	(*RequestCancelAllOrders)(nil),             // 2: rti.RequestCancelAllOrders
}
var file_request_cancel_all_orders_proto_depIdxs = []int32{
	1, // 0: rti.RequestCancelAllOrders.user_type:type_name -> rti.RequestCancelAllOrders.UserType
	0, // 1: rti.RequestCancelAllOrders.manual_or_auto:type_name -> rti.RequestCancelAllOrders.OrderPlacement
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_request_cancel_all_orders_proto_init() }
func file_request_cancel_all_orders_proto_init() {
	if File_request_cancel_all_orders_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_request_cancel_all_orders_proto_rawDesc), len(file_request_cancel_all_orders_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_request_cancel_all_orders_proto_goTypes,
		DependencyIndexes: file_request_cancel_all_orders_proto_depIdxs,
		EnumInfos:         file_request_cancel_all_orders_proto_enumTypes,
		MessageInfos:      file_request_cancel_all_orders_proto_msgTypes,
	}.Build()
	File_request_cancel_all_orders_proto = out.File
	file_request_cancel_all_orders_proto_goTypes = nil
	file_request_cancel_all_orders_proto_depIdxs = nil
}
