// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: request_oco_order.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestOCOOrder_TransactionType int32

const (
	RequestOCOOrder_BUY  RequestOCOOrder_TransactionType = 1
	RequestOCOOrder_SELL RequestOCOOrder_TransactionType = 2
)

// Enum value maps for RequestOCOOrder_TransactionType.
var (
	RequestOCOOrder_TransactionType_name = map[int32]string{
		1: "BUY",
		2: "SELL",
	}
	RequestOCOOrder_TransactionType_value = map[string]int32{
		"BUY":  1,
		"SELL": 2,
	}
)

func (x RequestOCOOrder_TransactionType) Enum() *RequestOCOOrder_TransactionType {
	p := new(RequestOCOOrder_TransactionType)
	*p = x
	return p
}

func (x RequestOCOOrder_TransactionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestOCOOrder_TransactionType) Descriptor() protoreflect.EnumDescriptor {
	return file_request_oco_order_proto_enumTypes[0].Descriptor()
}

func (RequestOCOOrder_TransactionType) Type() protoreflect.EnumType {
	return &file_request_oco_order_proto_enumTypes[0]
}

func (x RequestOCOOrder_TransactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RequestOCOOrder_TransactionType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RequestOCOOrder_TransactionType(num)
	return nil
}

// Deprecated: Use RequestOCOOrder_TransactionType.Descriptor instead.
func (RequestOCOOrder_TransactionType) EnumDescriptor() ([]byte, []int) {
	return file_request_oco_order_proto_rawDescGZIP(), []int{0, 0}
}

type RequestOCOOrder_Duration int32

const (
	RequestOCOOrder_DAY RequestOCOOrder_Duration = 1
	RequestOCOOrder_GTC RequestOCOOrder_Duration = 2
	RequestOCOOrder_IOC RequestOCOOrder_Duration = 3
	RequestOCOOrder_FOK RequestOCOOrder_Duration = 4
)

// Enum value maps for RequestOCOOrder_Duration.
var (
	RequestOCOOrder_Duration_name = map[int32]string{
		1: "DAY",
		2: "GTC",
		3: "IOC",
		4: "FOK",
	}
	RequestOCOOrder_Duration_value = map[string]int32{
		"DAY": 1,
		"GTC": 2,
		"IOC": 3,
		"FOK": 4,
	}
)

func (x RequestOCOOrder_Duration) Enum() *RequestOCOOrder_Duration {
	p := new(RequestOCOOrder_Duration)
	*p = x
	return p
}

func (x RequestOCOOrder_Duration) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestOCOOrder_Duration) Descriptor() protoreflect.EnumDescriptor {
	return file_request_oco_order_proto_enumTypes[1].Descriptor()
}

func (RequestOCOOrder_Duration) Type() protoreflect.EnumType {
	return &file_request_oco_order_proto_enumTypes[1]
}

func (x RequestOCOOrder_Duration) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RequestOCOOrder_Duration) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RequestOCOOrder_Duration(num)
	return nil
}

// Deprecated: Use RequestOCOOrder_Duration.Descriptor instead.
func (RequestOCOOrder_Duration) EnumDescriptor() ([]byte, []int) {
	return file_request_oco_order_proto_rawDescGZIP(), []int{0, 1}
}

type RequestOCOOrder_PriceType int32

const (
	RequestOCOOrder_LIMIT       RequestOCOOrder_PriceType = 1
	RequestOCOOrder_MARKET      RequestOCOOrder_PriceType = 2
	RequestOCOOrder_STOP_LIMIT  RequestOCOOrder_PriceType = 3
	RequestOCOOrder_STOP_MARKET RequestOCOOrder_PriceType = 4
)

// Enum value maps for RequestOCOOrder_PriceType.
var (
	RequestOCOOrder_PriceType_name = map[int32]string{
		1: "LIMIT",
		2: "MARKET",
		3: "STOP_LIMIT",
		4: "STOP_MARKET",
	}
	RequestOCOOrder_PriceType_value = map[string]int32{
		"LIMIT":       1,
		"MARKET":      2,
		"STOP_LIMIT":  3,
		"STOP_MARKET": 4,
	}
)

func (x RequestOCOOrder_PriceType) Enum() *RequestOCOOrder_PriceType {
	p := new(RequestOCOOrder_PriceType)
	*p = x
	return p
}

func (x RequestOCOOrder_PriceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestOCOOrder_PriceType) Descriptor() protoreflect.EnumDescriptor {
	return file_request_oco_order_proto_enumTypes[2].Descriptor()
}

func (RequestOCOOrder_PriceType) Type() protoreflect.EnumType {
	return &file_request_oco_order_proto_enumTypes[2]
}

func (x RequestOCOOrder_PriceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RequestOCOOrder_PriceType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RequestOCOOrder_PriceType(num)
	return nil
}

// Deprecated: Use RequestOCOOrder_PriceType.Descriptor instead.
func (RequestOCOOrder_PriceType) EnumDescriptor() ([]byte, []int) {
	return file_request_oco_order_proto_rawDescGZIP(), []int{0, 2}
}

type RequestOCOOrder_OrderPlacement int32

const (
	RequestOCOOrder_MANUAL RequestOCOOrder_OrderPlacement = 1
	RequestOCOOrder_AUTO   RequestOCOOrder_OrderPlacement = 2
)

// Enum value maps for RequestOCOOrder_OrderPlacement.
var (
	RequestOCOOrder_OrderPlacement_name = map[int32]string{
		1: "MANUAL",
		2: "AUTO",
	}
	RequestOCOOrder_OrderPlacement_value = map[string]int32{
		"MANUAL": 1,
		"AUTO":   2,
	}
)

func (x RequestOCOOrder_OrderPlacement) Enum() *RequestOCOOrder_OrderPlacement {
	p := new(RequestOCOOrder_OrderPlacement)
	*p = x
	return p
}

func (x RequestOCOOrder_OrderPlacement) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestOCOOrder_OrderPlacement) Descriptor() protoreflect.EnumDescriptor {
	return file_request_oco_order_proto_enumTypes[3].Descriptor()
}

func (RequestOCOOrder_OrderPlacement) Type() protoreflect.EnumType {
	return &file_request_oco_order_proto_enumTypes[3]
}

func (x RequestOCOOrder_OrderPlacement) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RequestOCOOrder_OrderPlacement) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RequestOCOOrder_OrderPlacement(num)
	return nil
}

// Deprecated: Use RequestOCOOrder_OrderPlacement.Descriptor instead.
func (RequestOCOOrder_OrderPlacement) EnumDescriptor() ([]byte, []int) {
	return file_request_oco_order_proto_rawDescGZIP(), []int{0, 3}
}

type RequestOCOOrder struct {
	state           protoimpl.MessageState            `protogen:"open.v1"`
	TemplateId      *int32                            `protobuf:"varint,154467,req,name=template_id,json=templateId" json:"template_id,omitempty"`
	UserMsg         []string                          `protobuf:"bytes,132760,rep,name=user_msg,json=userMsg" json:"user_msg,omitempty"`
	UserTag         []string                          `protobuf:"bytes,154119,rep,name=user_tag,json=userTag" json:"user_tag,omitempty"`
	WindowName      []string                          `protobuf:"bytes,154629,rep,name=window_name,json=windowName" json:"window_name,omitempty"`
	FcmId           *string                           `protobuf:"bytes,154013,opt,name=fcm_id,json=fcmId" json:"fcm_id,omitempty"`
	IbId            *string                           `protobuf:"bytes,154014,opt,name=ib_id,json=ibId" json:"ib_id,omitempty"`
	AccountId       *string                           `protobuf:"bytes,154008,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
	Symbol          []string                          `protobuf:"bytes,110100,rep,name=symbol" json:"symbol,omitempty"`
	Exchange        []string                          `protobuf:"bytes,110101,rep,name=exchange" json:"exchange,omitempty"`
	Quantity        []int32                           `protobuf:"varint,112004,rep,name=quantity" json:"quantity,omitempty"`
	Price           []float64                         `protobuf:"fixed64,110306,rep,name=price" json:"price,omitempty"`
	TriggerPrice    []float64                         `protobuf:"fixed64,149247,rep,name=trigger_price,json=triggerPrice" json:"trigger_price,omitempty"`
	TransactionType []RequestOCOOrder_TransactionType `protobuf:"varint,112003,rep,name=transaction_type,json=transactionType,enum=rti.RequestOCOOrder_TransactionType" json:"transaction_type,omitempty"`
	Duration        []RequestOCOOrder_Duration        `protobuf:"varint,112005,rep,name=duration,enum=rti.RequestOCOOrder_Duration" json:"duration,omitempty"`
	PriceType       []RequestOCOOrder_PriceType       `protobuf:"varint,112008,rep,name=price_type,json=priceType,enum=rti.RequestOCOOrder_PriceType" json:"price_type,omitempty"`
	TradeRoute      []string                          `protobuf:"bytes,112016,rep,name=trade_route,json=tradeRoute" json:"trade_route,omitempty"`
	ManualOrAuto    []RequestOCOOrder_OrderPlacement  `protobuf:"varint,154710,rep,name=manual_or_auto,json=manualOrAuto,enum=rti.RequestOCOOrder_OrderPlacement" json:"manual_or_auto,omitempty"`
	TrailingStop    []bool                            `protobuf:"varint,157063,rep,name=trailing_stop,json=trailingStop" json:"trailing_stop,omitempty"`
	TrailByTicks    []int32                           `protobuf:"varint,157064,rep,name=trail_by_ticks,json=trailByTicks" json:"trail_by_ticks,omitempty"`
	TrailByPriceId  []int32                           `protobuf:"varint,157065,rep,name=trail_by_price_id,json=trailByPriceId" json:"trail_by_price_id,omitempty"`
	CancelAtSsboe   *int32                            `protobuf:"varint,157085,opt,name=cancel_at_ssboe,json=cancelAtSsboe" json:"cancel_at_ssboe,omitempty"`
	CancelAtUsecs   *int32                            `protobuf:"varint,157086,opt,name=cancel_at_usecs,json=cancelAtUsecs" json:"cancel_at_usecs,omitempty"`
	CancelAfterSecs *int32                            `protobuf:"varint,154488,opt,name=cancel_after_secs,json=cancelAfterSecs" json:"cancel_after_secs,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RequestOCOOrder) Reset() {
	*x = RequestOCOOrder{}
	mi := &file_request_oco_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestOCOOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestOCOOrder) ProtoMessage() {}

func (x *RequestOCOOrder) ProtoReflect() protoreflect.Message {
	mi := &file_request_oco_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestOCOOrder.ProtoReflect.Descriptor instead.
func (*RequestOCOOrder) Descriptor() ([]byte, []int) {
	return file_request_oco_order_proto_rawDescGZIP(), []int{0}
}

func (x *RequestOCOOrder) GetTemplateId() int32 {
	if x != nil && x.TemplateId != nil {
		return *x.TemplateId
	}
	return 0
}

func (x *RequestOCOOrder) GetUserMsg() []string {
	if x != nil {
		return x.UserMsg
	}
	return nil
}

func (x *RequestOCOOrder) GetUserTag() []string {
	if x != nil {
		return x.UserTag
	}
	return nil
}

func (x *RequestOCOOrder) GetWindowName() []string {
	if x != nil {
		return x.WindowName
	}
	return nil
}

func (x *RequestOCOOrder) GetFcmId() string {
	if x != nil && x.FcmId != nil {
		return *x.FcmId
	}
	return ""
}

func (x *RequestOCOOrder) GetIbId() string {
	if x != nil && x.IbId != nil {
		return *x.IbId
	}
	return ""
}

func (x *RequestOCOOrder) GetAccountId() string {
	if x != nil && x.AccountId != nil {
		return *x.AccountId
	}
	return ""
}

func (x *RequestOCOOrder) GetSymbol() []string {
	if x != nil {
		return x.Symbol
	}
	return nil
}

func (x *RequestOCOOrder) GetExchange() []string {
	if x != nil {
		return x.Exchange
	}
	return nil
}

func (x *RequestOCOOrder) GetQuantity() []int32 {
	if x != nil {
		return x.Quantity
	}
	return nil
}

func (x *RequestOCOOrder) GetPrice() []float64 {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *RequestOCOOrder) GetTriggerPrice() []float64 {
	if x != nil {
		return x.TriggerPrice
	}
	return nil
}

func (x *RequestOCOOrder) GetTransactionType() []RequestOCOOrder_TransactionType {
	if x != nil {
		return x.TransactionType
	}
	return nil
}

func (x *RequestOCOOrder) GetDuration() []RequestOCOOrder_Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *RequestOCOOrder) GetPriceType() []RequestOCOOrder_PriceType {
	if x != nil {
		return x.PriceType
	}
	return nil
}

func (x *RequestOCOOrder) GetTradeRoute() []string {
	if x != nil {
		return x.TradeRoute
	}
	return nil
}

func (x *RequestOCOOrder) GetManualOrAuto() []RequestOCOOrder_OrderPlacement {
	if x != nil {
		return x.ManualOrAuto
	}
	return nil
}

func (x *RequestOCOOrder) GetTrailingStop() []bool {
	if x != nil {
		return x.TrailingStop
	}
	return nil
}

func (x *RequestOCOOrder) GetTrailByTicks() []int32 {
	if x != nil {
		return x.TrailByTicks
	}
	return nil
}

func (x *RequestOCOOrder) GetTrailByPriceId() []int32 {
	if x != nil {
		return x.TrailByPriceId
	}
	return nil
}

func (x *RequestOCOOrder) GetCancelAtSsboe() int32 {
	if x != nil && x.CancelAtSsboe != nil {
		return *x.CancelAtSsboe
	}
	return 0
}

func (x *RequestOCOOrder) GetCancelAtUsecs() int32 {
	if x != nil && x.CancelAtUsecs != nil {
		return *x.CancelAtUsecs
	}
	return 0
}

func (x *RequestOCOOrder) GetCancelAfterSecs() int32 {
	if x != nil && x.CancelAfterSecs != nil {
		return *x.CancelAfterSecs
	}
	return 0
}

var File_request_oco_order_proto protoreflect.FileDescriptor

const file_request_oco_order_proto_rawDesc = "" +
	"\n" +
	"\x17request_oco_order.proto\x12\x03rti\"\xf9\b\n" +
	"\x0fRequestOCOOrder\x12!\n" +
	"\vtemplate_id\x18\xe3\xb6\t \x02(\x05R\n" +
	"templateId\x12\x1b\n" +
	"\buser_msg\x18\x98\x8d\b \x03(\tR\auserMsg\x12\x1b\n" +
	"\buser_tag\x18\x87\xb4\t \x03(\tR\auserTag\x12!\n" +
	"\vwindow_name\x18\x85\xb8\t \x03(\tR\n" +
	"windowName\x12\x17\n" +
	"\x06fcm_id\x18\x9d\xb3\t \x01(\tR\x05fcmId\x12\x15\n" +
	"\x05ib_id\x18\x9e\xb3\t \x01(\tR\x04ibId\x12\x1f\n" +
	"\n" +
	"account_id\x18\x98\xb3\t \x01(\tR\taccountId\x12\x18\n" +
	"\x06symbol\x18\x94\xdc\x06 \x03(\tR\x06symbol\x12\x1c\n" +
	"\bexchange\x18\x95\xdc\x06 \x03(\tR\bexchange\x12\x1c\n" +
	"\bquantity\x18\x84\xeb\x06 \x03(\x05R\bquantity\x12\x16\n" +
	"\x05price\x18\xe2\xdd\x06 \x03(\x01R\x05price\x12%\n" +
	"\rtrigger_price\x18\xff\x8d\t \x03(\x01R\ftriggerPrice\x12Q\n" +
	"\x10transaction_type\x18\x83\xeb\x06 \x03(\x0e2$.rti.RequestOCOOrder.TransactionTypeR\x0ftransactionType\x12;\n" +
	"\bduration\x18\x85\xeb\x06 \x03(\x0e2\x1d.rti.RequestOCOOrder.DurationR\bduration\x12?\n" +
	"\n" +
	"price_type\x18\x88\xeb\x06 \x03(\x0e2\x1e.rti.RequestOCOOrder.PriceTypeR\tpriceType\x12!\n" +
	"\vtrade_route\x18\x90\xeb\x06 \x03(\tR\n" +
	"tradeRoute\x12K\n" +
	"\x0emanual_or_auto\x18ָ\t \x03(\x0e2#.rti.RequestOCOOrder.OrderPlacementR\fmanualOrAuto\x12%\n" +
	"\rtrailing_stop\x18\x87\xcb\t \x03(\bR\ftrailingStop\x12&\n" +
	"\x0etrail_by_ticks\x18\x88\xcb\t \x03(\x05R\ftrailByTicks\x12+\n" +
	"\x11trail_by_price_id\x18\x89\xcb\t \x03(\x05R\x0etrailByPriceId\x12(\n" +
	"\x0fcancel_at_ssboe\x18\x9d\xcb\t \x01(\x05R\rcancelAtSsboe\x12(\n" +
	"\x0fcancel_at_usecs\x18\x9e\xcb\t \x01(\x05R\rcancelAtUsecs\x12,\n" +
	"\x11cancel_after_secs\x18\xf8\xb6\t \x01(\x05R\x0fcancelAfterSecs\"$\n" +
	"\x0fTransactionType\x12\a\n" +
	"\x03BUY\x10\x01\x12\b\n" +
	"\x04SELL\x10\x02\".\n" +
	"\bDuration\x12\a\n" +
	"\x03DAY\x10\x01\x12\a\n" +
	"\x03GTC\x10\x02\x12\a\n" +
	"\x03IOC\x10\x03\x12\a\n" +
	"\x03FOK\x10\x04\"C\n" +
	"\tPriceType\x12\t\n" +
	"\x05LIMIT\x10\x01\x12\n" +
	"\n" +
	"\x06MARKET\x10\x02\x12\x0e\n" +
	"\n" +
	"STOP_LIMIT\x10\x03\x12\x0f\n" +
	"\vSTOP_MARKET\x10\x04\"&\n" +
	"\x0eOrderPlacement\x12\n" +
	"\n" +
	"\x06MANUAL\x10\x01\x12\b\n" +
	"\x04AUTO\x10\x02B\x1eZ\x1cquant/extensions/rithmic/api"

var (
	file_request_oco_order_proto_rawDescOnce sync.Once
	file_request_oco_order_proto_rawDescData []byte
)

func file_request_oco_order_proto_rawDescGZIP() []byte {
	file_request_oco_order_proto_rawDescOnce.Do(func() {
		file_request_oco_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_request_oco_order_proto_rawDesc), len(file_request_oco_order_proto_rawDesc)))
	})
	return file_request_oco_order_proto_rawDescData
}

var file_request_oco_order_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_request_oco_order_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_request_oco_order_proto_goTypes = []any{
	(RequestOCOOrder_TransactionType)(0), // 0: rti.RequestOCOOrder.TransactionType
	(RequestOCOOrder_Duration)(0),        // 1: rti.RequestOCOOrder.Duration
	(RequestOCOOrder_PriceType)(0),       // 2: rti.RequestOCOOrder.PriceType
	(RequestOCOOrder_OrderPlacement)(0),  // 3: rti.RequestOCOOrder.OrderPlacement
	(*RequestOCOOrder)(nil),              // 4: rti.RequestOCOOrder
}
var file_request_oco_order_proto_depIdxs = []int32{
	0, // 0: rti.RequestOCOOrder.transaction_type:type_name -> rti.RequestOCOOrder.TransactionType
	1, // 1: rti.RequestOCOOrder.duration:type_name -> rti.RequestOCOOrder.Duration
	2, // 2: rti.RequestOCOOrder.price_type:type_name -> rti.RequestOCOOrder.PriceType
	3, // 3: rti.RequestOCOOrder.manual_or_auto:type_name -> rti.RequestOCOOrder.OrderPlacement
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_request_oco_order_proto_init() }
func file_request_oco_order_proto_init() {
	if File_request_oco_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_request_oco_order_proto_rawDesc), len(file_request_oco_order_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_request_oco_order_proto_goTypes,
		DependencyIndexes: file_request_oco_order_proto_depIdxs,
		EnumInfos:         file_request_oco_order_proto_enumTypes,
		MessageInfos:      file_request_oco_order_proto_msgTypes,
	}.Build()
	File_request_oco_order_proto = out.File
	file_request_oco_order_proto_goTypes = nil
	file_request_oco_order_proto_depIdxs = nil
}
