// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: request_account_list.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestAccountList_UserType int32

const (
	RequestAccountList_USER_TYPE_FCM    RequestAccountList_UserType = 1
	RequestAccountList_USER_TYPE_IB     RequestAccountList_UserType = 2
	RequestAccountList_USER_TYPE_TRADER RequestAccountList_UserType = 3
)

// Enum value maps for RequestAccountList_UserType.
var (
	RequestAccountList_UserType_name = map[int32]string{
		1: "USER_TYPE_FCM",
		2: "USER_TYPE_IB",
		3: "USER_TYPE_TRADER",
	}
	RequestAccountList_UserType_value = map[string]int32{
		"USER_TYPE_FCM":    1,
		"USER_TYPE_IB":     2,
		"USER_TYPE_TRADER": 3,
	}
)

func (x RequestAccountList_UserType) Enum() *RequestAccountList_UserType {
	p := new(RequestAccountList_UserType)
	*p = x
	return p
}

func (x RequestAccountList_UserType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RequestAccountList_UserType) Descriptor() protoreflect.EnumDescriptor {
	return file_request_account_list_proto_enumTypes[0].Descriptor()
}

func (RequestAccountList_UserType) Type() protoreflect.EnumType {
	return &file_request_account_list_proto_enumTypes[0]
}

func (x RequestAccountList_UserType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *RequestAccountList_UserType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = RequestAccountList_UserType(num)
	return nil
}

// Deprecated: Use RequestAccountList_UserType.Descriptor instead.
func (RequestAccountList_UserType) EnumDescriptor() ([]byte, []int) {
	return file_request_account_list_proto_rawDescGZIP(), []int{0, 0}
}

type RequestAccountList struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	TemplateId    *int32                       `protobuf:"varint,154467,req,name=template_id,json=templateId" json:"template_id,omitempty"`                                // PB_OFFSET + MNM_TEMPLATE_ID
	UserMsg       []string                     `protobuf:"bytes,132760,rep,name=user_msg,json=userMsg" json:"user_msg,omitempty"`                                          // PB_OFFSET + MNM_USER_MSG
	FcmId         *string                      `protobuf:"bytes,154013,opt,name=fcm_id,json=fcmId" json:"fcm_id,omitempty"`                                                // PB_OFFSET + MNM_FCM_ID
	IbId          *string                      `protobuf:"bytes,154014,opt,name=ib_id,json=ibId" json:"ib_id,omitempty"`                                                   // PB_OFFSET + MNM_IB_ID
	UserType      *RequestAccountList_UserType `protobuf:"varint,154036,opt,name=user_type,json=userType,enum=rti.RequestAccountList_UserType" json:"user_type,omitempty"` // PB_OFFSET + MNM_USER_TYPE
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestAccountList) Reset() {
	*x = RequestAccountList{}
	mi := &file_request_account_list_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestAccountList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestAccountList) ProtoMessage() {}

func (x *RequestAccountList) ProtoReflect() protoreflect.Message {
	mi := &file_request_account_list_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestAccountList.ProtoReflect.Descriptor instead.
func (*RequestAccountList) Descriptor() ([]byte, []int) {
	return file_request_account_list_proto_rawDescGZIP(), []int{0}
}

func (x *RequestAccountList) GetTemplateId() int32 {
	if x != nil && x.TemplateId != nil {
		return *x.TemplateId
	}
	return 0
}

func (x *RequestAccountList) GetUserMsg() []string {
	if x != nil {
		return x.UserMsg
	}
	return nil
}

func (x *RequestAccountList) GetFcmId() string {
	if x != nil && x.FcmId != nil {
		return *x.FcmId
	}
	return ""
}

func (x *RequestAccountList) GetIbId() string {
	if x != nil && x.IbId != nil {
		return *x.IbId
	}
	return ""
}

func (x *RequestAccountList) GetUserType() RequestAccountList_UserType {
	if x != nil && x.UserType != nil {
		return *x.UserType
	}
	return RequestAccountList_USER_TYPE_FCM
}

var File_request_account_list_proto protoreflect.FileDescriptor

const file_request_account_list_proto_rawDesc = "" +
	"\n" +
	"\x1arequest_account_list.proto\x12\x03rti\"\x8c\x02\n" +
	"\x12RequestAccountList\x12!\n" +
	"\vtemplate_id\x18\xe3\xb6\t \x02(\x05R\n" +
	"templateId\x12\x1b\n" +
	"\buser_msg\x18\x98\x8d\b \x03(\tR\auserMsg\x12\x17\n" +
	"\x06fcm_id\x18\x9d\xb3\t \x01(\tR\x05fcmId\x12\x15\n" +
	"\x05ib_id\x18\x9e\xb3\t \x01(\tR\x04ibId\x12?\n" +
	"\tuser_type\x18\xb4\xb3\t \x01(\x0e2 .rti.RequestAccountList.UserTypeR\buserType\"E\n" +
	"\bUserType\x12\x11\n" +
	"\rUSER_TYPE_FCM\x10\x01\x12\x10\n" +
	"\fUSER_TYPE_IB\x10\x02\x12\x14\n" +
	"\x10USER_TYPE_TRADER\x10\x03B\x1eZ\x1cquant/extensions/rithmic/api"

var (
	file_request_account_list_proto_rawDescOnce sync.Once
	file_request_account_list_proto_rawDescData []byte
)

func file_request_account_list_proto_rawDescGZIP() []byte {
	file_request_account_list_proto_rawDescOnce.Do(func() {
		file_request_account_list_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_request_account_list_proto_rawDesc), len(file_request_account_list_proto_rawDesc)))
	})
	return file_request_account_list_proto_rawDescData
}

var file_request_account_list_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_request_account_list_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_request_account_list_proto_goTypes = []any{
	(RequestAccountList_UserType)(0), // 0: rti.RequestAccountList.UserType
	(*RequestAccountList)(nil),       // 1: rti.RequestAccountList
}
var file_request_account_list_proto_depIdxs = []int32{
	0, // 0: rti.RequestAccountList.user_type:type_name -> rti.RequestAccountList.UserType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_request_account_list_proto_init() }
func file_request_account_list_proto_init() {
	if File_request_account_list_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_request_account_list_proto_rawDesc), len(file_request_account_list_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_request_account_list_proto_goTypes,
		DependencyIndexes: file_request_account_list_proto_depIdxs,
		EnumInfos:         file_request_account_list_proto_enumTypes,
		MessageInfos:      file_request_account_list_proto_msgTypes,
	}.Build()
	File_request_account_list_proto = out.File
	file_request_account_list_proto_goTypes = nil
	file_request_account_list_proto_depIdxs = nil
}
