// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: response_account_list.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseAccountList struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	TemplateId                   *int32                 `protobuf:"varint,154467,req,name=template_id,json=templateId" json:"template_id,omitempty"`
	UserMsg                      []string               `protobuf:"bytes,132760,rep,name=user_msg,json=userMsg" json:"user_msg,omitempty"`
	RqHandlerRpCode              []string               `protobuf:"bytes,132764,rep,name=rq_handler_rp_code,json=rqHandlerRpCode" json:"rq_handler_rp_code,omitempty"`
	RpCode                       []string               `protobuf:"bytes,132766,rep,name=rp_code,json=rpCode" json:"rp_code,omitempty"`
	FcmId                        *string                `protobuf:"bytes,154013,opt,name=fcm_id,json=fcmId" json:"fcm_id,omitempty"`
	IbId                         *string                `protobuf:"bytes,154014,opt,name=ib_id,json=ibId" json:"ib_id,omitempty"`
	AccountId                    *string                `protobuf:"bytes,154008,opt,name=account_id,json=accountId" json:"account_id,omitempty"`
	AccountName                  *string                `protobuf:"bytes,154002,opt,name=account_name,json=accountName" json:"account_name,omitempty"`
	AccountCurrency              *string                `protobuf:"bytes,154383,opt,name=account_currency,json=accountCurrency" json:"account_currency,omitempty"`
	LossLimit                    *string                `protobuf:"bytes,154019,opt,name=loss_limit,json=lossLimit" json:"loss_limit,omitempty"`
	AccountCreationSsboe         *int32                 `protobuf:"varint,153171,opt,name=account_creation_ssboe,json=accountCreationSsboe" json:"account_creation_ssboe,omitempty"`
	AccountCreationUsecs         *int32                 `protobuf:"varint,153172,opt,name=account_creation_usecs,json=accountCreationUsecs" json:"account_creation_usecs,omitempty"`
	AccountAutoLiquidate         *string                `protobuf:"bytes,131035,opt,name=account_auto_liquidate,json=accountAutoLiquidate" json:"account_auto_liquidate,omitempty"`
	AutoLiqThresholdCurrentValue *string                `protobuf:"bytes,131040,opt,name=auto_liq_threshold_current_value,json=autoLiqThresholdCurrentValue" json:"auto_liq_threshold_current_value,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *ResponseAccountList) Reset() {
	*x = ResponseAccountList{}
	mi := &file_response_account_list_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseAccountList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseAccountList) ProtoMessage() {}

func (x *ResponseAccountList) ProtoReflect() protoreflect.Message {
	mi := &file_response_account_list_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseAccountList.ProtoReflect.Descriptor instead.
func (*ResponseAccountList) Descriptor() ([]byte, []int) {
	return file_response_account_list_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseAccountList) GetTemplateId() int32 {
	if x != nil && x.TemplateId != nil {
		return *x.TemplateId
	}
	return 0
}

func (x *ResponseAccountList) GetUserMsg() []string {
	if x != nil {
		return x.UserMsg
	}
	return nil
}

func (x *ResponseAccountList) GetRqHandlerRpCode() []string {
	if x != nil {
		return x.RqHandlerRpCode
	}
	return nil
}

func (x *ResponseAccountList) GetRpCode() []string {
	if x != nil {
		return x.RpCode
	}
	return nil
}

func (x *ResponseAccountList) GetFcmId() string {
	if x != nil && x.FcmId != nil {
		return *x.FcmId
	}
	return ""
}

func (x *ResponseAccountList) GetIbId() string {
	if x != nil && x.IbId != nil {
		return *x.IbId
	}
	return ""
}

func (x *ResponseAccountList) GetAccountId() string {
	if x != nil && x.AccountId != nil {
		return *x.AccountId
	}
	return ""
}

func (x *ResponseAccountList) GetAccountName() string {
	if x != nil && x.AccountName != nil {
		return *x.AccountName
	}
	return ""
}

func (x *ResponseAccountList) GetAccountCurrency() string {
	if x != nil && x.AccountCurrency != nil {
		return *x.AccountCurrency
	}
	return ""
}

func (x *ResponseAccountList) GetLossLimit() string {
	if x != nil && x.LossLimit != nil {
		return *x.LossLimit
	}
	return ""
}

func (x *ResponseAccountList) GetAccountCreationSsboe() int32 {
	if x != nil && x.AccountCreationSsboe != nil {
		return *x.AccountCreationSsboe
	}
	return 0
}

func (x *ResponseAccountList) GetAccountCreationUsecs() int32 {
	if x != nil && x.AccountCreationUsecs != nil {
		return *x.AccountCreationUsecs
	}
	return 0
}

func (x *ResponseAccountList) GetAccountAutoLiquidate() string {
	if x != nil && x.AccountAutoLiquidate != nil {
		return *x.AccountAutoLiquidate
	}
	return ""
}

func (x *ResponseAccountList) GetAutoLiqThresholdCurrentValue() string {
	if x != nil && x.AutoLiqThresholdCurrentValue != nil {
		return *x.AutoLiqThresholdCurrentValue
	}
	return ""
}

var File_response_account_list_proto protoreflect.FileDescriptor

const file_response_account_list_proto_rawDesc = "" +
	"\n" +
	"\x1bresponse_account_list.proto\x12\x03rti\"\xd5\x04\n" +
	"\x13ResponseAccountList\x12!\n" +
	"\vtemplate_id\x18\xe3\xb6\t \x02(\x05R\n" +
	"templateId\x12\x1b\n" +
	"\buser_msg\x18\x98\x8d\b \x03(\tR\auserMsg\x12-\n" +
	"\x12rq_handler_rp_code\x18\x9c\x8d\b \x03(\tR\x0frqHandlerRpCode\x12\x19\n" +
	"\arp_code\x18\x9e\x8d\b \x03(\tR\x06rpCode\x12\x17\n" +
	"\x06fcm_id\x18\x9d\xb3\t \x01(\tR\x05fcmId\x12\x15\n" +
	"\x05ib_id\x18\x9e\xb3\t \x01(\tR\x04ibId\x12\x1f\n" +
	"\n" +
	"account_id\x18\x98\xb3\t \x01(\tR\taccountId\x12#\n" +
	"\faccount_name\x18\x92\xb3\t \x01(\tR\vaccountName\x12+\n" +
	"\x10account_currency\x18\x8f\xb6\t \x01(\tR\x0faccountCurrency\x12\x1f\n" +
	"\n" +
	"loss_limit\x18\xa3\xb3\t \x01(\tR\tlossLimit\x126\n" +
	"\x16account_creation_ssboe\x18Ӭ\t \x01(\x05R\x14accountCreationSsboe\x126\n" +
	"\x16account_creation_usecs\x18Ԭ\t \x01(\x05R\x14accountCreationUsecs\x126\n" +
	"\x16account_auto_liquidate\x18\xdb\xff\a \x01(\tR\x14accountAutoLiquidate\x12H\n" +
	" auto_liq_threshold_current_value\x18\xe0\xff\a \x01(\tR\x1cautoLiqThresholdCurrentValueB\x1eZ\x1cquant/extensions/rithmic/api"

var (
	file_response_account_list_proto_rawDescOnce sync.Once
	file_response_account_list_proto_rawDescData []byte
)

func file_response_account_list_proto_rawDescGZIP() []byte {
	file_response_account_list_proto_rawDescOnce.Do(func() {
		file_response_account_list_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_response_account_list_proto_rawDesc), len(file_response_account_list_proto_rawDesc)))
	})
	return file_response_account_list_proto_rawDescData
}

var file_response_account_list_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_response_account_list_proto_goTypes = []any{
	(*ResponseAccountList)(nil), // 0: rti.ResponseAccountList
}
var file_response_account_list_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_response_account_list_proto_init() }
func file_response_account_list_proto_init() {
	if File_response_account_list_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_response_account_list_proto_rawDesc), len(file_response_account_list_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_response_account_list_proto_goTypes,
		DependencyIndexes: file_response_account_list_proto_depIdxs,
		MessageInfos:      file_response_account_list_proto_msgTypes,
	}.Build()
	File_response_account_list_proto = out.File
	file_response_account_list_proto_goTypes = nil
	file_response_account_list_proto_depIdxs = nil
}
