// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: response_front_month_contract.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseFrontMonthContract struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TemplateId         *int32                 `protobuf:"varint,154467,req,name=template_id,json=templateId" json:"template_id,omitempty"`                             // PB_OFFSET + MNM_TEMPLATE_ID
	UserMsg            []string               `protobuf:"bytes,132760,rep,name=user_msg,json=userMsg" json:"user_msg,omitempty"`                                       // PB_OFFSET + MNM_USER_MSG
	RpCode             []string               `protobuf:"bytes,132766,rep,name=rp_code,json=rpCode" json:"rp_code,omitempty"`                                          // PB_OFFSET + MNM_RESPONSE_CODE
	Symbol             *string                `protobuf:"bytes,110100,opt,name=symbol" json:"symbol,omitempty"`                                                        // PB_OFFSET + MNM_SYMBOL
	Exchange           *string                `protobuf:"bytes,110101,opt,name=exchange" json:"exchange,omitempty"`                                                    // PB_OFFSET + MNM_EXCHANGE
	IsFrontMonthSymbol *bool                  `protobuf:"varint,149166,opt,name=is_front_month_symbol,json=isFrontMonthSymbol" json:"is_front_month_symbol,omitempty"` // PB_OFFSET + MNM_STATUS_INDICATOR
	SymbolName         *string                `protobuf:"bytes,100003,opt,name=symbol_name,json=symbolName" json:"symbol_name,omitempty"`                              // PB_OFFSET + MNM_SYMBOL_NAME
	TradingSymbol      *string                `protobuf:"bytes,157095,opt,name=trading_symbol,json=tradingSymbol" json:"trading_symbol,omitempty"`                     // PB_OFFSET + MNM_TRADING_SYMBOL
	TradingExchange    *string                `protobuf:"bytes,157096,opt,name=trading_exchange,json=tradingExchange" json:"trading_exchange,omitempty"`               // PB_OFFSET + MNM_TRADING_EXCHANGE
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ResponseFrontMonthContract) Reset() {
	*x = ResponseFrontMonthContract{}
	mi := &file_response_front_month_contract_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseFrontMonthContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseFrontMonthContract) ProtoMessage() {}

func (x *ResponseFrontMonthContract) ProtoReflect() protoreflect.Message {
	mi := &file_response_front_month_contract_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseFrontMonthContract.ProtoReflect.Descriptor instead.
func (*ResponseFrontMonthContract) Descriptor() ([]byte, []int) {
	return file_response_front_month_contract_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseFrontMonthContract) GetTemplateId() int32 {
	if x != nil && x.TemplateId != nil {
		return *x.TemplateId
	}
	return 0
}

func (x *ResponseFrontMonthContract) GetUserMsg() []string {
	if x != nil {
		return x.UserMsg
	}
	return nil
}

func (x *ResponseFrontMonthContract) GetRpCode() []string {
	if x != nil {
		return x.RpCode
	}
	return nil
}

func (x *ResponseFrontMonthContract) GetSymbol() string {
	if x != nil && x.Symbol != nil {
		return *x.Symbol
	}
	return ""
}

func (x *ResponseFrontMonthContract) GetExchange() string {
	if x != nil && x.Exchange != nil {
		return *x.Exchange
	}
	return ""
}

func (x *ResponseFrontMonthContract) GetIsFrontMonthSymbol() bool {
	if x != nil && x.IsFrontMonthSymbol != nil {
		return *x.IsFrontMonthSymbol
	}
	return false
}

func (x *ResponseFrontMonthContract) GetSymbolName() string {
	if x != nil && x.SymbolName != nil {
		return *x.SymbolName
	}
	return ""
}

func (x *ResponseFrontMonthContract) GetTradingSymbol() string {
	if x != nil && x.TradingSymbol != nil {
		return *x.TradingSymbol
	}
	return ""
}

func (x *ResponseFrontMonthContract) GetTradingExchange() string {
	if x != nil && x.TradingExchange != nil {
		return *x.TradingExchange
	}
	return ""
}

var File_response_front_month_contract_proto protoreflect.FileDescriptor

const file_response_front_month_contract_proto_rawDesc = "" +
	"\n" +
	"#response_front_month_contract.proto\x12\x03rti\"\xdd\x02\n" +
	"\x1aResponseFrontMonthContract\x12!\n" +
	"\vtemplate_id\x18\xe3\xb6\t \x02(\x05R\n" +
	"templateId\x12\x1b\n" +
	"\buser_msg\x18\x98\x8d\b \x03(\tR\auserMsg\x12\x19\n" +
	"\arp_code\x18\x9e\x8d\b \x03(\tR\x06rpCode\x12\x18\n" +
	"\x06symbol\x18\x94\xdc\x06 \x01(\tR\x06symbol\x12\x1c\n" +
	"\bexchange\x18\x95\xdc\x06 \x01(\tR\bexchange\x123\n" +
	"\x15is_front_month_symbol\x18\xae\x8d\t \x01(\bR\x12isFrontMonthSymbol\x12!\n" +
	"\vsymbol_name\x18\xa3\x8d\x06 \x01(\tR\n" +
	"symbolName\x12'\n" +
	"\x0etrading_symbol\x18\xa7\xcb\t \x01(\tR\rtradingSymbol\x12+\n" +
	"\x10trading_exchange\x18\xa8\xcb\t \x01(\tR\x0ftradingExchangeB\x1eZ\x1cquant/extensions/rithmic/api"

var (
	file_response_front_month_contract_proto_rawDescOnce sync.Once
	file_response_front_month_contract_proto_rawDescData []byte
)

func file_response_front_month_contract_proto_rawDescGZIP() []byte {
	file_response_front_month_contract_proto_rawDescOnce.Do(func() {
		file_response_front_month_contract_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_response_front_month_contract_proto_rawDesc), len(file_response_front_month_contract_proto_rawDesc)))
	})
	return file_response_front_month_contract_proto_rawDescData
}

var file_response_front_month_contract_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_response_front_month_contract_proto_goTypes = []any{
	(*ResponseFrontMonthContract)(nil), // 0: rti.ResponseFrontMonthContract
}
var file_response_front_month_contract_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_response_front_month_contract_proto_init() }
func file_response_front_month_contract_proto_init() {
	if File_response_front_month_contract_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_response_front_month_contract_proto_rawDesc), len(file_response_front_month_contract_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_response_front_month_contract_proto_goTypes,
		DependencyIndexes: file_response_front_month_contract_proto_depIdxs,
		MessageInfos:      file_response_front_month_contract_proto_msgTypes,
	}.Build()
	File_response_front_month_contract_proto = out.File
	file_response_front_month_contract_proto_goTypes = nil
	file_response_front_month_contract_proto_depIdxs = nil
}
