// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: response_account_rms_info.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// below enum is just for reference only, not used in this message
type ResponseAccountRmsInfo_PresenceBits int32

const (
	ResponseAccountRmsInfo_BUY_LIMIT           ResponseAccountRmsInfo_PresenceBits = 1
	ResponseAccountRmsInfo_SELL_LIMIT          ResponseAccountRmsInfo_PresenceBits = 2
	ResponseAccountRmsInfo_LOSS_LIMIT          ResponseAccountRmsInfo_PresenceBits = 4
	ResponseAccountRmsInfo_MAX_ORDER_QUANTITY  ResponseAccountRmsInfo_PresenceBits = 8
	ResponseAccountRmsInfo_MIN_ACCOUNT_BALANCE ResponseAccountRmsInfo_PresenceBits = 16
	ResponseAccountRmsInfo_MIN_MARGIN_BALANCE  ResponseAccountRmsInfo_PresenceBits = 32
	ResponseAccountRmsInfo_ALGORITHM           ResponseAccountRmsInfo_PresenceBits = 64
	ResponseAccountRmsInfo_STATUS              ResponseAccountRmsInfo_PresenceBits = 128
	ResponseAccountRmsInfo_CURRENCY            ResponseAccountRmsInfo_PresenceBits = 256
	ResponseAccountRmsInfo_DEFAULT_COMMISSION  ResponseAccountRmsInfo_PresenceBits = 512
)

// Enum value maps for ResponseAccountRmsInfo_PresenceBits.
var (
	ResponseAccountRmsInfo_PresenceBits_name = map[int32]string{
		1:   "BUY_LIMIT",
		2:   "SELL_LIMIT",
		4:   "LOSS_LIMIT",
		8:   "MAX_ORDER_QUANTITY",
		16:  "MIN_ACCOUNT_BALANCE",
		32:  "MIN_MARGIN_BALANCE",
		64:  "ALGORITHM",
		128: "STATUS",
		256: "CURRENCY",
		512: "DEFAULT_COMMISSION",
	}
	ResponseAccountRmsInfo_PresenceBits_value = map[string]int32{
		"BUY_LIMIT":           1,
		"SELL_LIMIT":          2,
		"LOSS_LIMIT":          4,
		"MAX_ORDER_QUANTITY":  8,
		"MIN_ACCOUNT_BALANCE": 16,
		"MIN_MARGIN_BALANCE":  32,
		"ALGORITHM":           64,
		"STATUS":              128,
		"CURRENCY":            256,
		"DEFAULT_COMMISSION":  512,
	}
)

func (x ResponseAccountRmsInfo_PresenceBits) Enum() *ResponseAccountRmsInfo_PresenceBits {
	p := new(ResponseAccountRmsInfo_PresenceBits)
	*p = x
	return p
}

func (x ResponseAccountRmsInfo_PresenceBits) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseAccountRmsInfo_PresenceBits) Descriptor() protoreflect.EnumDescriptor {
	return file_response_account_rms_info_proto_enumTypes[0].Descriptor()
}

func (ResponseAccountRmsInfo_PresenceBits) Type() protoreflect.EnumType {
	return &file_response_account_rms_info_proto_enumTypes[0]
}

func (x ResponseAccountRmsInfo_PresenceBits) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ResponseAccountRmsInfo_PresenceBits) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ResponseAccountRmsInfo_PresenceBits(num)
	return nil
}

// Deprecated: Use ResponseAccountRmsInfo_PresenceBits.Descriptor instead.
func (ResponseAccountRmsInfo_PresenceBits) EnumDescriptor() ([]byte, []int) {
	return file_response_account_rms_info_proto_rawDescGZIP(), []int{0, 0}
}

type ResponseAccountRmsInfo_AutoLiquidateFlag int32

const (
	ResponseAccountRmsInfo_ENABLED  ResponseAccountRmsInfo_AutoLiquidateFlag = 1
	ResponseAccountRmsInfo_DISABLED ResponseAccountRmsInfo_AutoLiquidateFlag = 2
)

// Enum value maps for ResponseAccountRmsInfo_AutoLiquidateFlag.
var (
	ResponseAccountRmsInfo_AutoLiquidateFlag_name = map[int32]string{
		1: "ENABLED",
		2: "DISABLED",
	}
	ResponseAccountRmsInfo_AutoLiquidateFlag_value = map[string]int32{
		"ENABLED":  1,
		"DISABLED": 2,
	}
)

func (x ResponseAccountRmsInfo_AutoLiquidateFlag) Enum() *ResponseAccountRmsInfo_AutoLiquidateFlag {
	p := new(ResponseAccountRmsInfo_AutoLiquidateFlag)
	*p = x
	return p
}

func (x ResponseAccountRmsInfo_AutoLiquidateFlag) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseAccountRmsInfo_AutoLiquidateFlag) Descriptor() protoreflect.EnumDescriptor {
	return file_response_account_rms_info_proto_enumTypes[1].Descriptor()
}

func (ResponseAccountRmsInfo_AutoLiquidateFlag) Type() protoreflect.EnumType {
	return &file_response_account_rms_info_proto_enumTypes[1]
}

func (x ResponseAccountRmsInfo_AutoLiquidateFlag) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ResponseAccountRmsInfo_AutoLiquidateFlag) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ResponseAccountRmsInfo_AutoLiquidateFlag(num)
	return nil
}

// Deprecated: Use ResponseAccountRmsInfo_AutoLiquidateFlag.Descriptor instead.
func (ResponseAccountRmsInfo_AutoLiquidateFlag) EnumDescriptor() ([]byte, []int) {
	return file_response_account_rms_info_proto_rawDescGZIP(), []int{0, 1}
}

type ResponseAccountRmsInfo struct {
	state                             protoimpl.MessageState                    `protogen:"open.v1"`
	TemplateId                        *int32                                    `protobuf:"varint,154467,req,name=template_id,json=templateId" json:"template_id,omitempty"`                                                                                           // PB_OFFSET + MNM_TEMPLATE_ID
	UserMsg                           []string                                  `protobuf:"bytes,132760,rep,name=user_msg,json=userMsg" json:"user_msg,omitempty"`                                                                                                     // PB_OFFSET + MNM_USER_MSG
	RqHandlerRpCode                   []string                                  `protobuf:"bytes,132764,rep,name=rq_handler_rp_code,json=rqHandlerRpCode" json:"rq_handler_rp_code,omitempty"`                                                                         // PB_OFFSET + MNM_REQUEST_HANDLER_RESPONSE_CODE
	RpCode                            []string                                  `protobuf:"bytes,132766,rep,name=rp_code,json=rpCode" json:"rp_code,omitempty"`                                                                                                        // PB_OFFSET + MNM_RESPONSE_CODE
	PresenceBits                      *uint32                                   `protobuf:"varint,153622,opt,name=presence_bits,json=presenceBits" json:"presence_bits,omitempty"`                                                                                     // PB_OFFSET + MNM_FIELD_PRESENCE_BITS
	FcmId                             *string                                   `protobuf:"bytes,154013,opt,name=fcm_id,json=fcmId" json:"fcm_id,omitempty"`                                                                                                           // PB_OFFSET + MNM_FCM_ID
	IbId                              *string                                   `protobuf:"bytes,154014,opt,name=ib_id,json=ibId" json:"ib_id,omitempty"`                                                                                                              // PB_OFFSET + MNM_IB_ID
	AccountId                         *string                                   `protobuf:"bytes,154008,opt,name=account_id,json=accountId" json:"account_id,omitempty"`                                                                                               // PB_OFFSET + MNM_ACCOUNT_ID
	Currency                          *string                                   `protobuf:"bytes,154383,opt,name=currency" json:"currency,omitempty"`                                                                                                                  // PB_OFFSET + MNM_ACCOUNT_CURRENCY
	Status                            *string                                   `protobuf:"bytes,154003,opt,name=status" json:"status,omitempty"`                                                                                                                      // PB_OFFSET + MNM_ACCOUNT_STATUS
	Algorithm                         *string                                   `protobuf:"bytes,150142,opt,name=algorithm" json:"algorithm,omitempty"`                                                                                                                // PB_OFFSET + MNM_ALGORITHM
	AutoLiquidateCriteria             *string                                   `protobuf:"bytes,131036,opt,name=auto_liquidate_criteria,json=autoLiquidateCriteria" json:"auto_liquidate_criteria,omitempty"`                                                         // PB_OFFSET + MNM_ACCOUNT_AUTO_LIQUIDATE_CRITERIA
	AutoLiquidate                     *ResponseAccountRmsInfo_AutoLiquidateFlag `protobuf:"varint,131035,opt,name=auto_liquidate,json=autoLiquidate,enum=rti.ResponseAccountRmsInfo_AutoLiquidateFlag" json:"auto_liquidate,omitempty"`                                // PB_OFFSET + MNM_ACCOUNT_AUTO_LIQUIDATE
	DisableOnAutoLiquidate            *ResponseAccountRmsInfo_AutoLiquidateFlag `protobuf:"varint,131038,opt,name=disable_on_auto_liquidate,json=disableOnAutoLiquidate,enum=rti.ResponseAccountRmsInfo_AutoLiquidateFlag" json:"disable_on_auto_liquidate,omitempty"` // PB_OFFSET + MNM_DISABLE_ON_AUTO_LIQUIDATE_FLAG
	AutoLiquidateThreshold            *float64                                  `protobuf:"fixed64,131037,opt,name=auto_liquidate_threshold,json=autoLiquidateThreshold" json:"auto_liquidate_threshold,omitempty"`                                                    // PB_OFFSET + MNM_ACCOUNT_AUTO_LIQUIDATE_THRESHOLD
	AutoLiquidateMaxMinAccountBalance *float64                                  `protobuf:"fixed64,131039,opt,name=auto_liquidate_max_min_account_balance,json=autoLiquidateMaxMinAccountBalance" json:"auto_liquidate_max_min_account_balance,omitempty"`             // PB_OFFSET + MNM_AUTO_LIQ_MAX_MIN_ACCOUNT_BALANCE
	LossLimit                         *float64                                  `protobuf:"fixed64,154019,opt,name=loss_limit,json=lossLimit" json:"loss_limit,omitempty"`                                                                                             // PB_OFFSET + MNM_LOSS_LIMIT
	MinAccountBalance                 *float64                                  `protobuf:"fixed64,156968,opt,name=min_account_balance,json=minAccountBalance" json:"min_account_balance,omitempty"`                                                                   // PB_OFFSET + MNM_MINIMUM_ACCOUNT_BALANCE
	MinMarginBalance                  *float64                                  `protobuf:"fixed64,156976,opt,name=min_margin_balance,json=minMarginBalance" json:"min_margin_balance,omitempty"`                                                                      // PB_OFFSET + MNM_MIN_MARGIN_BALANCE
	DefaultCommission                 *float64                                  `protobuf:"fixed64,153368,opt,name=default_commission,json=defaultCommission" json:"default_commission,omitempty"`                                                                     // PB_OFFSET + MNM_DEFAULT_COMMISSION
	BuyLimit                          *int32                                    `protobuf:"varint,154009,opt,name=buy_limit,json=buyLimit" json:"buy_limit,omitempty"`                                                                                                 // PB_OFFSET + MNM_BUY_LIMIT
	MaxOrderQuantity                  *int32                                    `protobuf:"varint,110105,opt,name=max_order_quantity,json=maxOrderQuantity" json:"max_order_quantity,omitempty"`                                                                       // PB_OFFSET + MNM_MAX_LIMIT_QUAN
	SellLimit                         *int32                                    `protobuf:"varint,154035,opt,name=sell_limit,json=sellLimit" json:"sell_limit,omitempty"`                                                                                              // PB_OFFSET + MNM_SELL_LIMIT
	CheckMinAccountBalance            *bool                                     `protobuf:"varint,156972,opt,name=check_min_account_balance,json=checkMinAccountBalance" json:"check_min_account_balance,omitempty"`                                                   // PB_OFFSET + MNM_CHECK_MIN_ACCT_BALANCE
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *ResponseAccountRmsInfo) Reset() {
	*x = ResponseAccountRmsInfo{}
	mi := &file_response_account_rms_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseAccountRmsInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseAccountRmsInfo) ProtoMessage() {}

func (x *ResponseAccountRmsInfo) ProtoReflect() protoreflect.Message {
	mi := &file_response_account_rms_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseAccountRmsInfo.ProtoReflect.Descriptor instead.
func (*ResponseAccountRmsInfo) Descriptor() ([]byte, []int) {
	return file_response_account_rms_info_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseAccountRmsInfo) GetTemplateId() int32 {
	if x != nil && x.TemplateId != nil {
		return *x.TemplateId
	}
	return 0
}

func (x *ResponseAccountRmsInfo) GetUserMsg() []string {
	if x != nil {
		return x.UserMsg
	}
	return nil
}

func (x *ResponseAccountRmsInfo) GetRqHandlerRpCode() []string {
	if x != nil {
		return x.RqHandlerRpCode
	}
	return nil
}

func (x *ResponseAccountRmsInfo) GetRpCode() []string {
	if x != nil {
		return x.RpCode
	}
	return nil
}

func (x *ResponseAccountRmsInfo) GetPresenceBits() uint32 {
	if x != nil && x.PresenceBits != nil {
		return *x.PresenceBits
	}
	return 0
}

func (x *ResponseAccountRmsInfo) GetFcmId() string {
	if x != nil && x.FcmId != nil {
		return *x.FcmId
	}
	return ""
}

func (x *ResponseAccountRmsInfo) GetIbId() string {
	if x != nil && x.IbId != nil {
		return *x.IbId
	}
	return ""
}

func (x *ResponseAccountRmsInfo) GetAccountId() string {
	if x != nil && x.AccountId != nil {
		return *x.AccountId
	}
	return ""
}

func (x *ResponseAccountRmsInfo) GetCurrency() string {
	if x != nil && x.Currency != nil {
		return *x.Currency
	}
	return ""
}

func (x *ResponseAccountRmsInfo) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *ResponseAccountRmsInfo) GetAlgorithm() string {
	if x != nil && x.Algorithm != nil {
		return *x.Algorithm
	}
	return ""
}

func (x *ResponseAccountRmsInfo) GetAutoLiquidateCriteria() string {
	if x != nil && x.AutoLiquidateCriteria != nil {
		return *x.AutoLiquidateCriteria
	}
	return ""
}

func (x *ResponseAccountRmsInfo) GetAutoLiquidate() ResponseAccountRmsInfo_AutoLiquidateFlag {
	if x != nil && x.AutoLiquidate != nil {
		return *x.AutoLiquidate
	}
	return ResponseAccountRmsInfo_ENABLED
}

func (x *ResponseAccountRmsInfo) GetDisableOnAutoLiquidate() ResponseAccountRmsInfo_AutoLiquidateFlag {
	if x != nil && x.DisableOnAutoLiquidate != nil {
		return *x.DisableOnAutoLiquidate
	}
	return ResponseAccountRmsInfo_ENABLED
}

func (x *ResponseAccountRmsInfo) GetAutoLiquidateThreshold() float64 {
	if x != nil && x.AutoLiquidateThreshold != nil {
		return *x.AutoLiquidateThreshold
	}
	return 0
}

func (x *ResponseAccountRmsInfo) GetAutoLiquidateMaxMinAccountBalance() float64 {
	if x != nil && x.AutoLiquidateMaxMinAccountBalance != nil {
		return *x.AutoLiquidateMaxMinAccountBalance
	}
	return 0
}

func (x *ResponseAccountRmsInfo) GetLossLimit() float64 {
	if x != nil && x.LossLimit != nil {
		return *x.LossLimit
	}
	return 0
}

func (x *ResponseAccountRmsInfo) GetMinAccountBalance() float64 {
	if x != nil && x.MinAccountBalance != nil {
		return *x.MinAccountBalance
	}
	return 0
}

func (x *ResponseAccountRmsInfo) GetMinMarginBalance() float64 {
	if x != nil && x.MinMarginBalance != nil {
		return *x.MinMarginBalance
	}
	return 0
}

func (x *ResponseAccountRmsInfo) GetDefaultCommission() float64 {
	if x != nil && x.DefaultCommission != nil {
		return *x.DefaultCommission
	}
	return 0
}

func (x *ResponseAccountRmsInfo) GetBuyLimit() int32 {
	if x != nil && x.BuyLimit != nil {
		return *x.BuyLimit
	}
	return 0
}

func (x *ResponseAccountRmsInfo) GetMaxOrderQuantity() int32 {
	if x != nil && x.MaxOrderQuantity != nil {
		return *x.MaxOrderQuantity
	}
	return 0
}

func (x *ResponseAccountRmsInfo) GetSellLimit() int32 {
	if x != nil && x.SellLimit != nil {
		return *x.SellLimit
	}
	return 0
}

func (x *ResponseAccountRmsInfo) GetCheckMinAccountBalance() bool {
	if x != nil && x.CheckMinAccountBalance != nil {
		return *x.CheckMinAccountBalance
	}
	return false
}

var File_response_account_rms_info_proto protoreflect.FileDescriptor

const file_response_account_rms_info_proto_rawDesc = "" +
	"\n" +
	"\x1fresponse_account_rms_info.proto\x12\x03rti\"\xdf\n" +
	"\n" +
	"\x16ResponseAccountRmsInfo\x12!\n" +
	"\vtemplate_id\x18\xe3\xb6\t \x02(\x05R\n" +
	"templateId\x12\x1b\n" +
	"\buser_msg\x18\x98\x8d\b \x03(\tR\auserMsg\x12-\n" +
	"\x12rq_handler_rp_code\x18\x9c\x8d\b \x03(\tR\x0frqHandlerRpCode\x12\x19\n" +
	"\arp_code\x18\x9e\x8d\b \x03(\tR\x06rpCode\x12%\n" +
	"\rpresence_bits\x18\x96\xb0\t \x01(\rR\fpresenceBits\x12\x17\n" +
	"\x06fcm_id\x18\x9d\xb3\t \x01(\tR\x05fcmId\x12\x15\n" +
	"\x05ib_id\x18\x9e\xb3\t \x01(\tR\x04ibId\x12\x1f\n" +
	"\n" +
	"account_id\x18\x98\xb3\t \x01(\tR\taccountId\x12\x1c\n" +
	"\bcurrency\x18\x8f\xb6\t \x01(\tR\bcurrency\x12\x18\n" +
	"\x06status\x18\x93\xb3\t \x01(\tR\x06status\x12\x1e\n" +
	"\talgorithm\x18\xfe\x94\t \x01(\tR\talgorithm\x128\n" +
	"\x17auto_liquidate_criteria\x18\xdc\xff\a \x01(\tR\x15autoLiquidateCriteria\x12V\n" +
	"\x0eauto_liquidate\x18\xdb\xff\a \x01(\x0e2-.rti.ResponseAccountRmsInfo.AutoLiquidateFlagR\rautoLiquidate\x12j\n" +
	"\x19disable_on_auto_liquidate\x18\xde\xff\a \x01(\x0e2-.rti.ResponseAccountRmsInfo.AutoLiquidateFlagR\x16disableOnAutoLiquidate\x12:\n" +
	"\x18auto_liquidate_threshold\x18\xdd\xff\a \x01(\x01R\x16autoLiquidateThreshold\x12S\n" +
	"&auto_liquidate_max_min_account_balance\x18\xdf\xff\a \x01(\x01R!autoLiquidateMaxMinAccountBalance\x12\x1f\n" +
	"\n" +
	"loss_limit\x18\xa3\xb3\t \x01(\x01R\tlossLimit\x120\n" +
	"\x13min_account_balance\x18\xa8\xca\t \x01(\x01R\x11minAccountBalance\x12.\n" +
	"\x12min_margin_balance\x18\xb0\xca\t \x01(\x01R\x10minMarginBalance\x12/\n" +
	"\x12default_commission\x18\x98\xae\t \x01(\x01R\x11defaultCommission\x12\x1d\n" +
	"\tbuy_limit\x18\x99\xb3\t \x01(\x05R\bbuyLimit\x12.\n" +
	"\x12max_order_quantity\x18\x99\xdc\x06 \x01(\x05R\x10maxOrderQuantity\x12\x1f\n" +
	"\n" +
	"sell_limit\x18\xb3\xb3\t \x01(\x05R\tsellLimit\x12;\n" +
	"\x19check_min_account_balance\x18\xac\xca\t \x01(\bR\x16checkMinAccountBalance\"\xca\x01\n" +
	"\fPresenceBits\x12\r\n" +
	"\tBUY_LIMIT\x10\x01\x12\x0e\n" +
	"\n" +
	"SELL_LIMIT\x10\x02\x12\x0e\n" +
	"\n" +
	"LOSS_LIMIT\x10\x04\x12\x16\n" +
	"\x12MAX_ORDER_QUANTITY\x10\b\x12\x17\n" +
	"\x13MIN_ACCOUNT_BALANCE\x10\x10\x12\x16\n" +
	"\x12MIN_MARGIN_BALANCE\x10 \x12\r\n" +
	"\tALGORITHM\x10@\x12\v\n" +
	"\x06STATUS\x10\x80\x01\x12\r\n" +
	"\bCURRENCY\x10\x80\x02\x12\x17\n" +
	"\x12DEFAULT_COMMISSION\x10\x80\x04\".\n" +
	"\x11AutoLiquidateFlag\x12\v\n" +
	"\aENABLED\x10\x01\x12\f\n" +
	"\bDISABLED\x10\x02B\x1eZ\x1cquant/extensions/rithmic/api"

var (
	file_response_account_rms_info_proto_rawDescOnce sync.Once
	file_response_account_rms_info_proto_rawDescData []byte
)

func file_response_account_rms_info_proto_rawDescGZIP() []byte {
	file_response_account_rms_info_proto_rawDescOnce.Do(func() {
		file_response_account_rms_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_response_account_rms_info_proto_rawDesc), len(file_response_account_rms_info_proto_rawDesc)))
	})
	return file_response_account_rms_info_proto_rawDescData
}

var file_response_account_rms_info_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_response_account_rms_info_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_response_account_rms_info_proto_goTypes = []any{
	(ResponseAccountRmsInfo_PresenceBits)(0),      // 0: rti.ResponseAccountRmsInfo.PresenceBits
	(ResponseAccountRmsInfo_AutoLiquidateFlag)(0), // 1: rti.ResponseAccountRmsInfo.AutoLiquidateFlag
	(*ResponseAccountRmsInfo)(nil),                // 2: rti.ResponseAccountRmsInfo
}
var file_response_account_rms_info_proto_depIdxs = []int32{
	1, // 0: rti.ResponseAccountRmsInfo.auto_liquidate:type_name -> rti.ResponseAccountRmsInfo.AutoLiquidateFlag
	1, // 1: rti.ResponseAccountRmsInfo.disable_on_auto_liquidate:type_name -> rti.ResponseAccountRmsInfo.AutoLiquidateFlag
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_response_account_rms_info_proto_init() }
func file_response_account_rms_info_proto_init() {
	if File_response_account_rms_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_response_account_rms_info_proto_rawDesc), len(file_response_account_rms_info_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_response_account_rms_info_proto_goTypes,
		DependencyIndexes: file_response_account_rms_info_proto_depIdxs,
		EnumInfos:         file_response_account_rms_info_proto_enumTypes,
		MessageInfos:      file_response_account_rms_info_proto_msgTypes,
	}.Build()
	File_response_account_rms_info_proto = out.File
	file_response_account_rms_info_proto_goTypes = nil
	file_response_account_rms_info_proto_depIdxs = nil
}
