// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: response_oco_order.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseOCOOrder struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TemplateId      *int32                 `protobuf:"varint,154467,req,name=template_id,json=templateId" json:"template_id,omitempty"`                   // PB_OFFSET + MNM_TEMPLATE_ID
	UserMsg         []string               `protobuf:"bytes,132760,rep,name=user_msg,json=userMsg" json:"user_msg,omitempty"`                             // PB_OFFSET + MNM_USER_MSG
	UserTag         []string               `protobuf:"bytes,154119,rep,name=user_tag,json=userTag" json:"user_tag,omitempty"`                             // PB_OFFSET + MNM_USER_ORIGIN
	RqHandlerRpCode []string               `protobuf:"bytes,132764,rep,name=rq_handler_rp_code,json=rqHandlerRpCode" json:"rq_handler_rp_code,omitempty"` // PB_OFFSET + MNM_REQUEST_HANDLER_RESPONSE_CODE
	RpCode          []string               `protobuf:"bytes,132766,rep,name=rp_code,json=rpCode" json:"rp_code,omitempty"`                                // PB_OFFSET + MNM_RESPONSE_CODE
	BasketId        []string               `protobuf:"bytes,110300,rep,name=basket_id,json=basketId" json:"basket_id,omitempty"`                          // PB_OFFSET + MNM_BASKET_ID
	Ssboe           []int32                `protobuf:"varint,150100,rep,name=ssboe" json:"ssboe,omitempty"`                                               // PB_OFFSET + MNM_SECONDS_SINCE_BOE
	Usecs           []int32                `protobuf:"varint,150101,rep,name=usecs" json:"usecs,omitempty"`                                               // PB_OFFSET + MNM_USECS
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResponseOCOOrder) Reset() {
	*x = ResponseOCOOrder{}
	mi := &file_response_oco_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseOCOOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseOCOOrder) ProtoMessage() {}

func (x *ResponseOCOOrder) ProtoReflect() protoreflect.Message {
	mi := &file_response_oco_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseOCOOrder.ProtoReflect.Descriptor instead.
func (*ResponseOCOOrder) Descriptor() ([]byte, []int) {
	return file_response_oco_order_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseOCOOrder) GetTemplateId() int32 {
	if x != nil && x.TemplateId != nil {
		return *x.TemplateId
	}
	return 0
}

func (x *ResponseOCOOrder) GetUserMsg() []string {
	if x != nil {
		return x.UserMsg
	}
	return nil
}

func (x *ResponseOCOOrder) GetUserTag() []string {
	if x != nil {
		return x.UserTag
	}
	return nil
}

func (x *ResponseOCOOrder) GetRqHandlerRpCode() []string {
	if x != nil {
		return x.RqHandlerRpCode
	}
	return nil
}

func (x *ResponseOCOOrder) GetRpCode() []string {
	if x != nil {
		return x.RpCode
	}
	return nil
}

func (x *ResponseOCOOrder) GetBasketId() []string {
	if x != nil {
		return x.BasketId
	}
	return nil
}

func (x *ResponseOCOOrder) GetSsboe() []int32 {
	if x != nil {
		return x.Ssboe
	}
	return nil
}

func (x *ResponseOCOOrder) GetUsecs() []int32 {
	if x != nil {
		return x.Usecs
	}
	return nil
}

var File_response_oco_order_proto protoreflect.FileDescriptor

const file_response_oco_order_proto_rawDesc = "" +
	"\n" +
	"\x18response_oco_order.proto\x12\x03rti\"\x88\x02\n" +
	"\x10ResponseOCOOrder\x12!\n" +
	"\vtemplate_id\x18\xe3\xb6\t \x02(\x05R\n" +
	"templateId\x12\x1b\n" +
	"\buser_msg\x18\x98\x8d\b \x03(\tR\auserMsg\x12\x1b\n" +
	"\buser_tag\x18\x87\xb4\t \x03(\tR\auserTag\x12-\n" +
	"\x12rq_handler_rp_code\x18\x9c\x8d\b \x03(\tR\x0frqHandlerRpCode\x12\x19\n" +
	"\arp_code\x18\x9e\x8d\b \x03(\tR\x06rpCode\x12\x1d\n" +
	"\tbasket_id\x18\xdc\xdd\x06 \x03(\tR\bbasketId\x12\x16\n" +
	"\x05ssboe\x18Ԕ\t \x03(\x05R\x05ssboe\x12\x16\n" +
	"\x05usecs\x18Ք\t \x03(\x05R\x05usecsB\x1eZ\x1cquant/extensions/rithmic/api"

var (
	file_response_oco_order_proto_rawDescOnce sync.Once
	file_response_oco_order_proto_rawDescData []byte
)

func file_response_oco_order_proto_rawDescGZIP() []byte {
	file_response_oco_order_proto_rawDescOnce.Do(func() {
		file_response_oco_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_response_oco_order_proto_rawDesc), len(file_response_oco_order_proto_rawDesc)))
	})
	return file_response_oco_order_proto_rawDescData
}

var file_response_oco_order_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_response_oco_order_proto_goTypes = []any{
	(*ResponseOCOOrder)(nil), // 0: rti.ResponseOCOOrder
}
var file_response_oco_order_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_response_oco_order_proto_init() }
func file_response_oco_order_proto_init() {
	if File_response_oco_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_response_oco_order_proto_rawDesc), len(file_response_oco_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_response_oco_order_proto_goTypes,
		DependencyIndexes: file_response_oco_order_proto_depIdxs,
		MessageInfos:      file_response_oco_order_proto_msgTypes,
	}.Build()
	File_response_oco_order_proto = out.File
	file_response_oco_order_proto_goTypes = nil
	file_response_oco_order_proto_depIdxs = nil
}
