// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: response_give_tick_size_type_table.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// bit constants are defined using enum
type ResponseGiveTickSizeTypeTable_PresenceBits int32

const (
	ResponseGiveTickSizeTypeTable_TICK_SIZE_FIRST_PRICE ResponseGiveTickSizeTypeTable_PresenceBits = 1
	ResponseGiveTickSizeTypeTable_TICK_SIZE_LAST_PRICE  ResponseGiveTickSizeTypeTable_PresenceBits = 2
	ResponseGiveTickSizeTypeTable_TICK_SIZE_FP_OPERATOR ResponseGiveTickSizeTypeTable_PresenceBits = 4
	ResponseGiveTickSizeTypeTable_TICK_SIZE_LP_OPERATOR ResponseGiveTickSizeTypeTable_PresenceBits = 8
)

// Enum value maps for ResponseGiveTickSizeTypeTable_PresenceBits.
var (
	ResponseGiveTickSizeTypeTable_PresenceBits_name = map[int32]string{
		1: "TICK_SIZE_FIRST_PRICE",
		2: "TICK_SIZE_LAST_PRICE",
		4: "TICK_SIZE_FP_OPERATOR",
		8: "TICK_SIZE_LP_OPERATOR",
	}
	ResponseGiveTickSizeTypeTable_PresenceBits_value = map[string]int32{
		"TICK_SIZE_FIRST_PRICE": 1,
		"TICK_SIZE_LAST_PRICE":  2,
		"TICK_SIZE_FP_OPERATOR": 4,
		"TICK_SIZE_LP_OPERATOR": 8,
	}
)

func (x ResponseGiveTickSizeTypeTable_PresenceBits) Enum() *ResponseGiveTickSizeTypeTable_PresenceBits {
	p := new(ResponseGiveTickSizeTypeTable_PresenceBits)
	*p = x
	return p
}

func (x ResponseGiveTickSizeTypeTable_PresenceBits) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseGiveTickSizeTypeTable_PresenceBits) Descriptor() protoreflect.EnumDescriptor {
	return file_response_give_tick_size_type_table_proto_enumTypes[0].Descriptor()
}

func (ResponseGiveTickSizeTypeTable_PresenceBits) Type() protoreflect.EnumType {
	return &file_response_give_tick_size_type_table_proto_enumTypes[0]
}

func (x ResponseGiveTickSizeTypeTable_PresenceBits) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ResponseGiveTickSizeTypeTable_PresenceBits) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ResponseGiveTickSizeTypeTable_PresenceBits(num)
	return nil
}

// Deprecated: Use ResponseGiveTickSizeTypeTable_PresenceBits.Descriptor instead.
func (ResponseGiveTickSizeTypeTable_PresenceBits) EnumDescriptor() ([]byte, []int) {
	return file_response_give_tick_size_type_table_proto_rawDescGZIP(), []int{0, 0}
}

type ResponseGiveTickSizeTypeTable struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TemplateId         *int32                 `protobuf:"varint,154467,req,name=template_id,json=templateId" json:"template_id,omitempty"`                              // PB_OFFSET + MNM_TEMPLATE_ID
	UserMsg            []string               `protobuf:"bytes,132760,rep,name=user_msg,json=userMsg" json:"user_msg,omitempty"`                                        // PB_OFFSET + MNM_USER_MSG
	RqHandlerRpCode    []string               `protobuf:"bytes,132764,rep,name=rq_handler_rp_code,json=rqHandlerRpCode" json:"rq_handler_rp_code,omitempty"`            // PB_OFFSET + MNM_REQUEST_HANDLER_RESPONSE_CODE
	RpCode             []string               `protobuf:"bytes,132766,rep,name=rp_code,json=rpCode" json:"rp_code,omitempty"`                                           // PB_OFFSET + MNM_RESPONSE_CODE
	PresenceBits       *uint32                `protobuf:"varint,149138,opt,name=presence_bits,json=presenceBits" json:"presence_bits,omitempty"`                        // PB_OFFSET + MNM_PRICING_INDICATOR
	TickSizeType       *string                `protobuf:"bytes,154167,opt,name=tick_size_type,json=tickSizeType" json:"tick_size_type,omitempty"`                       // PB_OFFSET + MNM_TICK_SIZE_TYPE
	TickSizeFpOperator *string                `protobuf:"bytes,154170,opt,name=tick_size_fp_operator,json=tickSizeFpOperator" json:"tick_size_fp_operator,omitempty"`   // PB_OFFSET + MNM_TICK_SIZE_FP_OPERATOR
	TickSizeLpOperator *string                `protobuf:"bytes,154171,opt,name=tick_size_lp_operator,json=tickSizeLpOperator" json:"tick_size_lp_operator,omitempty"`   // PB_OFFSET + MNM_TICK_SIZE_LP_OPERATOR
	MinFpriceChange    *float64               `protobuf:"fixed64,154387,opt,name=min_fprice_change,json=minFpriceChange" json:"min_fprice_change,omitempty"`            // PB_OFFSET + MNM_MIN_FPRICE_CHANGE
	TickSizeFirstPrice *float64               `protobuf:"fixed64,154168,opt,name=tick_size_first_price,json=tickSizeFirstPrice" json:"tick_size_first_price,omitempty"` // PB_OFFSET + MNM_TICK_SIZE_FIRST_PRICE
	TickSizeLastPrice  *float64               `protobuf:"fixed64,154169,opt,name=tick_size_last_price,json=tickSizeLastPrice" json:"tick_size_last_price,omitempty"`    // PB_OFFSET + MNM_TICK_SIZE_LAST_PRICE
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ResponseGiveTickSizeTypeTable) Reset() {
	*x = ResponseGiveTickSizeTypeTable{}
	mi := &file_response_give_tick_size_type_table_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseGiveTickSizeTypeTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGiveTickSizeTypeTable) ProtoMessage() {}

func (x *ResponseGiveTickSizeTypeTable) ProtoReflect() protoreflect.Message {
	mi := &file_response_give_tick_size_type_table_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGiveTickSizeTypeTable.ProtoReflect.Descriptor instead.
func (*ResponseGiveTickSizeTypeTable) Descriptor() ([]byte, []int) {
	return file_response_give_tick_size_type_table_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseGiveTickSizeTypeTable) GetTemplateId() int32 {
	if x != nil && x.TemplateId != nil {
		return *x.TemplateId
	}
	return 0
}

func (x *ResponseGiveTickSizeTypeTable) GetUserMsg() []string {
	if x != nil {
		return x.UserMsg
	}
	return nil
}

func (x *ResponseGiveTickSizeTypeTable) GetRqHandlerRpCode() []string {
	if x != nil {
		return x.RqHandlerRpCode
	}
	return nil
}

func (x *ResponseGiveTickSizeTypeTable) GetRpCode() []string {
	if x != nil {
		return x.RpCode
	}
	return nil
}

func (x *ResponseGiveTickSizeTypeTable) GetPresenceBits() uint32 {
	if x != nil && x.PresenceBits != nil {
		return *x.PresenceBits
	}
	return 0
}

func (x *ResponseGiveTickSizeTypeTable) GetTickSizeType() string {
	if x != nil && x.TickSizeType != nil {
		return *x.TickSizeType
	}
	return ""
}

func (x *ResponseGiveTickSizeTypeTable) GetTickSizeFpOperator() string {
	if x != nil && x.TickSizeFpOperator != nil {
		return *x.TickSizeFpOperator
	}
	return ""
}

func (x *ResponseGiveTickSizeTypeTable) GetTickSizeLpOperator() string {
	if x != nil && x.TickSizeLpOperator != nil {
		return *x.TickSizeLpOperator
	}
	return ""
}

func (x *ResponseGiveTickSizeTypeTable) GetMinFpriceChange() float64 {
	if x != nil && x.MinFpriceChange != nil {
		return *x.MinFpriceChange
	}
	return 0
}

func (x *ResponseGiveTickSizeTypeTable) GetTickSizeFirstPrice() float64 {
	if x != nil && x.TickSizeFirstPrice != nil {
		return *x.TickSizeFirstPrice
	}
	return 0
}

func (x *ResponseGiveTickSizeTypeTable) GetTickSizeLastPrice() float64 {
	if x != nil && x.TickSizeLastPrice != nil {
		return *x.TickSizeLastPrice
	}
	return 0
}

var File_response_give_tick_size_type_table_proto protoreflect.FileDescriptor

const file_response_give_tick_size_type_table_proto_rawDesc = "" +
	"\n" +
	"(response_give_tick_size_type_table.proto\x12\x03rti\"\xf3\x04\n" +
	"\x1dResponseGiveTickSizeTypeTable\x12!\n" +
	"\vtemplate_id\x18\xe3\xb6\t \x02(\x05R\n" +
	"templateId\x12\x1b\n" +
	"\buser_msg\x18\x98\x8d\b \x03(\tR\auserMsg\x12-\n" +
	"\x12rq_handler_rp_code\x18\x9c\x8d\b \x03(\tR\x0frqHandlerRpCode\x12\x19\n" +
	"\arp_code\x18\x9e\x8d\b \x03(\tR\x06rpCode\x12%\n" +
	"\rpresence_bits\x18\x92\x8d\t \x01(\rR\fpresenceBits\x12&\n" +
	"\x0etick_size_type\x18\xb7\xb4\t \x01(\tR\ftickSizeType\x123\n" +
	"\x15tick_size_fp_operator\x18\xba\xb4\t \x01(\tR\x12tickSizeFpOperator\x123\n" +
	"\x15tick_size_lp_operator\x18\xbb\xb4\t \x01(\tR\x12tickSizeLpOperator\x12,\n" +
	"\x11min_fprice_change\x18\x93\xb6\t \x01(\x01R\x0fminFpriceChange\x123\n" +
	"\x15tick_size_first_price\x18\xb8\xb4\t \x01(\x01R\x12tickSizeFirstPrice\x121\n" +
	"\x14tick_size_last_price\x18\xb9\xb4\t \x01(\x01R\x11tickSizeLastPrice\"y\n" +
	"\fPresenceBits\x12\x19\n" +
	"\x15TICK_SIZE_FIRST_PRICE\x10\x01\x12\x18\n" +
	"\x14TICK_SIZE_LAST_PRICE\x10\x02\x12\x19\n" +
	"\x15TICK_SIZE_FP_OPERATOR\x10\x04\x12\x19\n" +
	"\x15TICK_SIZE_LP_OPERATOR\x10\bB\x1eZ\x1cquant/extensions/rithmic/api"

var (
	file_response_give_tick_size_type_table_proto_rawDescOnce sync.Once
	file_response_give_tick_size_type_table_proto_rawDescData []byte
)

func file_response_give_tick_size_type_table_proto_rawDescGZIP() []byte {
	file_response_give_tick_size_type_table_proto_rawDescOnce.Do(func() {
		file_response_give_tick_size_type_table_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_response_give_tick_size_type_table_proto_rawDesc), len(file_response_give_tick_size_type_table_proto_rawDesc)))
	})
	return file_response_give_tick_size_type_table_proto_rawDescData
}

var file_response_give_tick_size_type_table_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_response_give_tick_size_type_table_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_response_give_tick_size_type_table_proto_goTypes = []any{
	(ResponseGiveTickSizeTypeTable_PresenceBits)(0), // 0: rti.ResponseGiveTickSizeTypeTable.PresenceBits
	(*ResponseGiveTickSizeTypeTable)(nil),           // 1: rti.ResponseGiveTickSizeTypeTable
}
var file_response_give_tick_size_type_table_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_response_give_tick_size_type_table_proto_init() }
func file_response_give_tick_size_type_table_proto_init() {
	if File_response_give_tick_size_type_table_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_response_give_tick_size_type_table_proto_rawDesc), len(file_response_give_tick_size_type_table_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_response_give_tick_size_type_table_proto_goTypes,
		DependencyIndexes: file_response_give_tick_size_type_table_proto_depIdxs,
		EnumInfos:         file_response_give_tick_size_type_table_proto_enumTypes,
		MessageInfos:      file_response_give_tick_size_type_table_proto_msgTypes,
	}.Build()
	File_response_give_tick_size_type_table_proto = out.File
	file_response_give_tick_size_type_table_proto_goTypes = nil
	file_response_give_tick_size_type_table_proto_depIdxs = nil
}
